### ISSUE TITLE
single channel 2d input layer with h5py

### ISSUE THREAD

**Issue by micheleAlberto** [tflearn/tflearn#100]
I can' t explain why the following program does not train the simple model but i suspect it is because the training set use monochromatic images (with only one channel).
The training set is made of 5635 420x580 grayscale images.
I tried 2 variants of the following program and observed different errors as more data is provided to the algorithm.
```python
import tflearn
from tflearn.layers.core import input_data
from tflearn.layers.conv import conv_2d
from tflearn.layers.estimator import regression
import h5py
import numpy as np

tflearn.init_graph(num_cores=8)
network = input_data(
    shape=[None, 420, 580,1], 
    name='input')
#First element should be 'None' (representing batch size)
network = conv_2d(network, 
    32,#The number of convolutional filters
    3, #(Pixel) size of filters
    activation='relu',
    regularizer="L2")
network = conv_2d(network, 
    32,#The number of convolutional filters
    3, #(Pixel) size of filters
    activation='sigmoid'
    )
network = tflearn.regression(network, optimizer='adam', loss='binary_crossentropy')
model = tflearn.DNN(network)

h5f = h5py.File('dataset.h5', 'r')
# VARIANT 1: some data
X = h5f['data_X'][:200]
Y = h5f['data_Y'][:200]
#VARIANT 2: full data
X = h5f['data_X']
Y = h5f['data_Y']
print 'X :',X.shape,X.dtype
print 'Y :',Y.shape,Y.dtype
model.fit(X, Y, 
    n_epoch=50, 
    shuffle=True, 
    show_metric=True, 
    batch_size=96, 
    run_id='data_cnn')

```
will output

```
X : (200, 420, 580, 1) float32
Y : (200, 420, 580, 1) float32
---------------------------------
Run id: data_cnn
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 200
Validation samples: 0
--
--
```
VARIANT 1
and then throw a ValueError:
```
Traceback (most recent call last):
  File "simpleTrain.py", line 36, in <module>
    run_id='UltrasoundNerveSegmentation_cnn')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 183, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 263, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 668, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 506, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (96, 420, 580, 1) for Tensor u'TargetsData/Y:0', which has shape '(?, 420, 580, 32)'

```
VARIANT 2
but if we keep the whole dataset it throw an Attribute error from a thread:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_flow.py", line 183, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_flow.py", line 217, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/utils.py", line 164, in slice_array
    return [X[i] for i in start]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 367, in __getitem__
    if self._local.astype is not None:
AttributeError: 'thread._local' object has no attribute 'astype'
```

**Comment by aymericdamien** [comment]
Hi, do you have the latest version of TFLearn? There was a bug about the input shape. Can you try to update TFLearn?
```
pip uninstall tflearn
pip install git+https://github.com/tflearn/tflearn.git
```

I tried mnist convnet example (single channel images) with hdf5 dataset, but didn't run into any issue.

**Comment by micheleAlberto** [comment]
Tried, still there; you are right, i should have run the example before.
The example use_hdf5.py ( https://github.com/tflearn/tflearn/blob/master/examples/basics/use_hdf5.py )
result in a similar error:
```
Downloading CIFAR 10, Please wait...
('Succesfully downloaded', 'cifar-10-python.tar.gz', 170498071, 'bytes.')
File Extracted in Current Directory
---------------------------------
Run id: cifar10_cnn
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 50000
Validation samples: 10000
--
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_flow.py", line 183, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_flow.py", line 217, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/utils.py", line 164, in slice_array
    return [X[i] for i in start]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 367, in __getitem__
    if self._local.astype is not None:
AttributeError: 'thread._local' object has no attribute 'astype'
```

This tells us that it has nothing to do with serialization of 1-shaped tensors, but may be something else,  maybe relating to configuration.
```
Name: TFLearn Version: 0.1
Name: numpy Version: 1.8.2
Name: six Version: 1.5.2
Name: Pillow Version: 2.6.1
Name: protobuf Version: 2.6.1
Name: wheel Version: 0.29.0
```

**Comment by aymericdamien** [comment]
Maybe there is an issue with h5py, which version are you using?

**Comment by micheleAlberto** [comment]
I could solve it updating tensorflow, h5py, and protobuf. 
In case something like this happen notice that debian put a patch on pip (the python package manager) that may forbid to delete or upgrade a package if it is open by the OS but it may happen that the OS does not release the lock.

**Comment by victorhcm** [comment]
This solved for me too. If you try to upgrade h5py through pip and it still isn't showing the newer version, remove python-h5py (`sudo apt-get remove python-h5py`) which overshadows it and run `pip install --upgrade h5py` again.
