### ISSUE TITLE
Running problem when load model

### ISSUE THREAD

**Issue by transform19** [tflearn/tflearn#1015]
I got an error when I try to run vgg16_network_finetuning. The model was got by vgg16_network. And I do not know why this problem occured. Please help me，THANKS.
```
2018-02-04 18:53:24.778187: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv2_2/W not found in checkpoint
2018-02-04 18:53:24.778390: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_3/W not found in checkpoint
2018-02-04 18:53:24.778533: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_1/b not found in checkpoint
2018-02-04 18:53:24.778617: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_3/b not found in checkpoint
2018-02-04 18:53:24.778642: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_2/W not found in checkpoint
2018-02-04 18:53:24.780011: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_1/W not found in checkpoint
2018-02-04 18:53:24.779990: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv2_2/b not found in checkpoint
2018-02-04 18:53:24.781808: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv3_2/b not found in checkpoint
2018-02-04 18:53:24.782801: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_1/b not found in checkpoint
2018-02-04 18:53:24.783445: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_1/W not found in checkpoint
2018-02-04 18:53:24.783565: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv2_1/b not found in checkpoint
2018-02-04 18:53:24.783820: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_2/W not found in checkpoint
2018-02-04 18:53:24.785238: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_3/W not found in checkpoint
2018-02-04 18:53:24.785915: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_3/b not found in checkpoint
2018-02-04 18:53:24.786681: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv4_2/b not found in checkpoint
2018-02-04 18:53:24.787220: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_1/W not found in checkpoint
2018-02-04 18:53:24.790538: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_1/b not found in checkpoint
2018-02-04 18:53:24.790844: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_2/W not found in checkpoint
2018-02-04 18:53:24.791587: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv2_1/W not found in checkpoint
2018-02-04 18:53:24.792233: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_3/W not found in checkpoint
2018-02-04 18:53:24.792436: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_2/b not found in checkpoint
2018-02-04 18:53:24.794496: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv5_3/b not found in checkpoint
2018-02-04 18:53:24.795506: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key fc6/b not found in checkpoint
2018-02-04 18:53:24.795572: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key fc6/W not found in checkpoint
2018-02-04 18:53:24.796669: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key fc7/W not found in checkpoint
2018-02-04 18:53:24.796821: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key fc7/b not found in checkpoint
2018-02-04 18:53:24.797672: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv1_2/b not found in checkpoint
2018-02-04 18:53:24.797938: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv1_1/W not found in checkpoint
2018-02-04 18:53:24.798931: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv1_1/b not found in checkpoint
2018-02-04 18:53:24.799145: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key conv1_2/W not found in checkpoint
Traceback (most recent call last):
  File "G:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "G:\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "G:\anaconda\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "G:\anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key conv2_2/W not found in checkpoint
         [[Node: save_2/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_2/Const_0_0, save_2/RestoreV2_6/tensor_names, save_2/RestoreV2_6/shape_and_slices)]]
         [[Node: save_2/RestoreV2_19/_29 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_84_save_2/RestoreV2_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

```

**Comment by HarshalGarg** [comment]
Try to change the batch size. i got same error but solved when changed the batch size.
