### ISSUE TITLE
Why tflearn does not use GPU to train my network automatically?

### ISSUE THREAD

**Issue by StephenGreat** [tflearn/tflearn#1030]
My platform is：
TensorFlow-GPU 1.4.0
tflearn 0.3.2
GTX 1080Ti

But when I'm running the demo [code](https://github.com/tflearn/tflearn/blob/master/examples/images/vgg_network.py),
tflearn **choses the CPU** to train the network rather than GPU?
How to solve this problem?

**Comment by lyocean17** [comment]
same problem

**Comment by Aleks59** [comment]
Me too. TFlearn seems just don't use a gpu in any ways like "tf.device('/gpu:0')".

**Comment by Dentrax** [comment]
Same here:

with tf.device('/gpu:0'):
        self.model.fit(blablabla)

Not works...

Versions:

```
tensorflow==1.7.0
tflearn==0.3.2
tensorflow-gpu==1.4.0
```

How can i fix that CUDA incompatible problem?

Output:

```
Traceback (most recent call last):
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emotion_recognition.py", line 5, in <module>
    import tensorflow as tf
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
