### ISSUE TITLE
Found "IndexError: list index out of range"error while running cat and dog classifier.

### ISSUE THREAD

**Issue by devmishrs** [tflearn/tflearn#1032]
I'm building a classifier for Dog and Cat with CNN. I'm following this [link](https://pythonprogramming.net/convolutional-neural-network-kats-vs-dogs-machine-learning-tutorial/l). I'm using jupyter notebook for that. And I also tried by restarting the kernel.

My code is
`import cv2
import numpy as np
import os
from random import shuffle
from tqdm import tqdm
import tensorflow as tf

TRAIN_DIR ='data/train/'
TEST_DIR = 'data/test/'
IMG_SIZE = 50
LR = 1e-3

MODEL_NAME = 'dogsvscat-{}-{}.model'.format(LR,'2conv-basic-video')

tf.reset_default_graph()

def label_img(img):
    word_label = img.split('.')[-3]
    if word_label == 'cat': return[1,0]
    elif word_label == 'dog':return[0,1]
    
    
def create_train_data():
    training_data = []
    for img in tqdm(os.listdir(TRAIN_DIR)):
        label = label_img(img)
        path = os.path.join(TRAIN_DIR,img)
        img = cv2.resize(cv2.imread(path, cv2.IMREAD_GRAYSCALE),(IMG_SIZE,IMG_SIZE))
    training_data.append([np.array(img),np.array(label)])
    np.save('rain_data.npy',training_data)
    return training_data

def process_test_data():
    testing_data=[]
    for img in tqdm(os.listdir(TEST_DIR)):
        path= os.path.join(TEST_DIR,img)
        img_num = img.split('.')[0]
        img= cv2.resize(cv2.imread(path, cv2.IMREAD_GRAYSCALE),(IMG_SIZE,IMG_SIZE))
        testing_data.appent([np.array(img),img_num])
        
    np.save("test_data.npy",testing_data)
    return testing_data

train_data = create_train_data()

import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 2, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet, tensorboard_dir='log')

if os.path.exists('{}.meta'.format(MODEL_NAME)):
    model.load(MODEL_NAME)
    print('model loaded!!')
    
train =train_data[:-500]
test = train_data[-500:]

X =np.array([i[0] for i in train]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
Y =[i[1] for i in train]

test_x =np.array([i[0] for i in test]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
test_y =[i[1] for i in test]

model.fit({'input': X}, {'targets': Y}, n_epoch=3, validation_set=({'input': test_x}, {'targets': test_y}), 
    snapshot_step=500, show_metric=True, run_id=MODEL_NAME)

`

**And I found this error.** 

_`100%|██████████| 25000/25000 [00:14<00:00, 1750.12it/s]

---------------------------------
Run id: dogsvscat-0.001-2conv-basic-video.model
Log directory: log/
INFO:tensorflow:Summary name Accuracy/ (raw) is illegal; using Accuracy/__raw_ instead.
---------------------------------
Training samples: 0
Validation samples: 1
--

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/namrata/.virtualenv/tensorflow/lib/python3.6/site-packages/tflearn/data_flow.py", line 201, in fill_batch_ids_queue
    ids = self.next_batch_ids()
  File "/home/namrata/.virtualenv/tensorflow/lib/python3.6/site-packages/tflearn/data_flow.py", line 215, in next_batch_ids
    batch_start, batch_end = self.batches[self.batch_index]
IndexError: list index out of range

`_

please help me out.

**Comment by Leon-MK** [comment]
Hey did you end up finding a fix?
