### ISSUE TITLE
TFLearn failing with MemoryError on some machines - don't know enough to fully understand why

### ISSUE THREAD

**Issue by kriston13** [tflearn/tflearn#1064]
Hi,

I'm trying out an RNN character generation example. I've basically cribbed the code from the `last_generator_shakespeare.py`, and put in my own training data from here: https://eightportions.com/datasets/Recipes/

It's a 28mb text file of recipes (including ingredients & instructions) in a json format.

All up, it comes to ~93mil text total length, and 95 distinct chars, and total 31mil sequences.

On my mac, i7 CPI, 40gb RAM, 540gb free hard drive space, the vectorisation using the `textfile_to_semi_redundant_sequences` function works, and spits out the above data.

However, I then tried the same file & data on a set of Google Compute Platform VM instances, one with 8 vCPUs, 30GB memory, 100gb HD and one with 4vCPUs, 15gb memory, 10gb HD + a K80 GPU
And in both scenarios, during the `textfile_to_semi_redundant_sequences` function (it prints out 'Vectorizing text...`), I then get a MemoryError saying:

```
hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!
corpus length:  93702755
total chars:  95
Vectorizing text...
Traceback (most recent call last):
  File "recipe-trainer-tf.py", line 27, in <module>
    X,Y, char_idx = textfile_to_semi_redundant_sequences(file_name, seq_maxlen=maxlen, redun_step=step, pre_defined_char_idx=char_idx)
  File "/home/kriston/.local/lib/python2.7/site-packages/tflearn/data_utils.py", line 149, in textfile_to_semi_redundant_sequences
    return string_to_semi_redundant_sequences(text, seq_maxlen, redun_step, pre_defined_char_idx)
  File "/home/kriston/.local/lib/python2.7/site-packages/tflearn/data_utils.py", line 129, in string_to_semi_redundant_sequences
    X = np.zeros((len(sequences), seq_maxlen, len_chars), dtype=np.bool)
MemoryError
```

My code is configured very similar to the example, with the `learning_rate=0.01` (instead of `0.001`), and using a `for i in range(10)` instead of `50`.

Of course, the code isn't even getting there...

What I'd like some help with:
1. Why is this working on my mac, but not my GCP VMs?
2. How can I get it to work?
My very vague understanding, is that my input data NEEDS to contain the full set of characters. I'm thinking that maybe the `len(sequences)` section in the 'X=np.zeroes(...)' section shouldn't be the full set of sequences, but my vague understanding is that the batch parameter is set in the `fit(...)` function, and not the vectorisation section.

Any help please?

For reference, my full code is below:

```
from __future__ import absolute_import, division, print_function

import os
import pickle
import tflearn
from tflearn.data_utils import *

char_idx_file = 'char_idx.pickle'

# get the file
file_name = './data/recipes_raw_nosource_fn.json'

with open(file_name) as f:
    text = f.read()
print('corpus length: ', len(text))

# get the unique characters
chars = sorted(list(set(text)))
print('total chars: ',len(chars))

maxlen = 40
step = 3
char_idx = None
X,Y, char_idx = textfile_to_semi_redundant_sequences(file_name, seq_maxlen=maxlen, redun_step=step, pre_defined_char_idx=char_idx)

pickle.dump(char_idx, open(char_idx_file,'wb'))

g = tflearn.input_data([None, maxlen, len(char_idx)])
g = tflearn.lstm(g, 512, return_seq=True)
g = tflearn.dropout(g, 0.5)
g = tflearn.lstm(g, 512, return_seq=True)
g = tflearn.dropout(g, 0.5)
g = tflearn.lstm(g, 512)
g = tflearn.dropout(g, 0.5)
g = tflearn.fully_connected(g, len(char_idx), activation='softmax')
g = tflearn.regression(g,optimizer='adam', loss='categorical_crossentropy', learning_rate=0.01)

m = tflearn.SequenceGenerator(g, dictionary=char_idx, seq_maxlen=maxlen, clip_gradients=5.0, checkpoint_path='model_recipes')

for i in range(10):
    seed = random_sequence_from_textfile(file_name, maxlen)
    m.fit(X, Y, validation_set=0.1, batch_size=128, n_epoch=2, run_id='recipe')
    print("-- TESTING...")
    print("-- Test with temperature of 1.0 --")
    print(m.generate(600, temperature=1.0, seq_seed=seed))
    print("-- Test with temperature of 0.5 --")
    print(m.generate(600, temperature=0.5, seq_seed=seed))

```

**Comment by Flajt** [comment]
I am not an expert, but your RAM (I assume you mean that with 30GB and 15gb?) on both are lower than the 40GB RAM on your mac. So maybe you haven`t enough RAM on the cloud instance (because 30 and 15GB are <40GB). So I guess you need more RAM, if my assumption  was right. And for point 3:
Maybe your GPU hasn`t enough memory to do this, try minibatches instead. Hope this is helpfull.
