### ISSUE TITLE
tflearn Installation issues.

### ISSUE THREAD

**Issue by Nadedic** [tflearn/tflearn#1071]
Hello, 

I've been trying to install tflearn module for a while now and haven't been able to do so. I have checked most documentations and other problems but none seem to be usefull. 

I am using anaconda extension. I have tensorflow installed, it's current installed version is 1.8 and as far as I understood it should be higher or equal to 1.0.

I can't use anaconda navigator for some reason but the prompt is working just fine and that's where I've been trying. 

`import tflearn
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\tflearn-0.3.2-py3.6.egg\tflearn\__init__.py", line 62, in <module>
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\tflearn-0.3.2-py3.6.egg\tflearn\datasets\__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\tflearn-0.3.2-py3.6.egg\tflearn\datasets\cifar10.py", line 16, in <module>
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\tflearn-0.3.2-py3.6.egg\tflearn\data_utils.py", line 7, in <module>
  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.`

That's the error that comes up when I try to import it from the prompt. It seems like it is installed but not importable

`~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py in <module>()
     58     # Also note that Image.core is not a publicly documented interface,
     59     # and should be considered private and subject to change.
---> 60     from . import _imaging as core
     61     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     62         raise ImportError("The _imaging extension was built for another "
ImportError: DLL load failed: The specified module could not be found.`

And that's a jupyter's notebook import error. 

Please guide me!

**Comment by Nadedic** [comment]
Had to reinstall everything and pip install tflearn on a clean version of tensorflow. That did the trick.
