### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.framework'

### ISSUE THREAD

**Issue by ahbon123** [tflearn/tflearn#1078]
when i import tflearn, it says `ModuleNotFoundError: No module named 'tensorflow.contrib.framework'`,  does someone knows how to deal with this issues? thanks.

**Comment by ahbon123** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Anaconda3\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "C:\Users\User\Anaconda3\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "C:\Users\User\Anaconda3\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib.framework'

**Comment by 007fred50** [comment]
have you fix the issues? i have same porblem now
