### ISSUE TITLE
ValueError: Incompatible shapes with conv_2d_transpose

### ISSUE THREAD

**Issue by SinclairHudson** [tflearn/tflearn#1117]
I've been getting the following error when running the following code. I'm not too sure how the conv_2d_transpose layer works, so I'll do my best to explain what I want it to do. I'm making a GAN that generates 250x250 rgb images. So, the output for the generator should be (1x250x250x3), for 1 image that is 250px by 250px in three colour channels. I am generating them from random noise in the form of a [batch-size, 10, 10 3] array, which could be thought of as 10x10 rgb images. But I can't really get this to work. Let me know if you notice anything, or if I should approach the problem differently. Also, markdown really messes with my comments and turns them into headers... Thanks in advance!
`
from __future__ import division, print_function, absolute_import

import numpy as np
import tensorflow as tf
import tflearn
import data

print("loading data...")
X = data.getImages(50, 250, 250)

print(X.shape)
total_samples = len(X)

# Generator
def generator(x, reuse=False):
    with tf.variable_scope('Generator', reuse=reuse):
        # first layer is a deconvolutional layer with 4 filters, each of 5*5, outputting a larger tensor
        # that is of shape [batch, 250, 250, 4]
        x = tflearn.conv_2d_transpose(x, 4, [5, 5], [250, 250], activation='leaky_relu')
        # final layer pulls out a vector that can be reshaped to form the image.
        x = tflearn.fully_connected(x, 250*250*3, activation='leaky_relu')
        x = tflearn.reshape(x, [1, 250, 250, 3])  # reshape to look like an image
        return x

# Discriminator
def discriminator(x, reuse=False):
    with tf.variable_scope('Discriminator', reuse=reuse):
        x = tflearn.conv_2d(x, 2, [15, 15], activation='leaky_relu')
        x = tflearn.fully_connected(x, 1, activation='leaky_relu')  # pollock or fake, yes or no?
        return x

# Build Networks
gen_input = tflearn.input_data(shape=[None, 10, 10, 3], name='input_noise') #feeding generator random 10 * 10 rgb images
disc_input = tflearn.input_data(shape=[None, 250, 250, 3], name='disc_input') #feeding discriminator with full images

gen_sample = generator(gen_input) #these are the samples that are generated.
disc_real = discriminator(disc_input) #this is a true pollock for the discriminator
disc_fake = discriminator(gen_sample, reuse=True) #this is a fake for the discriminator

# Define Loss functions. Notice how the generator's loss is really just the negative of the discriminator's ability to
# determine fakes.
disc_loss = -tf.reduce_mean(tf.log(disc_real) + tf.log(1. - disc_fake))
gen_loss = -tf.reduce_mean(tf.log(disc_fake))

# Build Training Ops for both Generator and Discriminator.
# Each network optimization should only update its own variable, thus we need
# to retrieve each network variables (with get_layer_variables_by_scope) and set
# 'placeholder=None' because we do not need to feed any target.
gen_vars = tflearn.get_layer_variables_by_scope('Generator')
gen_model = tflearn.regression(gen_sample, placeholder=None, optimizer='adam',
                               loss=gen_loss, trainable_vars=gen_vars,
                               batch_size=64, name='target_gen', op_name='GEN')
disc_vars = tflearn.get_layer_variables_by_scope('Discriminator')
disc_model = tflearn.regression(disc_real, placeholder=None, optimizer='adam',
                                loss=disc_loss, trainable_vars=disc_vars,
                                batch_size=64, name='target_disc', op_name='DISC')
# Define GAN model, that output the generated images.
gan = tflearn.DNN(gen_model)

# Generate noise to feed to the generator
z = np.random.uniform(0, 255, size=[total_samples, 10, 10, 3])
# Start training, feed both noise and real images.
gan.fit(X_inputs={gen_input: z, disc_input: X},
        Y_targets=None,
        n_epoch=1000)
`
# Running this leads to the following error:

Traceback (most recent call last):
  File "/home/sinclair/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 558, in set_shape
    unknown_shape)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 250 and 10. Shapes are [?,250,250,3] and [?,10,10,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sinclair/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 841, in _GradientsHelper
    in_grad.set_shape(t_in.get_shape())
  File "/home/sinclair/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 561, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 250 and 10. Shapes are [?,250,250,3] and [?,10,10,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sinclair/Desktop/Pollocks/Pollock.py", line 60, in <module>
    gan = tflearn.DNN(gen_model)
  File "/home/sinclair/.local/lib/python3.6/site-packages/tflearn/models/dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/home/sinclair/.local/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 131, in __init__
    clip_gradients)
  File "/home/sinclair/.local/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 697, in initialize_training_ops
    self.grad = tf.gradients(total_loss, self.train_vars)
  File "/home/sinclair/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/sinclair/.local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 848, in _GradientsHelper
    (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: Generator/Conv2DTranspose/conv2d_transpose.  Input index: 2. Original input shape: (?, 10, 10, 3).  Calculated input gradient shape: (?, 250, 250, 3)`
>

**Comment by SinclairHudson** [comment]
Figured it out! From what I understand, the stride parameter in the 2D conv transpose outlines how the filters slide over the image.  It's helpful to think of transpose convolution in the reverse. In the reverse, I was trying to go from 250*250 to 10*10 images. But if strides = 1, then I'm processing all 250*250 pixels with the filter... and all that data can't map to the 10*10, smaller image. So instead, I've gotta skip over some pixels in the larger image, so that in the end I only apply the filter 100 times. This means that I need a stride of 25. That fixed the problem.
