### ISSUE TITLE
Unable to load saved model (model.load('./model.tflearn'))

### ISSUE THREAD

**Issue by tchax3742** [tflearn/tflearn#1123]
when i run model.load('./model.tflearn') i get the following error

INFO:tensorflow:Restoring parameters from /home/tatenda/tf/tf_env/model.tflearn
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

NotFoundError: Key Accuracy/Mean/moving_avg_1 not found in checkpoint
	 [[{{node save_5/RestoreV2}}]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1275         sess.run(self.saver_def.restore_op_name,
-> 1276                  {self.saver_def.filename_tensor_name: save_path})
   1277     except errors.NotFoundError as err:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 

NotFoundError: Key Accuracy/Mean/moving_avg_1 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at /home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py:147) ]]

Caused by op 'save_5/RestoreV2', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in _run_cell
    return runner(coro)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3044, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3209, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-6497c75ac4c0>", line 9, in <module>
    model = tflearn.DNN(net, tensorboard_dir='tflearn_logs')
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/models/dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 147, in __init__
    allow_empty=True)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key Accuracy/Mean/moving_avg_1 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at /home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py:147) ]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1285       try:
-> 1286         names_to_keys = object_graph_key_mapping(save_path)
   1287       except errors.NotFoundError:

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py in object_graph_key_mapping(checkpoint_path)
   1590   object_graph_string = reader.get_tensor(
-> 1591       checkpointable.OBJECT_GRAPH_PROTO_KEY)
   1592   object_graph_proto = (

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in get_tensor(self, tensor_str)
    369         return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str),
--> 370                                           status)
    371 

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive

NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-69-27684fe4c129> in <module>
      1 # load our saved model
----> 2 model.load('./model.tflearn')

~/tf/tf_env/lib/python3.6/site-packages/tflearn/models/dnn.py in load(self, model_file, weights_only, **optargs)
    306                      created for the restored variables.
    307         """
--> 308         self.trainer.restore(model_file, weights_only, **optargs)
    309         self.session = self.trainer.session
    310         self.predictor = Evaluator([self.net],

~/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py in restore(self, model_file, trainable_variable_only, variable_name_map, scope_for_restore, create_new_session, verbose)
    488             restorer.restore(self.session, model_file)
    489         elif not trainable_variable_only:
--> 490             self.restorer.restore(self.session, model_file)
    491         else:
    492             self.restorer_trainvars.restore(self.session, model_file)

~/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1290         # a helpful message (b/110263146)
   1291         raise _wrap_restore_error_with_msg(
-> 1292             err, "a Variable name or other graph key that is missing")
   1293 
   1294       # This is an object-based checkpoint. We'll print a warning and then do

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Accuracy/Mean/moving_avg_1 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at /home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py:147) ]]

Caused by op 'save_5/RestoreV2', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in _run_cell
    return runner(coro)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3044, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3209, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-6497c75ac4c0>", line 9, in <module>
    model = tflearn.DNN(net, tensorboard_dir='tflearn_logs')
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/models/dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 147, in __init__
    allow_empty=True)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/tatenda/tf/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Accuracy/Mean/moving_avg_1 not found in checkpoint
	 [[node save_5/RestoreV2 (defined at /home/tatenda/tf/tf_env/lib/python3.6/site-packages/tflearn/helpers/trainer.py:147) ]]

what am i missing

**Comment by snakebiking49** [comment]
I get the same error.
