### ISSUE TITLE
tflearn not work with tensorflow 2.0.x

### ISSUE THREAD

**Issue by 0x536** [tflearn/tflearn#1145]
`>>> import tflearn 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/chatbot/lib/python3.7/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/root/chatbot/lib/python3.7/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/root/chatbot/lib/python3.7/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'
`

**Comment by macedonga** [comment]
Having the same issue here... It is because tflearn doesn't support Tensorflow 2.0. I don't think it will be supported anytime soon, since this project is dead...

**Comment by aymericdamien** [comment]
Hi, FYI the latest version of TFLearn supports TF 2.0+
