### ISSUE TITLE
TimeDistributed equivalent in tflearn?

### ISSUE THREAD

**Issue by c0nn3r** [tflearn/tflearn#115]
Hello, 

I have been trying to apply a Highway neural network over timesteps in tflearn. It would be really useful if a way existed (like Keras) of wrapping a layer to make it apply over timesteps. Does this currently exist? Thank you.

**Comment by aymericdamien** [comment]
TFLearn doesn't have such wrapper yet, but it would be great to add it! It shouldn't be very hard to implement it.
In your case, you can use tensorflow to reshape your tensor and apply a fully_connected layer, should be something like:
```
x = ...\
x_shape = x.get_shape.as_list()
x = tf.reshape(x, [-1, x_shape[-1]])
x = tflearn.fully_connected(x, 64, activation='linear')
x = tf.reshape(x, x_shape[1], 64)
x = tflearn.activation(x, 'relu')
```

**Comment by VanushVaswani** [comment]
@aymericdamien Does this mean we can't have an output like [batch, steps, out_dim] ?

**Comment by aymericdamien** [comment]
@VanushVaswani I added a time_distributed layer (http://tflearn.org/layers/core/#time-distributed), this should do what you need.

**Comment by elmar-haussmann** [comment]
This doesn't seem to work when applied after an LSTM with return_seq=True.
For example:

```
embeddings = tfg
lstm = tflearn.lstm(embeddings, 32, return_seq=True)
dense = tflearn.time_distributed(lstm, tflearn.fully_connected, [num_classes])
```

```
  File "/Users/elmar/ddat-prototype/venv/lib/python3.5/site-packages/tflearn/layers/core.py", line 621, in time_distributed
    timestep = input_shape[1]
IndexError: tuple index out of range
```

Related to that: why does lstm return a list of tensors with `return_seq=True` (one element per timestep). According to documentation it should be a 3D-Tensor of shape [samples, timesteps, input dim].
I worked around it by packing the list and applying the time distribution myself.

**Comment by VanushVaswani** [comment]
@elmar-haussmann Can you post that as a gist?

**Comment by elmar-haussmann** [comment]
Reproducing the error is really straight forward, just take lstm.py from the examples and try to insert time_distributed.

**Comment by aymericdamien** [comment]
@elmar-haussmann @VanushVaswani Yes, this should fix it, just use tf.pack(...) to change your python list into a Tensor.

**Comment by VanushVaswani** [comment]
I'm trying to do the following where X shape = (1500, 4, 400) and y shape = (500, 4, 1) (so classification at each timestep where t = 4).

```
net = tflearn.input_data([None, X_train.shape[1], X_train.shape[2]])            
net = tflearn.lstm(net, 128, dropout=0.1, return_seq=True)                      
net = tflearn.time_distributed(net, tflearn.fully_connected, [1])               
net = tflearn.softmax(net)                                                      
net = tflearn.regression(net, optimizer='adam', learning_rate=0.001, loss='binary_crossentropy')

I get the below error:
```
Traceback (most recent call last):
  File "tftest.py", line 21, in <module>
    model.fit(X_train, y_train, validation_set=(X_test, y_test), show_metric=True, batch_size=32)
  File "build/bdist.linux-x86_64/egg/tflearn/models/dnn.py", line 191, in fit
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py", line 284, in fit
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py", line 701, in _train
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 625, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 4, 1) for Tensor u'TargetsData/Y:0', which has shape '(?, 4)'
```

Is this case supported?


                                                                                
model = tflearn.DNN(net, tensorboard_verbose=3)                                 
model.fit(X_train, y_train, validation_set=(X_test, y_test), show_metric=True, batch_size=32)
```

**Comment by aymericdamien** [comment]
You can use your own placeholder:
```
Yp = tf.placeholder(shape=[None, 4, 1])
net = tflearn.regression(net, optimizer='adam', learning_rate=0.001, loss='binary_crossentropy', placeholder=Yp)
```
But not that the placeholder shape is generated based on the input tensor (which means that your softmax layer returns [None, 4] shape tensor, so you might reshape it to [None, 4, 1] to make it works)

**Comment by VanushVaswani** [comment]
Thanks. I tried the following, but still getting an error.

```
yp = tf.placeholder(shape=[None, 4, 1], dtype=tf.float32)                       
                                                                                
net = tflearn.input_data([None, X_train.shape[1], X_train.shape[2]])            
net = tflearn.lstm(net, 128, dropout=0.1, return_seq=True)                      
net = tflearn.lstm(net, 128, dropout=0.1, return_seq=True)                      
net = tflearn.time_distributed(net, tflearn.fully_connected, [1])               
net = tflearn.softmax(net)                                                      
net = tflearn.reshape(net, [None, 4, 1])                                        
net = tflearn.regression(net, optimizer='adam', learning_rate=0.001, loss='binary_crossentropy', placeholder=yp)
model = tflearn.DNN(net, tensorboard_verbose=3)                                 
model.fit(X_train, y_train, validation_set=(X_test, y_test), show_metric=True, batch_size=32)
```

```
Traceback (most recent call last):
  File "tftest.py", line 21, in <module>
    net = tflearn.reshape(net, [None, 4, 1])
  File "build/bdist.linux-x86_64/egg/tflearn/layers/core.py", line 280, in reshape
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1383, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 455, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got None of type '_Message' instead.
```

**Comment by aymericdamien** [comment]
you have to use:
```
net = tflearn.reshape(net, [-1, 4, 1])    
```

**Comment by hackitdown** [comment]
`#!/usr/bin/env python3.6

import random as rnd
import pandas as pd
import numpy  as np

import tflearn
import tensorflow as tf

Num = 1
xLen = 20
yLen = 4

dataSetLen = 5000

X = np.array([[[rnd.uniform(-1.0, 1.0) for x in range(Num)] for x in range(xLen)] for x in range(dataSetLen)])
Y = np.array([[[rnd.uniform(-1.0, 1.0) for x in range(Num)] for x in range(yLen)] for x in range(dataSetLen)])

print("X shape:", X.shape)
print("Y shape:", Y.shape)

yp = tf.placeholder(shape=[None, Y.shape[1], Y.shape[2]], dtype=tf.float32)

net = tflearn.input_data([None, X.shape[1], X.shape[2]])
net = tflearn.lstm(net, 128, dropout=.1, return_seq=True)
net = tflearn.lstm(net, 128, dropout=.1, return_seq=True)
net = tflearn.time_distributed(net, tflearn.fully_connected, [128, xLen, Num])
net = tflearn.softmax(net)
net = tflearn.reshape(net, [-1, Y.shape[1], Y.shape[2]])
net = tflearn.regression(net, optimizer='adam', learning_rate=.001, loss='binary_crossentropy', placeholder=yp)

model = tflearn.DNN(net, tensorboard_verbose=3)
model.fit(X, Y, validation_set=.1, show_metric=True, batch_size=32)
`
(tf-v1.0.1-gpu) local@tsp02:~/Work/Work/Models> ./TFRegression.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
X shape: (5000, 20, 1)
Y shape: (5000, 4, 1)
Traceback (most recent call last):
  File "./TFRegression.py", line 27, in <module>
    net = tflearn.time_distributed(net, tflearn.fully_connected, [128, xLen, Num])
  File "/home/local/Work/VirtualEnviroment/tf-v1.0.1-gpu/lib/python3.6/site-packages/tflearn/layers/core.py", line 642, in time_distributed
    x = [fn(x[i], *args) for i in range(timestep)]
  File "/home/local/Work/VirtualEnviroment/tf-v1.0.1-gpu/lib/python3.6/site-packages/tflearn/layers/core.py", line 642, in <listcomp>
    x = [fn(x[i], *args) for i in range(timestep)]
  File "/home/local/Work/VirtualEnviroment/tf-v1.0.1-gpu/lib/python3.6/site-packages/tflearn/layers/core.py", line 181, in fully_connected
    raise ValueError("Invalid Activation.")
ValueError: Invalid Activation.

**Comment by hackitdown** [comment]
Google gives nothing usefull...

**Comment by chrisplyn** [comment]
@VanushVaswani 
Hi I was trying to follow your code but it seems this line 
'tflearn.time_distributed(net, tflearn.fully_connected, [1])'
gives me error 
'Expected int32,  of type 'map' instead'
do you know what's happening?

**Comment by kkonevets** [comment]
@aymericdamien is it possible to replace your 'for' loop in time_distributed() with tf.group?
