### ISSUE TITLE
tflearn

### ISSUE THREAD

**Issue by WillingDil** [tflearn/tflearn#1181]
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Scipy not supported!
Building Encoder
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tflearn-0.5.0-py3.7.egg/tflearn/initializations.py:110: calling UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:549: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Tensor("ge/Relu:0", shape=(?, ?, 64), dtype=float32)
Tensor("ge/Relu_1:0", shape=(?, ?, 128), dtype=float32)
Tensor("ge/Relu_2:0", shape=(?, ?, 128), dtype=float32)
Tensor("ge/Relu_3:0", shape=(?, ?, 256), dtype=float32)
Tensor("ge/Relu_4:0", shape=(?, ?, 128), dtype=float32)
Tensor("ge/Max:0", shape=(?, 128), dtype=float32)
Building Decoder
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tflearn-0.5.0-py3.7.egg/tflearn/initializations.py", line 198, in xavier
ModuleNotFoundError: No module named 'tensorflow.contrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pc_sampling_rec.py", line 196, in <module>
    train(args)
  File "pc_sampling_rec.py", line 75, in train
    outpj=decoder(word,layer_sizes=dec_args['layer_sizes'],b_norm=dec_args['b_norm'],b_norm_decay=1.0,b_norm_finish=dec_args['b_norm_finish'],b_norm_decay_finish=1.0,verbose=dec_args['verbose'])
  File "/media/ubuntu/0f083fd5-b631-4342-9812-7e262eaff979/ZZY/2024对抗攻击+数据蒸馏/PCDNet/encoders_decoders.py", line 187, in decoder_with_fc_only
    layer = fully_connected(layer, layer_sizes[i], activation='linear', weights_init='xavier', name=name, regularizer=regularizer, weight_decay=weight_decay, reuse=reuse, scope=scope_i)
  File "/home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tflearn-0.5.0-py3.7.egg/tflearn/layers/core.py", line 152, in fully_connected
  File "/home/ubuntu/anaconda3/envs/zzy_data/lib/python3.7/site-packages/tflearn-0.5.0-py3.7.egg/tflearn/initializations.py", line 201, in xavier
NotImplementedError: 'xavier_initializer' not supported, please update TensorFlow.

**Comment by WillingDil** [comment]
I get this error in my enviro: tflearn=0.5.0 tensorflow=2.6.0. what can I do to solve this problem,any answers is appreciate
