### ISSUE TITLE
Crashing galore with convolutional autoencoder

### ISSUE THREAD

**Issue by TylerBalsam** [tflearn/tflearn#131]
I'm trying to create a convolutional autoencoder (which, when stable, will hopefully be pegged for submission to /examples/).

However, I'm always getting NaN between my highest conv_2d layer and lowest conv_2d_transpose layer. Sometimes it's gradients, though the flavor of the last dozen crashes or so is the good ole ReLU. I've tried quite a few things (learning rate [currently .001], different bias/weight init patterns, a variety of activation functions, differing layer depths, batch sizes 1-8, etc.). However, it doesn't seem to even make it to 100 iterations. The data's just imagenet in the people class, and my loss is reasonable (between .02 and .006--the loss for the particular problem I'm working on is lower than standard.)

Maybe it's poor network design, but I'm not fully convinced yet that that's the case. Regardless of my configuration, the lowest conv_2d_transpose layer always is the one that triggers the NaN. Once or twice it was the second lowest, but that was 2. when I cranked up the learning rates very high to watch the gradients for distinct patterns and 2. when my network was ~30 layers deep. I've had to wrangle the conv_2d_transpose layer a bit to get it to cooperate fully, and plan on trying to expand that functionality within tflearn once I get some free cycles. In brief, here's my net design:

network = input_data(shape=[None, 224, 224, 3])
network = conv_2d(network, 64, 3, activation='leaky_relu', weights_init='truncated_normal', bias='truncated_normal')
network = conv_2d(network, 64, 3, activation='leaky_relu', weights_init='truncated_normal', bias='truncated_normal')
network = conv_2d_transpose(network, 32, [3, 3, 32, 64], [1, 1, 1, 1], [112, 112, 32], activation='leaky_relu', weights_init='truncated_normal', bias='truncated_normal')
network = conv_2d_transpose(network, 16, [3, 3, 16, 32], [1, 2, 2, 1], [224, 224, 16], activation='leaky_relu', weights_init='truncated_normal', bias='truncated_normal')
network = conv_2d_transpose(network, 2, [3, 3, 2, 16], [1, 1, 1, 1], [224, 224, 2], activation='sigmoid', weights_init='truncated_normal', bias='truncated_normal')

Dump below: 

Traceback (most recent call last):
  File "train.py", line 258, in <module>
    snapshot_epoch=False, run_id='colorize_15')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 185, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 263, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 677, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Nan in summary histogram for: AdaGrad/HistogramSummary_3
	 [[Node: AdaGrad/HistogramSummary_3 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](AdaGrad/HistogramSummary_3/tag, Conv2DTranspose/Relu)]]
Caused by op u'AdaGrad/HistogramSummary_3', defined at:
  File "train.py", line 254, in <module>
    max_checkpoints=1, tensorboard_verbose=3)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 111, in __init__
    clip_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 571, in initialize_training_ops
    self.create_summaries(tensorboard_verbose)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 751, in create_summaries
    summarize_activations(activations, summ_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/summarizer.py", line 50, in summarize_activations
    summaries.add_activations_summary(activations, "", "", summary_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 89, in add_activations_summary
    get_summary("histogram", summ_name, ao, collection_key)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 44, in get_summary
    summ = tf.histogram_summary(tag, value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

Thanks for any and all help offered for the resolution of this.

**Comment by TylerBalsam** [comment]
Update: Middle of the night revelation -- it may be the ReLU activation on the uppermost conv_2d to deconv_2d layer. Trying tanh for spectrum, looking pretty stable so far. Will update & close for reference if this is the issue.

**Comment by aymericdamien** [comment]
Hi, That is indeed an interesting example to add.You can also add some downsampling (`max_pool_2d` and `upsample2d`) into the convolution network, I think it will be useful for many other users. Also, I think you can simply use `conv2d` layer in your decoder for the deconvolution instead of the transpose of conv2d.

**Comment by TylerBalsam** [comment]
Sure thing. This was only a diagnostic network to single out the causes of crashing for an experimental pet project--the full network will be a little more standardized. I'm currently without a Tensorflow compatible GPU (waiting on the GTX 1070).

I'll be sure to swap in max_pool_2d and upsample2d in for reference in my submitted network. I know I've needed pretrained layers on imagenet in the past to save training time, which is something tflearn currently lacks. It'll be good to get this included to save others the legwork.

**Comment by TylerBalsam** [comment]
Ok, so a little over a dozen combinations later, I'm still crashing after a few iterations. Oftentimes it won't even get to the first iteration. Here's the updated structure.

Learning Rate: .001, Adagrad
Loss: Modified Mean Square

img_prep = ImagePreprocessing()
img_prep.add_featurewise_zero_center()
network = input_data(shape=[None, 224, 224, 3], data_preprocessing=img_prep)
network = conv_2d(network, 64, 3, activation='relu')
network = conv_2d(network, 64, 3, activation='relu')
network = max_pool_2d(network, 2, strides=2)
network = conv_2d(network, 128, 3, activation='relu')
network = conv_2d(network, 128, 3, activation='relu')
network = max_pool_2d(network, 2, strides=2)
pc_network = upsample_2d(network, 2)
pc_network = conv_2d(pc_network, 64, 3, activation='relu')
pc_network = conv_2d(pc_network, 64, 3, activation='relu')
pc_network = upsample_2d(pc_network, 2)
pc_network = conv_2d(pc_network, 32, 3, activation='relu')
pc_network = conv_2d(pc_network, 32, 3, activation='relu')
pc_network = conv_2d(pc_network, 2, 3, activation='relu')
pc_network = conv_2d(pc_network, 2, 3, activation='sigmoid')


And relevant dumps:

||||||DUMP 1|||||


Traceback (most recent call last):
  File "train.py", line 299, in <module>
    snapshot_epoch=False, run_id='colorize_20')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 188, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 277, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 684, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Nan in summary histogram for: AdaGrad/HistogramSummary_19
	 [[Node: AdaGrad/HistogramSummary_19 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](AdaGrad/HistogramSummary_19/tag, AdaGrad/clip_by_global_norm/AdaGrad/clip_by_global_norm/_19)]]
Caused by op u'AdaGrad/HistogramSummary_19', defined at:
  File "train.py", line 295, in <module>
    max_checkpoints=1, tensorboard_verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 111, in __init__
    clip_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 578, in initialize_training_ops
    self.create_summaries(tensorboard_verbose)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 764, in create_summaries
    summarize_gradients(self.grad, summ_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/summarizer.py", line 67, in summarize_gradients
    summaries.add_gradients_summary(grads, "", "", summary_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 132, in add_gradients_summary
    collection_key))
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 44, in get_summary
    summ = tf.histogram_summary(tag, value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

|||||DUMP 2|||||
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    snapshot_epoch=False, run_id='colorize_20')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 188, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 277, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 684, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Nan in summary histogram for: Adam/HistogramSummary_1
	 [[Node: Adam/HistogramSummary_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](Adam/HistogramSummary_1/tag, Adam/clip_by_global_norm/Adam/clip_by_global_norm/_1)]]
Caused by op u'Adam/HistogramSummary_1', defined at:
  File "train.py", line 295, in <module>
    max_checkpoints=1, tensorboard_verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 111, in __init__
    clip_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 578, in initialize_training_ops
    self.create_summaries(tensorboard_verbose)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 764, in create_summaries
    summarize_gradients(self.grad, summ_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/summarizer.py", line 67, in summarize_gradients
    summaries.add_gradients_summary(grads, "", "", summary_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 132, in add_gradients_summary
    collection_key))
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 44, in get_summary
    summ = tf.histogram_summary(tag, value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()


|||||DUMP 3|||||
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    snapshot_epoch=False, run_id='colorize_20')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 185, in fit
    run_id=run_id)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 263, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 668, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Nan in summary histogram for: AdaGrad/HistogramSummary_51
	 [[Node: AdaGrad/HistogramSummary_51 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](AdaGrad/HistogramSummary_51/tag, AdaGrad/gradients/Conv2D_9/BiasAdd_grad/BiasAddGrad)]]
Caused by op u'AdaGrad/HistogramSummary_51', defined at:
  File "train.py", line 295, in <module>
    max_checkpoints=1, tensorboard_verbose=3)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 111, in __init__
    clip_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 562, in initialize_training_ops
    self.create_summaries(tensorboard_verbose)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 748, in create_summaries
    summarize_gradients(self.grad, summ_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/summarizer.py", line 67, in summarize_gradients
    summaries.add_gradients_summary(grads, "", "", summary_collection)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 132, in add_gradients_summary
    collection_key))
  File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 44, in get_summary
    summ = tf.histogram_summary(tag, value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()


This certainly is the weirdest one I've run into. Turning tensorboard verbose=3 usually makes it crash at activations, tensorboard verbose=1 makes it crash at clip_by_global_norm. NaNs all around.

**Comment by aymericdamien** [comment]
Yes, it crashes because you have some NaNs value. It maybe due to the network architecture. For an example, we could use MNIST dataset, so anyone could run it.
It would indeed definitely be useful to have some pre-trained models, we are planning to add some sooner or later.

**Comment by TylerBalsam** [comment]
Did some deep digging, somehow the line of tensors in my loss function was messing up the gradient. I rewrote it and it (seems to) have fixed the issue. 

MNIST would be a great idea. Wouldn't need a deep network for that either. I can set that one up, no trouble.

**Comment by aymericdamien** [comment]
great, thanks :)

**Comment by sabersf** [comment]
I used AdaGrad instead of the Adam optimizer and get "InvalidArgumentError: Nan in summary histogram for: AdaGrad/HistogramSummary_19" error on my dataset. It works fine for the MNIST data set, However, I'm not sure why AdaGrad is not working properly on other data sets.

**Comment by TylerBalsam** [comment]
What's your GPU, cuda, cudnn, and tensorflow versions and have you made any
modifications to your network structure?

**Comment by sabersf** [comment]
I'm not running the code on GPU since I'm running the code on mac. TF version is 0.9.0
I just changed the number of neurons in each layer and added names to them:

`# Building the encoder
encoder = tflearn.input_data(shape=[None, len(X[0])])
INPUT = encoder
encoder = tflearn.fully_connected(encoder, layer1_neurons, name = "en_1")
encoder = tflearn.fully_connected(encoder, layer2_neurons, name = "en_2")
encoder = tflearn.fully_connected(encoder, layer3_neurons, name = "en_3")
HIDDEN_STATE = encoder
# Building the decoder
decoder = tflearn.fully_connected(encoder, layer2_neurons, name = "de_1")
decoder = tflearn.fully_connected(decoder, layer1_neurons, name = "de_2")
decoder = tflearn.fully_connected(decoder, len(X[0]), name = "de_3")
OUTPUT = decoder `

**Comment by sabersf** [comment]
I managed to fix the problem, I changed the loss function to a more appropriate one in my data set and I'm not seeing any error and it's working fine!

**Comment by TylerBalsam** [comment]
Great! For reference for anyone with GPU issues like this, for those on the
new 10 series Nvidia architecture experiencing errors should build
tensorflow on master from source with RC 8.0, cudnn 5.1 for RC 8, and
building Basil from source.
