### ISSUE TITLE
_rnn_cell has no attribute '_is_sequence' error when running rnn_pixels.py on tensorflow 0.9 version

### ISSUE THREAD

**Issue by CharlesShang** [tflearn/tflearn#185]
```
Traceback (most recent call last):
  File "/home/shang/pycharm-community-2016.1.2/helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/shang/pycharm-community-2016.1.2/helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shang/Work/tflearn/examples/images/rnn_pixels.py", line 19, in <module>
    net = tflearn.lstm(net, 128, return_seq=True)
  File "build/bdist.linux-x86_64/egg/tflearn/layers/recurrent.py", line 216, in lstm
  File "build/bdist.linux-x86_64/egg/tflearn/layers/recurrent.py", line 65, in _rnn_template
  File "/home/shang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 189, in rnn
    (output, state) = call_cell()
  File "/home/shang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 176, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "build/bdist.linux-x86_64/egg/tflearn/layers/recurrent.py", line 505, in __call__
  File "build/bdist.linux-x86_64/egg/tflearn/layers/recurrent.py", line 615, in _linear
AttributeError: 'module' object has no attribute '_is_sequence'
```
I think the tf 0.9 version API has been changed, any temp solutions?

**Comment by aymericdamien** [comment]
Hi correct, in master version they changed it to 'is_sequence', I will push an update soon.

**Comment by aymericdamien** [comment]
It is fixed!
