### ISSUE TITLE
Freezing as TensorFlow graph

### ISSUE THREAD

**Issue by chrisruk** [tflearn/tflearn#217]
Hi, 

I'm just wondering if it's possible to freeze a graph as a TensorFlow model, using 
TensorFlow's FreezeGraph functionality, for instance:

```
def save_graph(sess,output_path,checkpoint,checkpoint_state_name,input_graph_name,output_graph_name):

    checkpoint_prefix = os.path.join(output_path,checkpoint)
    saver = tf.train.Saver(tf.all_variables())
    saver.save(sess, checkpoint_prefix, global_step=0,latest_filename=checkpoint_state_name)
    tf.train.write_graph(sess.graph.as_graph_def(),output_path,
                           input_graph_name)

    # We save out the graph to disk, and then call the const conversion
    # routine.
    input_graph_path = os.path.join(output_path, input_graph_name)
    input_saver_def_path = ""
    input_binary = False
    input_checkpoint_path = checkpoint_prefix + "-0"
    output_node_names = "out"
    restore_op_name = "save3/restore_all"
    filename_tensor_name = "save3/Const:0"
    output_graph_path = os.path.join(output_path, output_graph_name)
    clear_devices = False

    freezegraph.freeze_graph(input_graph_path, input_saver_def_path,
                              input_binary, input_checkpoint_path,
                              output_node_names, restore_op_name,
                              filename_tensor_name, output_graph_path,clear_devices, "")
```

When I try to use this I get:

```
E tensorflow/core/client/tensor_c_api.cc:485] Attempting to use uninitialized value Adam/conv1/b/Adam_1
	 [[Node: Adam/conv1/b/Adam_1/_15 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_14_Adam/conv1/b/Adam_1", _device="/job:localhost/replica:0/task:0/gpu:0"](Adam/conv1/b/Adam_1)]]
	 [[Node: conv2/W/_50 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_31_conv2/W", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](^_recv_save_3/Const_0, ^save_3/save/tensor_names, ^save_3/save/shapes_and_slices)]]
Traceback (most recent call last):
  File "./train_cnn.py", line 103, in <module>
    save_graph(sess,"/tmp/","saved_checkpoint","checkpoint_state","input_graph.pb","output_graph.pb")
  File "/home/chris/Repositories/cnn/tensor.py", line 12, in save_graph
    saver.save(sess, checkpoint_prefix, global_step=0,latest_filename=checkpoint_state_name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1060, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value Adam/conv1/b/Adam_1
	 [[Node: Adam/conv1/b/Adam_1/_15 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_14_Adam/conv1/b/Adam_1", _device="/job:localhost/replica:0/task:0/gpu:0"](Adam/conv1/b/Adam_1)]]
	 [[Node: conv2/W/_50 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_31_conv2/W", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](^_recv_save_3/Const_0, ^save_3/save/tensor_names, ^save_3/save/shapes_and_slices)]]
```

I'm thinking this is likely due to TFlearn, providing its own functionality, which can't be saved through freeze graph?

Thanks a lot!

Chris

**Comment by aymericdamien** [comment]
Your error seems to occur when you are trying to save the model, and warns that your have some uninitialized variables. Did you try to save the graph before initializing the variables (with tf.initialize_all_variables), maybe that is the issue here.

**Comment by chrisruk** [comment]
Thanks a lot, that definitely seems to have helped, however I still get this:

```
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:02:00.0)
Traceback (most recent call last):
  File "./train_cnn.py", line 110, in <module>
    save_graph(sess,"/tmp/","saved_checkpoint","checkpoint_state","input_graph.pb","output_graph.pb")
  File "/home/chris/Repositories/cnn/tensor.py", line 31, in save_graph
    filename_tensor_name, output_graph_path,clear_devices, "")
  File "/home/chris/Repositories/cnn/freezegraph.py", line 121, in freeze_graph
    sess, input_graph_def, output_node_names.split(","))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/graph_util.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/graph_util.py", line 156, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: out is not in graph
```

I created the node 'out' as follows:
```
...
network = fully_connected(network, len(mod), activation='softmax',name="out")
network = regression(network, optimizer='adam',loss='categorical_crossentropy', learning_rate=0.001)
model = tflearn.DNN(network, tensorboard_verbose=0)
for v in sess.graph.get_operations():
    print(v.name)
model.fit(X, Y, n_epoch=1, shuffle=True,show_metric=True, batch_size=1024, run_id='radio_cnn')
init_op = tf.initialize_all_variables()
sess.run(init_op)
save_graph(sess,"/tmp/","saved_checkpoint","checkpoint_state","input_graph.pb","output_graph.pb")
```

I've tried placing the init_op & sess.run before the .fit call too.

My code prints out TensorFlow operations, so I can see 'out' does seem to exist, so I'm rather confused.'

Any pointers would be great!

Cheers

```
out/W
out/W/Initializer/truncated_normal/shape
out/W/Initializer/truncated_normal/mean
out/W/Initializer/truncated_normal/stddev
out/W/Initializer/truncated_normal/TruncatedNormal
out/W/Initializer/truncated_normal/mul
out/W/Initializer/truncated_normal
out/W/Assign
out/W/read
out/b
out/b/Initializer/Const
out/b/Assign
out/b/read
out/MatMul
out/BiasAdd
out/Softmax
Adam/gradients/out/Softmax_grad/mul
Adam/gradients/out/Softmax_grad/Sum/reduction_indices
Adam/gradients/out/Softmax_grad/Sum
Adam/gradients/out/Softmax_grad/Reshape/shape
Adam/gradients/out/Softmax_grad/Reshape
Adam/gradients/out/Softmax_grad/sub
Adam/gradients/out/Softmax_grad/mul_1
Adam/gradients/out/BiasAdd_grad/BiasAddGrad
Adam/gradients/out/MatMul_grad/MatMul
Adam/gradients/out/MatMul_grad/MatMul_1
Adam/out/W/Adam
Adam/out/W/Adam/Assign
Adam/out/W/Adam/read
Adam/out/W/Adam_1
Adam/out/W/Adam_1/Assign
Adam/out/W/Adam_1/read
Adam/out/b/Adam
Adam/out/b/Adam/Assign
Adam/out/b/Adam/read
Adam/out/b/Adam_1
Adam/out/b/Adam_1/Assign
Adam/out/b/Adam_1/read
Adam/apply_grad_op_0/update_out/W/ApplyAdam
Adam/apply_grad_op_0/update_out/b/ApplyAdam
```

**Comment by chrisruk** [comment]
My mentor managed to fix the problem: 

In the graph save routine, I need to use "out/Softmax" rather than just out.

And to access tensors when loading:

n_input = sess.graph.get_tensor_by_name("inp/X:0")
output = sess.graph.get_tensor_by_name("out/Softmax:0")

So it works now! 

Thanks a lot for your wrapper

**Comment by chrisruk** [comment]
In case anyone wants to do this, I found it's also necessary to
pass the session into the DNN:

```
    m = tflearn.DNN(regressor,session=sess)
```

Otherwise, the model you freeze will be untrained.

**Comment by aymericdamien** [comment]
Great! Good to know.

**Comment by iMatrix67** [comment]
Could I import freezegraph directly? Where is the freezegraph packets located in?

**Comment by stellasoft-will** [comment]
@chrisruk just a quick question how are you able to pass the session to the DNN as im currently accessing the session on the model as an attribute at the moment so only have access to it after the DNN function any help would be greatly appreciated
