### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jdsutton** [tflearn/tflearn#26]
I've followed the instructions in the installation guide, but no matter what I do, when I run `>>>import tflearn` I get:
```
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

Here is the full error for reference:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tflearn/__init__.py", line 8, in <module>
    from . import models
  File "tflearn/models/__init__.py", line 2, in <module>
    from .dnn import DNN
  File "tflearn/models/dnn.py", line 5, in <module>
    from ..helpers.trainer import Trainer
  File "tflearn/helpers/__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "tflearn/helpers/evaluator.py", line 6, in <module>
    from ..utils import to_list
  File "tflearn/utils.py", line 7, in <module>
    import h5py
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/tmp/easy_install-w7IxB0/h5py-2.6.0/h5py/_conv.c:7357)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/tmp/easy_install-w7IxB0/h5py-2.6.0/h5py/h5t.c:20344)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

**Comment by aymericdamien** [comment]
It seems there is a conflict between h5py and numpy. It might be that h5py have been compiled with another version of numpy? Can you try to reinstall h5py and numpy? I think this should fix the issue.

I found this related issue:
http://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312

**Comment by jdsutton** [comment]
Resolved, thanks!
