### ISSUE TITLE
Error when doing multi-class classification

### ISSUE THREAD

**Issue by carlobailey** [tflearn/tflearn#260]
Hello,

Thanks for providing this excellent framework!

I am running into issues when trying to do multi-class classification (with 7 labels). 
Here is my code (I am using Python3):

```python
import numpy as np
import tflearn
from tflearn.data_utils import to_categorical, pad_sequences
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.embedding_ops import embedding
from tflearn.layers.recurrent import bidirectional_rnn, BasicLSTMCell
from tflearn.layers.estimator import regression
import data_helpers
from tensorflow.contrib import learn


# Load data
x_text, y = data_helpers.load_data_and_labels()


# Data preprocessing
# Sequence padding & Build vocabulary
max_document_length = max([len(x.split(" ")) for x in x_text])
vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length)
vocab_size = len(vocab_processor.vocabulary_)
trainX = np.array(list(vocab_processor.fit_transform(x_text)))

# Converting labels to binary vectors
trainY = to_categorical(y, nb_classes=7)

# Split data
trainX, testX = trainX[1001:], trainX[:1000]
trainY, testY = trainY[1001:], trainY[:1000]


# Network building
net = input_data(shape=[None, max_document_length])
net = embedding(net, input_dim=vocab_size, output_dim=128)
net = bidirectional_rnn(net, BasicLSTMCell(128), BasicLSTMCell(128))
net = dropout(net, 0.5)
net = fully_connected(net, 7, activation='softmax')
net = regression(net, optimizer='adam', loss='categorical_crossentropy')

# Training
model = tflearn.DNN(net, clip_gradients=0., tensorboard_verbose=7)
model.fit(trainX, trainY, validation_set=0.1, show_metric=True)
```

I get the following error:
```
E tensorflow/core/client/tensor_c_api.cc:485] indices[0,0] = 14 is not in [0, 1)
	 [[Node: Embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Embedding/W/read, Embedding/Cast)]]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 730, in _do_call
    return fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in _run_fn
    status, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: indices[0,0] = 14 is not in [0, 1)
	 [[Node: Embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Embedding/W/read, Embedding/Cast)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cbailey/Documents/tflearn/examples/nlp/my_bidirectional_lstm.py", line 45, in <module>
    model.fit(trainX, trainY, validation_set=0.1, show_metric=True)#, batch_size=64)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tflearn/models/dnn.py", line 188, in fit
    run_id=run_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 277, in fit
    show_metric)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 684, in _train
    feed_batch)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: indices[0,0] = 14 is not in [0, 1)
	 [[Node: Embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Embedding/W/read, Embedding/Cast)]]
Caused by op 'Embedding/embedding_lookup', defined at:
  File "/Users/cbailey/Documents/tflearn/examples/nlp/my_bidirectional_lstm.py", line 37, in <module>
    net = embedding(net, input_dim=vocab_size, output_dim=128)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tflearn/layers/embedding_ops.py", line 53, in embedding
    inference = tf.nn.embedding_lookup(W, inference)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/embedding_ops.py", line 86, in embedding_lookup
    validate_indices=validate_indices)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 980, in gather
    validate_indices=validate_indices, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()
```

Any help would be much appreciated. Thanks!

**Comment by aymericdamien** [comment]
This error is due to the fact that the index '14' is not inside your embedding matrix. So it seems that you have a wrong 'vocab_size' (maybe it should be `net = embedding(net, input_dim=vocab_size+1, output_dim=128)`).

**Comment by carlobailey** [comment]
Awesome! I should have picked that up.

Everything's fine now

**Comment by sifatron** [comment]
```
InvalidArgumentError (see above for traceback): indices[0,2] = -1 is not in [0, 15663)
	 [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]
```
I am having this error. I am using Keras with Tensorflow backend. 

`rint('Building Model')
model7 = Sequential()

model7.add(Embedding(len(train_vecs_w2v), EMBEDDING_DIM, input_length=max_length, dtype='float32', trainable=True, embeddings_initializer='uniform', embeddings_regularizer=None, activity_regularizer=None, embeddings_constraint=None))
print(model7.output_shape)
# model7.add(Convolution1D(128, 3, strides=1, activation='relu', use_bias=False, input_shape=(max_length, nb_classes), border_mode='same'))
model7.add(Convolution1D(filters =128, kernel_size = 3, strides=1, activation='relu', use_bias=False, border_mode='same')) 
print(model7.output_shape)
model7.add(MaxPooling1D(pool_size = 3))`

my input x_train shape is (15663,400) and y_train shape is (15663, 3). 3 Binary class labels.

**Comment by kasptom** [comment]
@sifatron I am getting the similar issue. My input vectors contain floats, including negative values. I've noticed that if I get rid of the negative values (e.g. by finding the minimum value amongst all of the input vectors and adding its absolute value to all of the vectors elements) the error is gone.

**Comment by sifatron** [comment]
@kasptom the issue went away when I changed from tensorflow backend to theano backend. In my code, btw I used scikit-learn scale on my input vectors.

**Comment by radiodee1** [comment]
Hi, I hope I'm in the right place. I get the following error.

```
InvalidArgumentError (see above for traceback): indices[0,205] = -1 is not in [0, 2005)
	 [[Node: embedding_2_2/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_2_1/embeddings/read, embedding_2_2/Cast)]]
```

I have some embedding weights that are set using the following code:

`value = np.random.uniform(size=(embed_size,))
`
I use Tensorflow as a backend. The problem is I don't think there are any negative values in the weights... not that I put there anyway. Does anybody have any advice?

**Comment by seeiespi** [comment]
@radiodee1 I don't know if this is your case but I had a model where I was getting this error but none of the above solutions  were helping. My issue ended up being that I have a multi-input model and was feeding the data in the wrong order.

**Comment by MizAmy** [comment]
use this one. it helps me
net = input_data(shape=[None, max_document_length])
net = embedding(input_dim=**vocab_size+1**, output_dim=128)(net)

**Comment by marc88** [comment]
I get the following error too after running an embedding layer as;

`Embedding(23624, 50, input_length=5, trainable=False)`

> InvalidArgumentError (see above for traceback): **indices[6,4]** = 23624 is not in [0, 23624)
> 	 [[Node: embedding_1/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_1/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]

Each datapoint here is a number(index). Upon checking indices[6,4] I found the following

```
print(ar_train_data[6,4])
5088
```
ar_train_data is an array of shape (162896, 5) where each value is  between [0, 23624).
The training stops towards the end of the first epoch with the error above.
am amazed! 5088 is no where out of range for [0, 23624).  Can anyone suggest what could be the issue here?
Please suggest if additional code snippets are required for clarity.

Keras version - 2.2.4
tensorflow version: 1.5.0

Regards

**Comment by arnoldazeem** [comment]
@marc88 please did you solve your problem?. I have the same issue.

**Comment by marc88** [comment]
Yes!
0, 23624 was the range earlier. I had to increase the range to solve this.

Embedding(23625, 50, input_length=5, trainable=False)
