### ISSUE TITLE
error when running residual mnist net example

### ISSUE THREAD

**Issue by agiovann** [tflearn/tflearn#276]
--
Traceback (most recent call last):

  File "<ipython-input-1-bcc363f6a19b>", line 35, in <module>
    show_metric=True, batch_size=256, run_id='resnet_mnist')

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/models/dnn.py", line 188, in fit
    run_id=run_id)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 277, in fit
    show_metric)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 684, in _train
    feed_batch)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)

  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: stride must be less than or equal to kernel size
	 [[Node: Momentum/gradients/ResidualBottleneck_3/AvgPool2D/AvgPool_grad/AvgPoolGrad = AvgPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](Momentum/gradients/ResidualBottleneck_3/AvgPool2D/AvgPool_grad/Shape, Momentum/gradients/ResidualBottleneck_3/Pad_grad/Slice_1)]]
Caused by op u'Momentum/gradients/ResidualBottleneck_3/AvgPool2D/AvgPool_grad/AvgPoolGrad', defined at:
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 205, in <module>
    __ipythonkernel__.start()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tornado/ioloop.py", line 827, in start
    self._run_callback(callback)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 258, in enter_eventloop
    self.eventloop(self)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/eventloops.py", line 75, in loop_qt4
    start_event_loop_qt4(kernel.app)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/IPython/lib/guisupport.py", line 135, in start_event_loop_qt4
    app.exec_()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/eventloops.py", line 28, in process_stream_events
    kernel.do_one_iteration()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 291, in do_one_iteration
    stream.flush(zmq.POLLIN, 1)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 352, in flush
    self._handle_recv()
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-bcc363f6a19b>", line 33, in <module>
    max_checkpoints=10, tensorboard_verbose=0)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 111, in __init__
    clip_gradients)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 565, in initialize_training_ops
    self.grad = tf.gradients(total_loss, self.train_vars)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 481, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 303, in _AvgPoolGrad
    data_format=op.get_attr("data_format"))
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 146, in _avg_pool_grad
    data_format=data_format, name=name)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'ResidualBottleneck_3/AvgPool2D/AvgPool', defined at:
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 205, in <module>
    __ipythonkernel__.start()
[elided 20 identical lines from previous traceback]
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-bcc363f6a19b>", line 21, in <module>
    net = tflearn.residual_bottleneck(net, 1, 64, 256, downsample=True)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/layers/conv.py", line 856, in residual_bottleneck
    downsample_strides)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tflearn/layers/conv.py", line 429, in avg_pool_2d
    inference = tf.nn.avg_pool(incoming, kernel, strides, padding)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 508, in avg_pool
    name=name)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 48, in _avg_pool
    data_format=data_format, name=name)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/agiovann/anaconda/envs/CNMF/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

**Comment by agiovann** [comment]
Apparently I had an old version of tf installed. Reinstalling everything solved the issue. Sorry about the troubles.
