### ISSUE TITLE
using .next in python3 

### ISSUE THREAD

**Issue by YehudaItkin** [tflearn/tflearn#294]
classes = sorted(os.walk(directory).next()[1]) 
AttributeError: 'generator' object has no attribute 'next'

python version = 3.5
How to reproduce:
run this: https://github.com/tflearn/tflearn/blob/master/examples/images/alexnet.py

**Comment by aymericdamien** [comment]
This is strange, it has been fix long time ago. Could you try to use the latest version:
```
sudo pip3 install git+https://github.com/tflearn/tflearn.git
```
Also, can you make sure that your directory actually exists (should be '17flowers')

**Comment by ibadami** [comment]
The error comes for the reason that it tries to find .pkl file which does not exist in the folder after download is finished.
Following is the error message I am getting:
```

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Downloading Oxford 17 category Flower Dataset, Please wait...
('Succesfully downloaded', '17flowers.tgz', 60270631, 'bytes.')
File Extracted
Starting to parse images...
Traceback (most recent call last):
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/data_utils.py", line 339, in build_image_dataset_from_dir
    X, Y = pickle.load(open(dataset_file, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/badami/Codes/deeplearning/datasets/17flowers/17flowers.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_vgg.py", line 27, in <module>
    X, Y = oxflower17.load_data(dirname=datasetsdir + '17flowers',one_hot=True)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/datasets/oxflower17.py", line 34, in load_data
    categorical_Y=one_hot)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/data_utils.py", line 341, in build_image_dataset_from_dir
    X, Y = image_dirs_to_samples(directory, resize, convert_gray, filetypes)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/data_utils.py", line 320, in image_dirs_to_samples
    samples, targets = directory_to_samples(directory, flags=filetypes)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/data_utils.py", line 474, in directory_to_samples
    classes = sorted(os.walk(directory).next()[1])
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by hejz** [comment]
I've met this issue too, when I run this code
`import tflearn.datasets.oxflower17 as oxflower17

X, Y = oxflower17.load_data("data/17flowers", one_hot=True, resize_pics=(227, 227))`

I'm sure the directory "data/17flowers" exists, and I've installed the lasted version for both Python2.7 and Python3.6 using this command today.
`sudo pip install git+https://github.com/tflearn/tflearn.git
sudo pip3 install git+https://github.com/tflearn/tflearn.git`
But when I run the above code on Python 2.7, I get
`File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tflearn/data_utils.py", line 732, in directory_to_samples
    classes = sorted(os.walk(directory).__next__()[1])
AttributeError: 'generator' object has no attribute '__next__'`
and on Python 3.6, I get
`/anaconda/lib/python3.6/site-packages/tflearn/data_utils.py in directory_to_samples(directory, flags, filter_channel)
    730         classes = sorted(os.walk(directory).next()[1])
    731     except Exception: # Python 3
--> 732         classes = sorted(os.walk(directory).__next__()[1])
    733     for c in classes:
    734         c_dir = os.path.join(directory, c)

StopIteration:`
