### ISSUE TITLE
cifar10.load_data(dirname="/tmp/data") does not work

### ISSUE THREAD

**Issue by davidenitti** [tflearn/tflearn#295]
the command cifar10.load_data() does not work if I specify the dirname paramenter.
It downloads the data in the dirname directory but it extracts them in the current directory (regardless of dirname) and thus it does not work.

example:
```
from tflearn.datasets import cifar10
(Xtr, Ytr), (X_test, Y_test) = cifar10.load_data(dirname="/tmp/data")
```

output:
```
Downloading CIFAR 10, Please wait...
('Succesfully downloaded', 'cifar-10-python.tar.gz', 170498071, 'bytes.')
File Extracted in Current Directory
Traceback (most recent call last):
  File "/home/davide/Dropbox/learning/tflearn_tf_cifar10.py", line 16, in <module>
    (Xtr, Ytr), (X_test, Y_test) = cifar10.load_data(dirname="/tmp/data")
  File "/usr/local/lib/python2.7/dist-packages/tflearn/datasets/cifar10.py", line 28, in load_data
    data, labels = load_batch(fpath)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/datasets/cifar10.py", line 54, in load_batch
    with open(fpath, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/tmp/data/data_batch_1'
```

**Comment by aymericdamien** [comment]
Hi, thanks for reporting that issue, it is fixed now, please reinstall TFLearn (bleeding edge version)

**Comment by yousefzook** [comment]
you can just navigate to /tmp/ and unzip the file called data.tar.zip which will replace the /data/ file with a fixed one. This worked for me!
