### ISSUE TITLE
Tensor name "Training_step" not found in checkpoint files

### ISSUE THREAD

**Issue by burness** [tflearn/tflearn#317]
Hi, all:

When I use the vgg16.tflearn in tflearn/models to finetuning to a new task, I met a problem with the Training_step:

`E tensorflow/core/client/tensor_c_api.cc:485] Tensor name "Training_step" not found in checkpoint files /Users/burness/git_repository/CV_bot/data/model_data/vgg16.tflearn
	 [[Node: save_1/restore_slice_1 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_1/tensor_name, save_1/restore_slice_1/shape_and_slice)]]
Traceback (most recent call last):
  File "/Users/burness/git_repository/CV_bot/script/models/vgg/fine-tuning.py", line 89, in <module>
    model.load(model_file)
  File "build/bdist.macosx-10.5-x86_64/egg/tflearn/models/dnn.py", line 248, in load
  File "build/bdist.macosx-10.5-x86_64/egg/tflearn/helpers/trainer.py", line 450, in restore
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "Training_step" not found in checkpoint files /Users/burness/git_repository/CV_bot/data/model_data/vgg16.tflearn
	 [[Node: save_1/restore_slice_1 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_1/tensor_name, save_1/restore_slice_1/shape_and_slice)]]
Caused by op u'save_1/restore_slice_1', defined at:
  File "/Users/burness/git_repository/CV_bot/script/models/vgg/fine-tuning.py", line 84, in <module>
    max_checkpoints=3, tensorboard_verbose=2)
  File "build/bdist.macosx-10.5-x86_64/egg/tflearn/models/dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "build/bdist.macosx-10.5-x86_64/egg/tflearn/helpers/trainer.py", line 133, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 519, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 272, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 187, in restore_op
    preferred_shard=preferred_shard)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 203, in _restore_slice
    preferred_shard, name=name)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()`

I guess that it must have new Training_step in some ops, but how can it solve this issue ? Thanks

**Comment by burness** [comment]
I fix this problem， I change the weight_only to True and it's ok now
