### ISSUE TITLE
An error in residual example 

### ISSUE THREAD

**Issue by burness** [tflearn/tflearn#331]
When I try to run the residual network in the example, it get  an error like that, It seem when downsample is True, the code will get the ksize will be less than stride, please check this, thanks !!!
```
/Users/burness/anaconda/bin/python2.7 /Users/burness/git_repository/tflearn/examples/images/residual_network_cifar10.py
[1, 1, 1, 1] [1, 2, 2, 1]
[1, 1, 1, 1] [1, 2, 2, 1]
---------------------------------
Run id: resnet_cifar10
Log directory: /tmp/tflearn_logs/
---------------------------------
Preprocessing... Calculating mean over all dataset (this may take long)...
Mean: [ 0.49139968  0.48215841  0.44653091] (To avoid repetitive computation, add it to argument 'mean' of `add_featurewise_zero_center`)
---------------------------------
Training samples: 50000
Validation samples: 10000
--
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
W tensorflow/core/framework/op_kernel.cc:936] Invalid argument: stride must be less than or equal to kernel size
E tensorflow/core/client/tensor_c_api.cc:485] stride must be less than or equal to kernel size
	 [[Node: Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/AvgPoolGrad = AvgPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/Shape, Momentum/gradients/ResidualBlock_3/Pad_grad/Slice_1)]]
Traceback (most recent call last):
  File "/Users/burness/git_repository/tflearn/examples/images/residual_network_cifar10.py", line 67, in <module>
    run_id='resnet_cifar10')
  File "/Users/burness/git_repository/tflearn/tflearn/models/dnn.py", line 202, in fit
    callbacks=callbacks)
  File "/Users/burness/git_repository/tflearn/tflearn/helpers/trainer.py", line 304, in fit
    show_metric)
  File "/Users/burness/git_repository/tflearn/tflearn/helpers/trainer.py", line 759, in _train
    feed_batch)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 654, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 722, in _do_run
    target_list, options, run_metadata)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 742, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: stride must be less than or equal to kernel size
	 [[Node: Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/AvgPoolGrad = AvgPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/Shape, Momentum/gradients/ResidualBlock_3/Pad_grad/Slice_1)]]
Caused by op u'Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/AvgPoolGrad', defined at:
  File "/Users/burness/git_repository/tflearn/examples/images/residual_network_cifar10.py", line 62, in <module>
    clip_gradients=0.)
  File "/Users/burness/git_repository/tflearn/tflearn/models/dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/Users/burness/git_repository/tflearn/tflearn/helpers/trainer.py", line 119, in __init__
    clip_gradients)
  File "/Users/burness/git_repository/tflearn/tflearn/helpers/trainer.py", line 640, in initialize_training_ops
    self.grad = tf.gradients(total_loss, self.train_vars)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 478, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 350, in _AvgPoolGrad
    data_format=op.get_attr("data_format"))
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 146, in _avg_pool_grad
    data_format=data_format, name=name)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'ResidualBlock_3/AvgPool2D/AvgPool', defined at:
  File "/Users/burness/git_repository/tflearn/examples/images/residual_network_cifar10.py", line 49, in <module>
    net = tflearn.residual_block(net, 1, 64, downsample=True)
  File "/Users/burness/git_repository/tflearn/tflearn/layers/conv.py", line 1029, in residual_block
    downsample_strides)
  File "/Users/burness/git_repository/tflearn/tflearn/layers/conv.py", line 328, in avg_pool_2d
    inference = tf.nn.avg_pool(incoming, kernel, strides, padding)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 637, in avg_pool
    name=name)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 48, in _avg_pool
    data_format=data_format, name=name)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()


Process finished with exit code 1

```

**Comment by aymericdamien** [comment]
Hi, unfortunately, TensorFlow has this error with CPU (but not GPU). Please use this older version script that has a fix: https://github.com/tflearn/tflearn/blob/c5bdfe00fbe2f8a9fc24d4e39b7058c4a858c5b7/tflearn/layers/conv.py#L692

**Comment by burness** [comment]
@aymericdamien  Thanks
