### ISSUE TITLE
'tflearn_logs' dir permission issue.

### ISSUE THREAD

**Issue by papower1** [tflearn/tflearn#358]
I've get '/tmp/tflearn_logs/ permission denied'.

My traceback is attached.

I think we can handle that.
With setting permission for all users when tflearn makes tflearn_logs dir.

> Run id: Q17392
Log directory: /tmp/tflearn_logs/
Traceback (most recent call last):
  File "learner.py", line 82, in <module>
    model.fit(trainX, trainY, validation_set=0.1, n_epoch = N_EPOCH, show_metric=True, batch_size=256, snapshot_epoch=True, snapshot_step=500)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 213, in fit
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 231, in fit
    self.tensorboard_dir + run_id, self.session.graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 102, in __init__
    gfile.MakeDirs(self._logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 295, in MakeDirs
    os.makedirs(path, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/tmp/tflearn_logs/Q17392'

**Comment by aymericdamien** [comment]
It means you do not have access to /tmp/tflearn_logs, maybe you ran tflearn with 2 different users, and one has ownership to /tmp/tflearn_logs and not the other one. To fix it, you can:
```
sudo chmod -R 777 /tmp/tflearn_logs
```

**Comment by papower1** [comment]
It solved. Thank you.
