### ISSUE TITLE
BatchNormalization error when building residual network under v.0.2.2

### ISSUE THREAD

**Issue by abdoelali** [tflearn/tflearn#375]
Updating tflearn to 0.2.2 gives the following error when building a residual network, but not on 0.2.1. Is this already a known issue? Note: I'm deliberately using `shallow_residual_block` since I'm rebuilding the network on a CPU (given the known issue that the updated `residual_block` only works for GPUs).

My ResNet model:

``
self.network = input_data(shape = [None, SIZE, SIZE, 1], data_preprocessing=img_prep, data_augmentation=img_aug)
    self.network = conv_2d(self.network, 16, 3, regularizer='L2', weight_decay=0.0001) 
    self.network = shallow_residual_block(self.network, n, 16)
    self.network = shallow_residual_block(self.network, 1, 32, downsample=True) 
    self.network = shallow_residual_block(self.network, n-1, 32) 
    self.network = shallow_residual_block(self.network, 1, 64, downsample=True) 
    self.network = shallow_residual_block(self.network, n-1, 64) 
    self.network = batch_normalization(self.network)
    self.network = activation(self.network, 'relu') 
    self.network = global_avg_pool(self.network)
    self.network = tflearn.fully_connected(self.network, len(ELIST), `activation='softmax') ``

Output:
``
[+] Building ResNet
E tensorflow/core/client/tensor_c_api.cc:485] Tensor name "BatchNormalization_1/gamma" not found in checkpoint files ./data/resnet_model_mom_100e_n6
	 [[Node: save_1/restore_slice_6 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_6/tensor_name, save_1/restore_slice_6/shape_and_slice)]]

Traceback (most recent call last):
  File "plot_emotion_matrix.py", line 12, in <module>
    network.build_network()
  File "/Users/aelali/Desktop/CNNemotions2/emotion_recognition_resnet.py", line 66, in build_network
    self.load_model()
  File "/Users/aelali/Desktop/CNNemotions2/emotion_recognition_resnet.py", line 110, in load_model
    self.model.load(join(SAVE_DIRECTORY, SAVE_MODEL_FILENAME))
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tflearn/models/dnn.py", line 260, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 447, in restore
    self.restorer.restore(self.session, model_file)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "BatchNormalization_1/gamma" not found in checkpoint files ./data/resnet_model_mom_100e_n6
	 [[Node: save_1/restore_slice_6 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_6/tensor_name, save_1/restore_slice_6/shape_and_slice)]]
Caused by op u'save_1/restore_slice_6', defined at:
  File "plot_emotion_matrix.py", line 12, in <module>
    network.build_network()
  File "/Users/aelali/Desktop/CNNemotions2/emotion_recognition_resnet.py", line 65, in build_network
    clip_gradients=0., tensorboard_dir='resnet_logs_mom_2')
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tflearn/models/dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 133, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 519, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 272, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 187, in restore_op
    preferred_shard=preferred_shard)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 203, in _restore_slice
    preferred_shard, name=name)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/aelali/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()

**Comment by aymericdamien** [comment]
Could you try to restore weights only?
```
model.load(..., weights_only=True)
```

**Comment by abdoelali** [comment]
Getting the same error.
