### ISSUE TITLE
Error when using build_hdf5_image_dataset

### ISSUE THREAD

**Issue by 10wei1000** [tflearn/tflearn#412]
Hello. When I was trying to build my own dataset by using "build_hdf5_image_dataset", the following error occurred:

python build_train.py 

Traceback (most recent call last):
  File "build_train.py", line 11, in <module>
    categorical_labels=True, normalize=True, files_extension=['.jpeg'])
  File "/usr/local/lib/python2.7/site-packages/tflearn/data_utils.py", line 384, in build_hdf5_image_dataset
    n_classes = np.max(labels) + 1
  File "/usr/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2293, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

<br><br>
And my python script to build the dataset was written like:

import tflearn

dataset_file = 'TRAIN/'

from tflearn.data_utils import build_hdf5_image_dataset
build_hdf5_image_dataset(dataset_file, image_shape=(128, 128),
                         mode='folder', output_path='training_set.h5',
                         categorical_labels=True, normalize=True, files_extension=['.jpeg'])

<br><br>
In the folder "TRAIN" there are 2 subfolders each with name "0" and "1".
<br>
Looking forward to your help! Thanks!

**Comment by 10wei1000** [comment]
solved! The extension of images in the subfolders are all ".JPEG". So it works when I change the "files_extension=['.jpeg']" to "files_extension=['.JPEG']" in the code.
