### ISSUE TITLE
Noob question, Titanic example fails

### ISSUE THREAD

**Issue by hugetto** [tflearn/tflearn#413]
Hello everyone, I'm starting to learn tensorflow and I have the following problem:
I've installed tflearn, tensorflow, pillow and most of the libraries needed to use TFLearn.

I copied the source from the titanic example (http://tflearn.org/tutorials/quickstart.html), but when I try to run the example, the code fails when training the network with the following error:

`---------------------------------
Run id: NK92RD
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 1309
Validation samples: 0
--
Traceback (most recent call last):
  File "/home/osboxes/Documents/LiClipse Workspace/TensorFlowTest/Titanic.py", line 42, in <module>
    model.fit(data, labels, n_epoch=10, batch_size=16, show_metric=True)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 214, in fit
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 314, in fit
    caller.on_batch_end(self.training_state, snapshot)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/callbacks.py", line 65, in on_batch_end
    callback.on_batch_end(training_state, snapshot)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/callbacks.py", line 128, in on_batch_end
    self.print_termlogs(training_state)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/callbacks.py", line 217, in print_termlogs
    clear_output(wait=True)
TypeError: clear_output() got an unexpected keyword argument 'wait'`

Anyone else got this error and know how to fix it?

Thank you!

**Comment by hugetto** [comment]
Ok I edited the file /usr/local/lib/python2.7/dist-packages/tflearn/cabacks.py 
and changed clear_output(wait=True) to clear_output()

**Comment by tgallice** [comment]
Are you sure that your IPython version is up to date ? The `wait` flag was added in the version 2.0
