### ISSUE TITLE
Error when running examples of tflearn

### ISSUE THREAD

**Issue by Lukeeeeee** [tflearn/tflearn#417]
lukedong@ubuntu:~/tensorflow/tflearn-master/examples/basics$ python logical.py
hdf5 not supported (please install/reinstall h5py)
Traceback (most recent call last):
  File "logical.py", line 9, in <module>
    import tflearn
  File "build/bdist.linux-x86_64/egg/tflearn/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/models/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/models/dnn.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/evaluator.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/utils.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/tflearn/variables.py", line 8, in <module>
AttributeError: 'module' object has no attribute 'contrib'

-------------------------
When I run the examples of tflearn,  here is the error in shell.
“AttributeError: 'module' object has no attribute 'contrib' ”

**Comment by Lukeeeeee** [comment]
The tensorflow version is 0.6.0  installed by pip
tflearn version is 0.2.2 installed by running setup.py

**Comment by Lukeeeeee** [comment]
Solved it by upgrade tensorflow
