### ISSUE TITLE
Variable Initialization Issue with TFlearn in Tensorflow v12

### ISSUE THREAD

**Issue by DavidMChan** [tflearn/tflearn#491]
The following error occurs during training with Tensorflow v0.12 and TFlearn v0.2.2 head:

```
WARNING:tensorflow:From C:\Python35\lib\site-packages\tflearn-0.2.2-py3.5.egg\tflearn\helpers\trainer.py:149 in __init__.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "C:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value is_training
         [[Node: is_training/read = Identity[T=DT_BOOL, _class=["loc:@is_training"], _device="/job:localhost/replica:0/task:0/cpu:0"](is_training)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_pca_cross_entropy_loss_based_cnn.py", line 105, in <module>
    best_val_accuracy = cfg['best_val_accuracy'])
  File "C:\Python35\lib\site-packages\tflearn-0.2.2-py3.5.egg\tflearn\models\dnn.py", line 63, in __init__
  File "C:\Python35\lib\site-packages\tflearn-0.2.2-py3.5.egg\tflearn\helpers\trainer.py", line 150, in __init__
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value is_training
         [[Node: is_training/read = Identity[T=DT_BOOL, _class=["loc:@is_training"], _device="/job:localhost/replica:0/task:0/cpu:0"](is_training)]]

Caused by op 'is_training/read', defined at:
  File "test_pca_cross_entropy_loss_based_cnn.py", line 23, in <module>
    import tflearn
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Python35\lib\site-packages\tflearn-0.2.2-py3.5.egg\tflearn\__init__.py", line 71, in <module>
    config.init_training_mode()
  File "C:\Python35\lib\site-packages\tflearn-0.2.2-py3.5.egg\tflearn\config.py", line 127, in init_training_mode
    trainable=False)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variables.py", line 370, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value is_training
         [[Node: is_training/read = Identity[T=DT_BOOL, _class=["loc:@is_training"], _device="/job:localhost/replica:0/task:0/cpu:0"](is_training)]]
```

**Comment by aymericdamien** [comment]
We are working on a patch for TensorFlow 0.12, the only solution now is to use TF 0.11
