### ISSUE TITLE
About training by GPU

### ISSUE THREAD

**Issue by joei1981** [tflearn/tflearn#501]
I used alexnet.py for make a model by CPU, and it was no problem. When I configured tensorflow by GPU, I used the same code for making a new model, but it failed and the error messages are as follows:
----
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)

Traceback (most recent call last):
  File "alexnet_training.py", line 80, in <module>
    max_checkpoints=1, tensorboard_verbose=2)
  File "/home/deep/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tflearn/models/dnn.py", line 57, in __init__
    session=session)
  File "/home/deep/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 125, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/home/deep/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/home/deep/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
----

Does anyone give me some idea ?

**Comment by DefinitlyEvil** [comment]
I got the same thing: 
```
I ........\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
I ........\gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
E ........\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:0, defaulting to 0.  Your kernel may not have been built with NUMA support.
E ........\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:1, defaulting to 0.  Your kernel may not have been built with NUMA support.
Traceback (most recent call last):
  File "convnet_mnist.py", line 42, in <module>
    model = tflearn.DNN(network, tensorboard_verbose=0)
  File "D:\Programs\Python35\lib\site-packages\tflearn\models\dnn.py", line 57, in __init__
    session=session)
  File "D:\Programs\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 125, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "D:\Programs\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by joei1981** [comment]
@DefinitlyEvil I resolved this problem by adding the following code before "model = tflearn.DNN(network, checkpoint_path='model_alexnet', max_checkpoints=1, tensorboard_verbose=2)". But when I used googlenet for training, this method will result in another problem.

----
### add this "fix":
col = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
for x in col:
    tf.add_to_collection(tf.GraphKeys.VARIABLES, x ) 
----

**Comment by DefinitlyEvil** [comment]
@joei1981 So this code manually recover the data to the saver?

**Comment by joei1981** [comment]
@DefinitlyEvil I think so.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.

**Comment by DefinitlyEvil** [comment]
@joei1981 Cool, gonna try this out. I like this library because it abstracted all the handy math part so I only need to consider what I rly want. :P I am a math noob.
