### ISSUE TITLE
conv_2d activation == None raises an 'Invalid Activation Error' 

### ISSUE THREAD

**Issue by kwotsin** [tflearn/tflearn#511]
Error stack:
```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
WARNING:tensorflow:tf.variable_op_scope(values, name, default_name) is deprecated, use tf.variable_scope(name, default_name, values)
Traceback (most recent call last):
  File "code_TL.py", line 98, in <module>
    conv1a_3_3 = relu(batch_normalization(conv_2d(network, 32, 3, strides=2, bias=False, padding='VALID',activation=None,name='Conv2d_1a_3x3')))
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/conv.py", line 105, in conv_2d
    raise ValueError("Invalid Activation.")
ValueError: Invalid Activation.
```
In the official documentation, a None activation is allowed for conv_2d, as seen in:
http://tflearn.org/layers/conv/

However, in the inception-resnet-v2 model, activation is None, which automatically raises this error. This code can be found in:
https://github.com/tflearn/tflearn/blob/master/examples/images/inception_resnet_v2.py
lines 107-113

```
        if activation:
            if isinstance(activation, str):
                inference = activations.get(activation)(inference)
            elif hasattr(activation, '__call__'):
                inference = activation(inference)
            else:
                raise ValueError("Invalid Activation.")
```

How can I fix this issue? Will it be alright to let no activation occur?

**Comment by aymericdamien** [comment]
For no activation, please use `'linear'` (The default). It is a mistake in the docs, will correct that.
