### ISSUE TITLE
There is something wrong when I restore the net's weights from the checkpoint files. 

### ISSUE THREAD

**Issue by NeutronT** [tflearn/tflearn#526]
My codes:
1. model = tflearn.DNN(network,checkpoint_path='W:\AnimalClassification\models\model_googlenet',max_checkpoints=1, tensorboard_verbose=2)
2. model.load ('W:\AnimalClassification\models\model_googlenet', weights_only=True)
3.  model.fit(X, Y, n_epoch=1, validation_set=0.1, shuffle=True,
           show_metric=True, batch_size=64, snapshot_step=200,
         snapshot_epoch=False, run_id='googlenet_oxflowers17')
4. model.save('W:\AnimalClassification\models\go_net')`
Errors:
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for W:\AnimalClassification\models\model_googlenet
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "D:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for W:\AnimalClassification\models\model_googlenet
	 [[Node: save_2/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_2/Const_0, save_2/RestoreV2_12/tensor_names, save_2/RestoreV2_12/shape_and_slices)]]
	 [[Node: save_2/RestoreV2_89/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_728_save_2/RestoreV2_89", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:/AnimalClassification/google_net.py", line 133, in <module>
    model.load ('W:\AnimalClassification\models\model_googlenet', weights_only=True)
  File "D:\Python35\lib\site-packages\tflearn\models\dnn.py", line 260, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "D:\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 436, in restore
    self.restorer_trainvars.restore(self.session, model_file)
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for W:\AnimalClassification\models\model_googlenet
	 [[Node: save_2/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_2/Const_0, save_2/RestoreV2_12/tensor_names, save_2/RestoreV2_12/shape_and_slices)]]
	 [[Node: save_2/RestoreV2_89/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_728_save_2/RestoreV2_89", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save_2/RestoreV2_12', defined at:
  File "W:/AnimalClassification/google_net.py", line 132, in <module>
    max_checkpoints=1, tensorboard_verbose=2)
  File "D:\Python35\lib\site-packages\tflearn\models\dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "D:\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 152, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 624, in build
    restore_sequentially, reshape)
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "D:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "D:\Python35\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for W:\AnimalClassification\models\model_googlenet
	 [[Node: save_2/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_2/Const_0, save_2/RestoreV2_12/tensor_names, save_2/RestoreV2_12/shape_and_slices)]]
	 [[Node: save_2/RestoreV2_89/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_728_save_2/RestoreV2_89", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Process finished with exit code 1

**Comment by aymericdamien** [comment]
I believe this is due to TF 0.12.0. Please downgrade to TF 0.11 rc2 while we are releasing a patch that fully support the new TensorFlow version.
