### ISSUE TITLE
ImportError: No module named '_curses'

### ISSUE THREAD

**Issue by smithdir101** [tflearn/tflearn#531]
Hi All,

i just intsalled the tftrean for widnows , python 3.5 for 64 bits and I got this:

Traceback (most recent call last):
  File "dp_v5.py", line 2, in <module>
    import tflearn
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\__init__.py", line 8, in <module>
    from . import models
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\models\__init__.py", line 2, in <module>
    from .dnn import DNN
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\models\dnn.py", line 5, in <module>
    from ..helpers.trainer import Trainer
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\helpers\__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\helpers\evaluator.py", line 10, in <module>
    from .trainer import evaluate_flow
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 12, in <module>
    from .. import callbacks
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\callbacks.py", line 3, in <module>
    import sys, curses
  File "C:\Program Files\Anaconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *

ImportError: No module named '_curses'

I followed the advise :
=============================================
benb969  commented 16 days ago 

I was able to install curses from here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses
 And was then able to use tflearn to some extent on windows, but got different issues (will post later)
 
=============================

but i get the same error.

Could any one advise.

Thanks,

Jhon

**Comment by zchky** [comment]
i have the same problem too

**Comment by hipoglucido** [comment]
+1

**Comment by SnowWalkerJ** [comment]
This is because `curses` package is not supported in windows. Try installing `Unicurses` for windows. It should solve your problem, at least in my case.

**Comment by jaradc** [comment]
Unicurses doesn't seem supported. I did try to install it (I have Python 3.5) but when installer launched, it couldn't find my version of Python. At this point, I followed this answer here: http://stackoverflow.com/a/41224335/1577947 and was able to import tflearn and not have the `ImportError: No module named '_curses'` appear.

**Comment by DavidMChan** [comment]
It seems like curses isn't used prominently in the TFLearn library so I have suggested removing the library as a required dependency. See PR #549
