### ISSUE TITLE
build_hdf5_image_dataset TypeError.

### ISSUE THREAD

**Issue by jadenyjw** [tflearn/tflearn#548]
My images are dimensions 176x144. If I run build_hdf5_image_dataset with those dimensions, then it returns this error:
`
Traceback (most recent call last):
  File "tf_testing.py", line 16, in <module>
    build_hdf5_image_dataset(dataset_file, image_shape=[176, 144], mode='file', output_path='dataset.h5', categorical_labels=True)
  File "/usr/lib/python3.5/site-packages/tflearn/data_utils.py", line 414, in build_hdf5_image_dataset
    dataset['X'][i] = img
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2642)
  File "/usr/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 617, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/usr/lib/python3.5/site-packages/h5py/_hl/selections.py", line 297, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
TypeError: Can't broadcast (144, 176, 3) -> (1, 176, 144, 3)
`

However, if I use something else like 128x128, then it seems to work.

EDIT: It seems like it only accepts square dimensions?

**Comment by awilliamson** [comment]
@jadenyjw See https://github.com/h5py/h5py/issues/844 It appears to be an issue with converting TIF from within data_utils. It swaps the width and height dimension, thus causing conflict between your specified dimensions and image actual when it gets processed within h5py.
