### ISSUE TITLE
ImportError: No module named 'tensorflow.models'

### ISSUE THREAD

**Issue by EncodeTS** [tflearn/tflearn#563]
I compiled the latest TensorFlow(https://github.com/tensorflow/tensorflow/commit/73bc428901dfd6507bbea1315c8813f2048233ff), and everything is ok, I can also import TensorFlow in python.
But when I import tflearn(compiled from https://github.com/tflearn/tflearn/commit/d9a6689ea6a9437ea44bd3a283e18de0f74c127e), the following error occured:
```
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
>>> import tflearn
Traceback (most recent call last):
  File "/home/ts/library/tflearn/tflearn/layers/recurrent.py", line 9, in <module>
    from tensorflow.python.ops.nn import rnn_cell as _rnn_cell
ImportError: cannot import name 'rnn_cell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ts/library/tflearn/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/home/ts/library/tflearn/tflearn/layers/__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/home/ts/library/tflearn/tflearn/layers/recurrent.py", line 13, in <module>
    from tensorflow.models.rnn import rnn_cell as _rnn_cell
ImportError: No module named 'tensorflow.models'
```

**Comment by aymericdamien** [comment]
It may have a problem with latest version of TensorFlow. I pushed a fix to support the new TF script. You can have a try.

**Comment by EncodeTS** [comment]
@aymericdamien It works! I can import tflearn without errors now.
