### ISSUE TITLE
atari_1step_qlearning.py: RuntimeError('Attempted to use a closed Session.')

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#590]
Hi, tflearn Team,

I use the newest tflearn and the 0.12 tensorflow try the q learning example and get the following error.
Do you know why is this happening?

Thank you!

Best,
Rui

/home/ubuntu/anaconda2/bin/python2.7 /home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
[2017-02-06 14:21:37,172] Making new env: MsPacman-v0
[2017-02-06 14:21:37,851] Making new env: MsPacman-v0
[2017-02-06 14:21:37,881] Making new env: MsPacman-v0
[2017-02-06 14:21:37,907] Making new env: MsPacman-v0
[2017-02-06 14:21:37,933] Making new env: MsPacman-v0
[2017-02-06 14:21:37,958] Making new env: MsPacman-v0
[2017-02-06 14:21:37,984] Making new env: MsPacman-v0
[2017-02-06 14:21:38,009] Making new env: MsPacman-v0
[2017-02-06 14:21:38,035] Making new env: MsPacman-v0
WARNING:tensorflow:From /home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py:390 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
[2017-02-06 14:21:38,284] From /home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py:390 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Thread 0 - Final epsilon: 0.1
Thread 1 - Final epsilon: 0.1
Thread 2 - Final epsilon: 0.1
Thread 3 - Final epsilon: 0.5
Thread 4 - Final epsilon: 0.01
Thread 5 - Final epsilon: 0.01
Thread 6 - Final epsilon: 0.5
Thread 7 - Final epsilon: 0.1
Traceback (most recent call last):
  File "/home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py", line 465, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py", line 462, in main
    train(session, graph_ops, num_actions, saver)
  File "/home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py", line 411, in train
    env.render()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/gym/core.py", line 174, in render
    return self._render(mode=mode, close=close)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/gym/envs/atari/atari_env.py", line 119, in _render
    from gym.envs.classic_control import rendering
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1817, in <module>
    gl._create_shadow_window()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/window/__init__.py", line 505, in __init__
    config = screen.get_best_config(template_config)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/canvas/base.py", line 161, in get_best_config
    configs = self.get_matching_configs(template)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/canvas/xlib.py", line 179, in get_matching_configs
    configs = template.match(canvas)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/gl/xlib.py", line 29, in match
    have_13 = info.have_version(1, 3)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/pyglet/gl/glx_info.py", line 89, in have_version
    client = [int(i) for i in client_version.split('.')]
ValueError: invalid literal for int() with base 10: 'None'
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py", line 258, in actor_learner_thread
    feed_dict = {st : [s_t1]})
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 575, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3633, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 902, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tflearn/examples/reinforcement_learning/atari_1step_qlearning.py", line 239, in actor_learner_thread
    readout_t = q_values.eval(session=session, feed_dict={s: [s_t]})
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 575, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3633, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 902, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by SnowWalkerJ** [comment]
I ran in this situation as well

**Comment by haoyue77** [comment]
So have you figured it out?

**Comment by SnowWalkerJ** [comment]
Nop, I decided to write one from the beginning.
