### ISSUE TITLE
Dimension is not reduced after maxpooling

### ISSUE THREAD

**Issue by hobincar** [tflearn/tflearn#593]
Here's part of my network,
```
...
conv1 = conv_2d(input, nb_filter=96, filter_size=11, strides=4, activation="relu")
lrn1 = local_response_normalization(conv1, depth_radius=2, alpha=0.0001, beta=0.75, bias=1.0)
max1 = max_pool_2d(lrn1, kernel_size=3, strides=2, padding='valid')
conv2 = conv_2d(max1, 256, 5, 1, activation="relu")
...
```

the code for set weights of conv2,
```
...
pretrained_weight = np.load("bvlc_alexnet.npy", encoding="latin1").item()
model.set_weights(conv1.W, pretrained_weight['conv1'][0])
model.set_weights(conv1.b, pretrained_weight['conv1'][1])
model.set_weights(conv2.W, pretrained_weight['conv2'][0]) # error occurs
model.set_weights(conv2.b, pretrained_weight['conv2'][1])
...
```

and the error log
```
...
Traceback (most recent call last):
  File "/Users/hobincar/PycharmProjects/CBIR/run.py", line 27, in <module>
    module1 = PretrainedAlexnet()
  File "/Users/hobincar/PycharmProjects/CBIR/src/model/alexnet.py", line 42, in __init__
    model.set_weights(conv2.W, pretrained_weight['conv2'][0])
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tflearn/models/dnn.py", line 316, in set_weights
    op = tf.assign(tensor, weights)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/hobincar/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 2 in both shapes must be equal, but are 96 and 48 for 'Assign_3' (op: 'Assign') with input shapes: [5,5,96,256], [5,5,48,256].

Process finished with exit code 1
```

I think the dimension should be [5,5,48,256] like the error says since it's maxpooled with stride 2, but it says the dimension of conv2 of my network is [5,5,96,256]. I don't know what I've missed.

I'm using tensorflow v0.12.1, and tflearn v0.2.2

**Comment by hobincar** [comment]
solved by using 'weights_init' and 'bias_init' argument of 'conv_2d' instead of 'set_weights'.
Thanks for great library :)

**Comment by kulkarnikeerti** [comment]
Could you please be more clear, I am facing the same error, but I see there are no arguments called 'weights_init' and 'bias_init' in Conv2D?

**Comment by hobincar** [comment]
@kulkarnikeerti I almost forgot what I did since it is more than 2 years ago, but I think there're `weights_init` and `bias_init` in conv_2d. Please refer http://tflearn.org/layers/conv/


> tflearn.layers.conv.conv_2d (incoming, nb_filter, filter_size, strides=1, padding='same', activation='linear', bias=True, **weights_init**='uniform_scaling', **bias_init**='zeros', regularizer=None, weight_decay=0.001, trainable=True, restore=True, reuse=False, scope=None, name='Conv2D')
