### ISSUE TITLE
ValueError: Tag: Loss/SGD_0 cannot be found in summaries list.

### ISSUE THREAD

**Issue by riemar** [tflearn/tflearn#594]
Hi, 

when running the example "/basics/logical.py" the error below occurs when trying to train the merged XOR model.

Traceback (most recent call last):
  File "logical.py", line 113, in <module>
    m.fit(X, [Y_nand, Y_or], n_epoch=400, snapshot_epoch=False)
  File "xxxxx\Python35\lib\site-packages\tflearn\models\dnn.py", line 215, in fit
    callbacks=callbacks)
  File "xxxxx\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 334, in fit
    show_metric)
  File "xxxxx\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 780, in _train
    sname, train_summ_str)
  File "xxxxx\Python35\lib\site-packages\tflearn\summaries.py", line 203, in get_value_from_summary_string
    raise ValueError("Tag: " + tag + " cannot be found in summaries list.")
ValueError: Tag: Loss/SGD_0 cannot be found in summaries list.

-------
Name: tflearn
Version: 0.2.2
Name: tensorflow
Version: 0.12.1

**Comment by yangapku** [comment]
Same problem occurred when running `basics/logical.py` on py2.7

    Training samples: 8
    Validation samples: 0
    --
    Traceback (most recent call last):
    File "/home/user/projects/PycharmProjects/TF/TFlearn/test.py", line 34, in <module>
    m.fit(X, [Y_nand, Y_or], n_epoch=400, snapshot_epoch=False)
    File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 215, in fit
    callbacks=callbacks)
    File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 333, in fit
    show_metric)
    File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 779, in _train
    sname, train_summ_str)
    File "/usr/local/lib/python2.7/dist-packages/tflearn/summaries.py", line 203, in get_value_from_summary_string
    raise ValueError("Tag: " + tag + " cannot be found in summaries list.")
    ValueError: Tag: Loss/SGD_0 cannot be found in summaries list.

Name: tflearn 
Version: 0.2.2 
Name: tensorflow-gpu
Version: 0.12.0rc0
