### ISSUE TITLE
Errors in running linear regression on Mac with python 3.5.1 (Anaconda)

### ISSUE THREAD

**Issue by rcholic** [tflearn/tflearn#6]
I just did a fresh installation on my Mac 10.11.4 that has python 3.5.1 (Anaconda and Scikit-learn). The tensorflow installation was successful, as I was to verify it with their installation test.

However, I am running into many issues with the first example `linear regress` from [here](https://github.com/tflearn/tflearn/blob/master/examples/basics/linear_regression.py) , I got many complaints about the python 2-style print statements (no paranthesis) and the following issues:
```
Run id: P97QY2
Log directory: /tmp/tflearn_logs/
Traceback (most recent call last):
  File "/Users/xxx/Desktop/Code/Python/Tensorflow/TFLearn/linear_regression/example1.py", line 15, in <module>
    m.fit(X, Y, n_epoch=1000, show_metric=True, snapshot_epoch=False)
  File "/Users/xxx/anaconda/lib/python3.5/site-packages/tflearn/models/dnn.py", line 161, in fit
    run_id=run_id)
  File "/Users/xxx/anaconda/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 190, in fit
    termlogger = callbacks.TermLogger(self.training_step)
  File "/Users/xxx/anaconda/lib/python3.5/site-packages/tflearn/callbacks.py", line 53, in __init__
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database
```

Any idea what might be wrong? Thanks for making the module available!

**Comment by LoveTube** [comment]
I have a similar issue I run  linear regression on ubuntu 14.04 with python 3.4.3 and I got a error message as below

Traceback (most recent call last):
  File "linear_regression.py", line 5, in <module>
    import tflearn
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/models/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/models/dnn.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/helpers/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/helpers/evaluator.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/TFLearn-0.1-py3.4.egg/tflearn/utils.py", line 7, in <module>
  File "/usr/local/lib/python3.4/dist-packages/h5py/__init__.py", line 23, in <module>
    from . import _conv
  File "h5t.pxd", line 14, in init h5py._conv (/tmp/pip_build_root/h5py/h5py/_conv.c:6880)
  File "numpy.pxd", line 66, in init h5py.h5t (/tmp/pip_build_root/h5py/h5py/h5t.c:19085)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by aymericdamien** [comment]
Latest TFLearn version supports python3 (See PR #5). Can you try to update it:
```
pip uninstall tflearn
pip install git+https://github.com/tflearn/tflearn.git
```

It is working for me:
```
Aymerics-MacBook-Pro:~ aymeric$ ~/anaconda3/bin/python ~/tflearn/examples/basics/linear_regression.py 
---------------------------------
Run id: VQQYWE
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 17
Validation samples: 0
--
Training Step: 1000  | total loss: 0.15429
| SGD | epoch: 1000 | loss: 0.15429 - R2: 0.9923 -- iter: 00/17

Regression result:
Y = [ 0.24346755].X + [ 0.85670429]

Test prediction for y = 3.2 and y = 4.5:
[1.6358004808425903, 1.952308177947998]
```
