### ISSUE TITLE
lstm() got an unexpected keyword argument 'return_state'

### ISSUE THREAD

**Issue by yanwii** [tflearn/tflearn#604]
Python 3.5
tflearn (0.2.1)

Traceback (most recent call last):
  File "/home/yanwii/Python/NLP/seq2seq/tf_seq2seq.py", line 62, in <module>
    sqs.buildModel()
  File "/home/yanwii/Python/NLP/seq2seq/tf_seq2seq.py", line 31, in buildModel
    (encoder_output_tensor, states) = tflearn.lstm(encoder_inputs, self.word_vec_dim, return_state=True, scope='encoder_lstm')
TypeError: lstm() got an unexpected keyword argument 'return_state'

**Comment by 307509256** [comment]
解决了吗

**Comment by yanwii** [comment]
直接转tensorflow了。。。
