### ISSUE TITLE
Graph serialization error for LSTMs

### ISSUE THREAD

**Issue by eamartin** [tflearn/tflearn#605]
The following code

```python
import tensorflow as tf
import tflearn

def model():
    time_steps = 20

    network = tflearn.input_data(shape=[None, time_steps, 2], name='input')
    network = tflearn.lstm(network, 200, return_seq=False, name='lstm')
    network = tflearn.fully_connected(network, 1, activation='linear')
    network = tflearn.regression(network, optimizer='adam', learning_rate=0.001,
                                 loss='mean_square', name='output')
    return tflearn.DNN(network, tensorboard_verbose=3,
                       checkpoint_path='save/model.tfl.ckpt')

model()

print 'EXPORTING'
mg = tf.train.export_meta_graph()

print
print 'IMPORTING'

g = tf.Graph()
with g.as_default():
    tf.train.import_meta_graph(mg)
```

gives output
```
EXPORTING
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'

IMPORTING
Traceback (most recent call last):
  File "basic_lstm.py", line 25, in <module>
    tf.train.import_meta_graph(mg)
  File "/home/emartin/test_models/env/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1708, in import_meta_graph
    return _import_meta_graph_def(meta_graph_or_file, clear_devices)
  File "/home/emartin/test_models/env/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1619, in _import_meta_graph_def
    col_op = ops.get_default_graph().as_graph_element(value)
  File "/home/emartin/test_models/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2458, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/emartin/test_models/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2518, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'Adam' refers to an Operation not in the graph."
```

This is with 
```
tensorflow==0.11.0
tflearn==0.2.1
```

It appears various versions of this issue have been reported before: https://github.com/tflearn/tflearn/issues/381#issuecomment-251912961 , https://github.com/tflearn/tflearn/issues/217#issuecomment-234343991 , https://github.com/tflearn/tflearn/issues/480#issuecomment-264389490 .
Reading the error message, my guess is that tflearn is putting objects that aren't tensors (such as ``None`` and ``dict``) into TensorFlow collections, and then TensorFlow doesn't know how to serialize these collections.

**Comment by eamartin** [comment]
I tried adding some code to inspect what's in all of the graph collections.
```python
for name, coll in tf.get_default_graph()._collections.iteritems():
    print '%s: %s' % (name, set(map(type, coll)))
```

This gives output
```
inputs: set([<class 'tensorflow.python.framework.ops.Tensor'>])
('__variable_store',): set([<class 'tensorflow.python.ops.variable_scope._VariableStore'>])
data_augmentation: set([<type 'NoneType'>])
trainable_variables: set([<class 'tensorflow.python.ops.variables.Variable'>])
variables: set([<class 'tensorflow.python.ops.variables.Variable'>])
data_preprocessing: set([<type 'NoneType'>])
summaries: set([<class 'tensorflow.python.framework.ops.Tensor'>])
Adam_training_summaries: set([<class 'tensorflow.python.framework.ops.Tensor'>])
is_training_ops: set([<class 'tensorflow.python.framework.ops.Tensor'>])
layer_variables/lstm/: set([<class 'tensorflow.python.ops.variables.Variable'>])
trainops: set([<class 'tflearn.helpers.trainer.TrainOp'>])
is_training: set([<class 'tensorflow.python.ops.variables.Variable'>])
activations: set([<class 'tensorflow.python.framework.ops.Tensor'>])
summary_tags: set([<type 'dict'>])
targets: set([<class 'tensorflow.python.framework.ops.Tensor'>])
('__varscope',): set([<class 'tensorflow.python.ops.variable_scope.VariableScope'>])
layer_variables/FullyConnected/: set([<class 'tensorflow.python.ops.variables.Variable'>])
```

The warning messages for summary_tags, data_preprocessing, and data_augmentation correspond to the collections that have None or dict in them.

**Comment by roongroj** [comment]
Hi @eamartin, 
Thank you for reporting this issue. I also encountered this similar issue. Have you found any workaround or a fix for this issue? Would appreciate to hear so.

**Comment by lipixun** [comment]
I met the same issue when I was trying to export graph and variables by saved_model module. And finally I found a walk around to fix this issue:

Remove the `TRAIN_OPS` collections from graph collection. e.g.:

```python
with dnn.graph.as_default():
     del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]
```

**Comment by Andrew9Tech** [comment]
@lipixun in version 1.1.0，tf.GraphKeys did not have TRAIN_OPS, only TRAIN_OP,are they same?

**Comment by lipixun** [comment]
@Andrew9Tech I have no idea about 1.1.0. But according to the [source codes of master branch](https://github.com/tflearn/tflearn/blob/master/tflearn/layers/estimator.py#L198), tflearn still uses `TRAIN_OPS` to save the TrainOp objects. You can also verify this by checking the source code of 1.1.0.

**Comment by lipixun** [comment]
By the way, I wrote the following simple codes to help dump models that is constructed by tflearn.

```python
class _DumpableGraph(object):
    """The dumpable graph
    """
    Keys = [ "summary_tags", tf.GraphKeys.GRAPH_CONFIG, tf.GraphKeys.DATA_PREP, tf.GraphKeys.DATA_AUG, tf.GraphKeys.TRAIN_OPS ] #pylint: disable=I0011,E1101

    def __init__(self):
        """Create a new _DumpableGraph
        """
        self._values = {}

    def __enter__(self):
        """Make this graph dumpable
        """
        for key in self.Keys:
            values = tf.get_collection_ref(key)
            self._values[key] = list(values)
            del values[:]

    def __exit__(self, _, __, ___):
        """Restore this graph
        """
        for key in self.Keys:
            if key not in self._values:
                continue
            tf.get_collection_ref(key).extend(self._values[key])
```

And you can use saved_model like this:

```python
# Dump graph and variables by saved_model
        with self._graph.as_default(), _DumpableGraph():
            builder = tf.saved_model.builder.SavedModelBuilder(dirname)
            builder.add_meta_graph_and_variables(self._dnn.session, tags)
            builder.save()
```

**Comment by Eurybus** [comment]
Hey!

I ran into this same issue and I am unable to continue my work. How exactly can I remove TRAIN_OPS from my model?

**Comment by lipixun** [comment]
@Eurybus Set the right default graph, and run:

```python
del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]
```

**Comment by shuri** [comment]
I'm having the same problem I believe. I got the Adam message originally and when I used _DumpableGraph (cool @lipixun :) when saving the graph I get this "Key Global_Step_1 not found in checkpoint".

I save simply like this
```python
tfmodel_save_path = os.path.join(filename, "model")
with graph.as_default(), _DumpableGraph(), session.as_default():
    model.save(tfmodel_save_path)
```
Where model is whatever is returned by tflearn.DNN.

I closed the computer, rebooted. Now I want to load it, architecture and all:
```python
graph = tf.Graph()
session = tf.Session(graph=graph)
with graph.as_default(), session.as_default():
    # Restore this graph (the architecture).
    tfmodel_save_path = os.path.join(path, "model.meta")
    tf.train.import_meta_graph(path)
    # Rebuild the tflearn model.
    net = tfmodel.graph.get_tensor_by_name("FullyConnected/Softmax:0")
    model = tflearn.DNN(net, tensorboard_verbose=0)
    # And restore the rest (only weights, right?).
    tfmodel_save_path = os.path.join(filename, "model")
    **tfmodel.model.load(tfmodel_save_path)**
return tfmodel
```

As for "FullyConnected/Softmax:0", it's the Tensor.name that was passed to the original tflearn.DNN.

I know I'm missing some things here :), any advice?

Thanks!
Uri

**Comment by zwep** [comment]
I face a similar issue, but then while using tf.GraphKeys.MODEL_VARIABLES for placeholders. An example to see this is here




class CollectionsGraphCreator:
    """
    A graph object with multiple nodes that are added to collections
    """
    def __init__(self):
        self.graph_obj = tf.Graph()
        self.saver_obj = tf.train.Saver(defer_build=True)

        with self.graph_obj.as_default() as g_def:
			w1 = tf.get_variable('weight_set', dtype=tf.float32, shape=(5, 5))
			b_bias_fun = tf.get_variable('bias_set', dtype=tf.float32, shape=(5, 5))
			x_input_fun = tf.placeholder(dtype=tf.float32, name='input')
			y_output_fun = tf.placeholder(dtype=tf.float32, name='output')
			
			g_def.add_to_collection('input variables', x_input_fun)
			g_def.add_to_collection(tf.GraphKeys.MODEL_VARIABLES, y_output_fun)  # Adding this will prevent saving
			g_def.add_to_collection('input variables', y_output_fun)
			
			self.saver_obj.build()
			
        self.graph_obj = g_def
		
# How to save a graph object with Collections addede to it?


# Create the Collections-graph object
coll_graph_object = CollectionsGraphCreator().graph_obj

# Now initialize all the variables of the graph.. and save the savers
with tf.Session(graph=coll_graph_object) as sess:
    sess.run(tf.global_variables_initializer())
    saver_graph_object.saver_begin.save(sess, './some_test')


anyone else knows why this happens? Are certain collections being protected or so?

**Comment by geweihgg** [comment]
Hi, @lipixun ,
I've encountered the same problem, and then I used  your method, it works. Now I have a directory, in which there are some files including a "saved_model.pb". How can I restore this model? I've tried to load the model like this:
```
default_graph = tf.get_default_graph()
with default_graph.as_default():
	output_graph_def = tf.GraphDef()
	pb_file_path = self.model_save_dir + "model_1/saved_model.pb"
	with open(pb_file_path, "rb") as f:
		output_graph_def.ParseFromString(f.read())
		_ = tf.import_graph_def(output_graph_def, name="")
```
But error occurred at "output_graph_def.ParseFromString(f.read)":
```
google.protobuf.message.DecodeError: Tag had invalid wire type.
```
I saved the model like this:
```
model_save_path = path + "model_pb/"
meta_graph_tags = ["meta_graph_udef"]
with default_graph.as_default(), default_sess.as_default(), DumpableGraph():
  	builder = tf.saved_model.builder.SavedModelBuilder(model_save_path)
  	builder.add_meta_graph_and_variables(self.sess, meta_graph_tags)
   	builder.save()
```
Can you tell me how to load the model?
Thank you very much.
GeWei

**Comment by lipixun** [comment]
@geweihgg Try this:

```python
from google.protobuf import text_format

default_graph = tf.get_default_graph()
with default_graph.as_default():
	output_graph_def = tf.GraphDef()
	pb_file_path = self.model_save_dir + "model_1/saved_model.pb"
	with open(pb_file_path, "rb") as f:
                 text_format.Merge(str(f.read()), output_graph_def)
		_ = tf.import_graph_def(output_graph_def, name="")
```

**Comment by geweihgg** [comment]
Hi, @lipixun ,
Thank you very much, I’ll try it~
GeWei

**Comment by sathyamoorthyrr** [comment]
Facing similar error https://github.com/tensorflow/tensorflow/pull/12759#issuecomment-467860111
