### ISSUE TITLE
Error on array Index LSTM/RNN

### ISSUE THREAD

**Issue by PrimeF** [tflearn/tflearn#637]
Hello,

I'm trying to execute the following code:
```
import sys
import tensorflow
import tflearn
from tflearn.data_utils import to_categorical, pad_sequences, VocabularyProcessor

text, labels = load_csv(r"C:\Users\Desktop\Machine Learning\Getting Started\Data\train_dataset_rnn.csv", categorical_labels=True, n_classes=2, delim=";")
print(text, labels)

max_document_length = []
temp_max_document_length = []
for string in text:
    for x in string:
        temp_max_document_length.append(len(x.split(" ")))
max_document_length = max(temp_max_document_length)
print(max_document_length)

vocab_processor = tflearn.data_utils.VocabularyProcessor(max_document_length)

text_to_transform = ""
for string in text:
    for x in string:
        text_to_transform = text_to_transform + "\n" + x

print(text_to_transform)

x = np.array(list(vocab_processor.fit_transform(text_to_transform)))

vocab_dict = vocab_processor.vocabulary_._mapping

sorted_vocab = sorted(vocab_dict.items(), key = lambda x : x[1])

vocabulary = list(list(zip(*sorted_vocab))[0])

print("vocabulary:", vocabulary)
print("x", x)

data = pad_sequences(x, maxlen=max_document_length, value=0.)
print(data, labels)

net = tflearn.input_data(shape=[None, max_document_length])
net = tflearn.embedding(net, input_dim=10000, output_dim=128)
net = tflearn.lstm(net, 128)
net = tflearn.fully_connected(net, 2, activation="softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)
model.fit(data, labels, n_epoch=10, batch_size=32, show_metric=True)
```

My CSV file looks like this:
`"some string of maximal 3 words";0 or 1`

The first column is the feature and the second the label.

But unfortunately I get this error:

```
Training samples: 79
Validation samples: 0
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tflearn\data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tflearn\data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tflearn\utils.py", line 187, in slice_array
    return X[start]
IndexError: index 18 is out of bounds for axis 0 with size 11

```
How is this possible?

**Comment by ClarkN3** [comment]
## Very similar issue...

Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\tflearn\data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "C:\Anaconda3\lib\site-packages\tflearn\data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "C:\Anaconda3\lib\site-packages\tflearn\utils.py", line 187, in slice_array
    return X[start]
IndexError: index 32280 is out of bounds for axis 0 with size 24500
Training samples: 73500
Validation samples: 1500
--
