### ISSUE TITLE
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by EricPerbos** [tflearn/tflearn#639]
Anaconda 3.5
TensorFlow 1.0
TFLearn from latest Git pull

In:
> tflearn\examples\extending_tensorflow> python trainer.py

> Traceback (most recent call last):
>   File "trainer.py", line 39, in <module>
>     loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(net, Y))
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1578, in softmax_cross_entropy
>     labels, logits)
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1533, in _ensure_xent_args
>     "named arguments (labels=..., logits=..., ...)" % name)
> ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by guddulrk** [comment]
I am getting the same error. Any solution please...

**Comment by guddulrk** [comment]
File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)

ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by yash0307** [comment]
Please refer to this issue : https://github.com/ibab/tensorflow-wavenet/issues/223

**Comment by Techlucy** [comment]
Hello every one, I had been using Tensorflow 0.12.0-rc0.   But unfortunately it cracked and uninstalled then after I intalled another one which is 1.1.0 ... It is annoying me more. I have the same error on training NN. How to revert to 0.12.0??? Any help, Thanks

**Comment by 370533136** [comment]
Try this
tf.nn.softmax_cross_entropy_with_logits(logits = yPredbyNN, labels=Y)

**Comment by Techlucy** [comment]
Thanks dear @370533136 I have managed using that code.

**Comment by Techlucy** [comment]
Hello, another bug of error has come after tensorflow update.. I have been initializing to save model by  tf.train.Saver() but then after new TF version it is giving me error, 
ValueError: At least two variables have the same name: W/RMSProp   ... 
Any idea help me. Thanks
![image](https://cloud.githubusercontent.com/assets/23651685/25661623/f3091b86-3043-11e7-82a2-1cf32564539f.png)

**Comment by R-Prady** [comment]
worked for me...`cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))`

**Comment by kadirsahan** [comment]
work for me also ... tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))

**Comment by mlpanda** [comment]
Thanks guys, this saved me from a long time of frustration! :D

**Comment by arunanala** [comment]
Thank you for the suggestion tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))

This worked for me too!!!

**Comment by jahidmixmaster** [comment]
Thanks a lot 
Worked for me too

**Comment by aneeta29** [comment]
Please help! I already have my code written out as " tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction,labels=y))"
and I still get this error:
"both labels and logits must be provided"

**Comment by itechoasis** [comment]
@aneeta29
try this 
y = tf.placeholder('float',[None,n_classes])
pred = multilayer_perceptron(x,weights,biases)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))

**Comment by Hari365** [comment]
same problem here

**Comment by mk43** [comment]
May be you can use `tf.nn.softmax_cross_entropy_with_logits_v2(logits = predy, labels= y)`.

```
@deprecation.deprecated(date=None, instructions=_XENT_DEPRECATION)
def softmax_cross_entropy_with_logits(_sentinel=None,  # pylint: disable=invalid-name
                                      labels=None, logits=None,
                                      dim=-1, name=None):
```
as you can see, ` softmax_cross_entropy_with_logits` was deprecated. by the way, just following official recommends, good luck!

**Comment by danelee2601** [comment]
@370533136 Thank you so much. You just solved a problem that I've been having for a week.

**Comment by Mukesh7860** [comment]
### Train my model.
from sklearn.utils import shuffle

rate = 0.001
EPOCHS = 25
BATCH_SIZE = 128
x = tf.placeholder(tf.float32, (None, 32, 32, 1))
y = tf.placeholder(tf.int32, (None))
one_hot_y = tf.one_hot(y, n_classes)
keep_prob = tf.placeholder(tf.float32)


logits = ConvNet(x)
#logits = LeNet(x)

cross_entropy = tf.nn.softmax_cross_entropy_with_logits(one_hot_y,logits)
loss_operation = tf.reduce_mean(cross_entropy)
optimizer = tf.train.AdamOptimizer(learning_rate = rate)
training_operation = optimizer.minimize(loss_operation)

correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(one_hot_y, 1))
accuracy_operation = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
saver = tf.train.Saver()

def evaluate(X_data, y_data):
    num_examples = len(X_data)
    total_accuracy = 0
    sess = tf.get_default_session()
    for offset in range(0, num_examples, BATCH_SIZE):
        batch_x, batch_y = X_data[offset:offset+BATCH_SIZE], y_data[offset:offset+BATCH_SIZE]
        accuracy = sess.run(accuracy_operation, feed_dict={x: batch_x, y: batch_y,keep_prob: 1.0})
        total_accuracy += (accuracy * len(batch_x))
    return total_accuracy / num_examples


print('Done')


Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)    


what should i do on this error?
