### ISSUE TITLE
Installing from source on Ubuntu: "ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting"

### ISSUE THREAD

**Issue by 26medias** [tflearn/tflearn#67]
Hi,

I'm attempting to install from the source on Ubuntu.

However I'm getting an error. I get the same error when installing using `pip install git+https://github.com/tflearn/tflearn.git`

Any idea how to fix?

Here is the output of the terminal:

```
  julien@julien-Linux:~/Desktop/AI/tensorFlow/examples/tflearn-master$ sudo python setup.py install
  running install
  running bdist_egg
  running egg_info
  writing requirements to TFLearn.egg-info/requires.txt
  writing TFLearn.egg-info/PKG-INFO
  writing top-level names to TFLearn.egg-info/top_level.txt
  writing dependency_links to TFLearn.egg-info/dependency_links.txt
  reading manifest file 'TFLearn.egg-info/SOURCES.txt'
  writing manifest file 'TFLearn.egg-info/SOURCES.txt'
  installing library code to build/bdist.linux-x86_64/egg
  running install_lib
  running build_py
  creating build/bdist.linux-x86_64/egg
  creating build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/metrics.py -> build/bdist.linux-x86_64/egg/tflearn
  creating build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/datasets/mnist.py -> build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/datasets/oxflower17.py -> build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/datasets/cifar10.py -> build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/datasets/imdb.py -> build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/datasets/__init__.py -> build/bdist.linux-x86_64/egg/tflearn/datasets
  copying build/lib.linux-x86_64-2.7/tflearn/collections.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/data_preprocessing.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/initializations.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/summaries.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/losses.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/data_augmentation.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/utils.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/config.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/optimizers.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/data_flow.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/callbacks.py -> build/bdist.linux-x86_64/egg/tflearn
  creating build/bdist.linux-x86_64/egg/tflearn/models
  copying build/lib.linux-x86_64-2.7/tflearn/models/generator.py -> build/bdist.linux-x86_64/egg/tflearn/models
  copying build/lib.linux-x86_64-2.7/tflearn/models/dnn.py -> build/bdist.linux-x86_64/egg/tflearn/models
  copying build/lib.linux-x86_64-2.7/tflearn/models/__init__.py -> build/bdist.linux-x86_64/egg/tflearn/models
  copying build/lib.linux-x86_64-2.7/tflearn/objectives.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/data_utils.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/activations.py -> build/bdist.linux-x86_64/egg/tflearn
  copying build/lib.linux-x86_64-2.7/tflearn/__init__.py -> build/bdist.linux-x86_64/egg/tflearn
  creating build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/generator.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/evaluator.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/regularizer.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/trainer.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/__init__.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  copying build/lib.linux-x86_64-2.7/tflearn/helpers/summarizer.py -> build/bdist.linux-x86_64/egg/tflearn/helpers
  creating build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/embedding_ops.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/normalization.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/conv.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/__init__.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/recurrent.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/estimator.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/core.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/layers/merge_ops.py -> build/bdist.linux-x86_64/egg/tflearn/layers
  copying build/lib.linux-x86_64-2.7/tflearn/variables.py -> build/bdist.linux-x86_64/egg/tflearn
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/metrics.py to metrics.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/datasets/mnist.py to mnist.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/datasets/oxflower17.py to oxflower17.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/datasets/cifar10.py to cifar10.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/datasets/imdb.py to imdb.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/datasets/__init__.py to __init__.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/collections.py to collections.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/data_preprocessing.py to data_preprocessing.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/initializations.py to initializations.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/summaries.py to summaries.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/losses.py to losses.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/data_augmentation.py to data_augmentation.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/utils.py to utils.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/config.py to config.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/optimizers.py to optimizers.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/data_flow.py to data_flow.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/callbacks.py to callbacks.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/models/generator.py to generator.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/models/dnn.py to dnn.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/models/__init__.py to __init__.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/objectives.py to objectives.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/data_utils.py to data_utils.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/activations.py to activations.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/__init__.py to __init__.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/generator.py to generator.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/evaluator.py to evaluator.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/regularizer.py to regularizer.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py to trainer.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/__init__.py to __init__.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/helpers/summarizer.py to summarizer.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/embedding_ops.py to embedding_ops.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/normalization.py to normalization.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/conv.py to conv.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/__init__.py to __init__.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/recurrent.py to recurrent.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/estimator.py to estimator.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/core.py to core.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/layers/merge_ops.py to merge_ops.pyc
  byte-compiling build/bdist.linux-x86_64/egg/tflearn/variables.py to variables.pyc
  creating build/bdist.linux-x86_64/egg/EGG-INFO
  copying TFLearn.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying TFLearn.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying TFLearn.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying TFLearn.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying TFLearn.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  zip_safe flag not set; analyzing archive contents...
  creating 'dist/TFLearn-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
  removing 'build/bdist.linux-x86_64/egg' (and everything under it)
  Processing TFLearn-0.1-py2.7.egg
  Removing /usr/local/lib/python2.7/dist-packages/TFLearn-0.1-py2.7.egg
  Copying TFLearn-0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  TFLearn 0.1 is already the active version in easy-install.pth

  Installed /usr/local/lib/python2.7/dist-packages/TFLearn-0.1-py2.7.egg
  Processing dependencies for TFLearn==0.1
  Searching for Pillow
  Reading https://pypi.python.org/simple/Pillow/
  Best match: Pillow 3.2.0
  Downloading https://pypi.python.org/packages/e2/af/0a3981fffc5cd43078eb8b1057702e0dd2d5771e5aaa36cbd140e32f8473/Pillow-3.2.0.tar.gz#md5=7cfd093c11205d9e2ebe3c51dfcad510
  Processing Pillow-3.2.0.tar.gz
  Writing /tmp/easy_install-uMqe0s/Pillow-3.2.0/setup.cfg
  Running Pillow-3.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uMqe0s/Pillow-3.2.0/egg-dist-tmp-PNQLRN
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  Traceback (most recent call last):
    File "setup.py", line 32, in <module>
      'AI'
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
      self.do_egg_install()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
      cmd.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 391, in run
      self.easy_install(spec, not self.no_deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 621, in easy_install
      return self.install_item(None, spec, tmpdir, deps, True)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in install_item
      self.process_distribution(spec, dist, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 717, in process_distribution
      [requirement], self.local_index, self.easy_install
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 640, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 670, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 850, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1064, in run_setup
      run_setup(setup_script, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
      raise
    File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
      DirectorySandbox(setup_dir).run(runner)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
      return func()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
      _execfile(setup_script, ns)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-uMqe0s/Pillow-3.2.0/setup.py", line 767, in <module>
      
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
      cmd = self.call_command('install_lib', warn_dir=0)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
      self.run_command(cmdname)

    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 10, in run
      self.build()
    File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
      self.run_command('build_ext')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/easy_install-uMqe0s/Pillow-3.2.0/setup.py", line 512, in build_extensions
      
  ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

  ```

**Comment by aymericdamien** [comment]
What version of Ubuntu are you using?
From the error message you sent, it seems that installing Pillow has issues. Can you clear pip cache and try to install Pillow:
```
rm -rf ~/.cache/pip
pip uninstall pillow
pip install pillow
pip install git+https://github.com/tflearn/tflearn.git
```
