### ISSUE TITLE
Basic example "use_hdf5.py" gets FileNotFoundError

### ISSUE THREAD

**Issue by EricPerbos** [tflearn/tflearn#670]
When running "tflearn/examples/basics/use_hdf5.py", I get the error below:

```
Traceback (most recent call last):
  File ".\use_hdf5_1.py", line 22, in <module>
    (X, Y), (X_test, Y_test) = cifar10.load_data()
  File "C:\Anaconda3\lib\site-packages\tflearn\datasets\cifar10.py", line 34, in load_data
    data, labels = load_batch(fpath)
  File "C:\Anaconda3\lib\site-packages\tflearn\datasets\cifar10.py", line 60, in load_batch
    with open(fpath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cifar-10-batches-py\\cifar-10-batches-py\\cifar-10-batches-py\\data_batch_1'
```

I think it's related to a typo in "tflearn/tflearn/datasets/cifar10.py", will try to create a PR next.

**Comment by EricPerbos** [comment]
PR created here: https://github.com/tflearn/tflearn/issues/671
