### ISSUE TITLE
failed to run the  reinforcement_learning example

### ISSUE THREAD

**Issue by windog18** [tflearn/tflearn#677]
I was trying to run the atari_1step_qlearning.py ,but I got an exception below:

`Traceback (most recent call last):
  File "./qLearning_test.py", line 463, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./qLearning_test.py", line 458, in main
    evaluation(session, graph_ops, saver)
  File "./qLearning_test.py", line 441, in evaluation
    monitor_env.render()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 157, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 287, in _render
    return self.env.render(mode, close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 157, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 287, in _render
    return self.env.render(mode, close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 157, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/atari/atari_env.py", line 119, in _render
    from gym.envs.classic_control import rendering
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 1817, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 505, in __init__
    config = screen.get_best_config(template_config)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/base.py", line 161, in get_best_config
    configs = self.get_matching_configs(template)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/xlib.py", line 179, in get_matching_configs
    configs = template.match(canvas)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/xlib.py", line 29, in match
    have_13 = info.have_version(1, 3)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/glx_info.py", line 89, in have_version
    client = [int(i) for i in client_version.split('.')]
ValueError: invalid literal for int() with base 10: 'None'`

I was trying to find if something wrong with my pyglet and gym.
So I wrote a code like below:
`import gym
import tensorflow as tf
from gym import envs
import numpy as np
import tflearn

env = gym.make('CartPole-v0')
env.reset()
reward_sum = 0
random_episodes = 0
while random_episodes < 100:
    env.render()
    observation, reward, done, _ = env.step(np.random.randint(0,2))
    reward_sum += reward
    if done:
        random_episodes += 1
        print("Reward for this episode was:",reward_sum)
`
It got the some error unless I comment the (import tflearn)
Anyone meet the some error like me ?

**Comment by FarshadKoohifar** [comment]
The same here. Is there any update on this?
```

Traceback (most recent call last):
  File "/root/repos/sc2/farshadTensor/tfLearnGym.py", line 465, in <module>
    tf.app.run()
  File "/root/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/repos/sc2/farshadTensor/tfLearnGym.py", line 462, in main
    train(session, graph_ops, num_actions, saver)
  File "/root/repos/sc2/farshadTensor/tfLearnGym.py", line 411, in train
    env.render()
  File "/root/tensorflow/local/lib/python2.7/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/root/tensorflow/local/lib/python2.7/site-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/root/tensorflow/local/lib/python2.7/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/root/tensorflow/local/lib/python2.7/site-packages/gym/envs/atari/atari_env.py", line 117, in _render
    from gym.envs.classic_control import rendering
  File "/root/tensorflow/local/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 236, in <module>
    import pyglet.window
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1817, in <module>
    gl._create_shadow_window()
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 505, in __init__
    config = screen.get_best_config(template_config)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/canvas/base.py", line 161, in get_best_config
    configs = self.get_matching_configs(template)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/canvas/xlib.py", line 179, in get_matching_configs
    configs = template.match(canvas)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/gl/xlib.py", line 29, in match
    have_13 = info.have_version(1, 3)
  File "/root/tensorflow/local/lib/python2.7/site-packages/pyglet/gl/glx_info.py", line 89, in have_version
    client = [int(i) for i in client_version.split('.')]
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by Faizy51** [comment]
I have the same error.
Yes the tflearn import statements are conflicting with the render() function somehow.
If i comment out tflearn import statements, render() works, else it gives the following error.

`Traceback (most recent call last):
  File "C:\Users\Faizy\Downloads\openai\cartpole.py", line 26, in <module>
    envr.render()
  File "c:\users\faizy\downloads\version-control\gym\gym\core.py", line 243, in render
    return self.env.render(mode)
  File "c:\users\faizy\downloads\version-control\gym\gym\envs\classic_control\cartpole.py", line 107, in render
    self.viewer = rendering.Viewer(screen_width, screen_height)
  File "c:\users\faizy\downloads\version-control\gym\gym\envs\classic_control\rendering.py", line 51, in __init__
    self.window = pyglet.window.Window(width=width, height=height, display=display)
  File "C:\Users\Faizy\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 504, in __init__
    screen = display.get_default_screen()
  File "C:\Users\Faizy\Anaconda3\lib\site-packages\pyglet\canvas\base.py", line 73, in get_default_screen
    return self.get_screens()[0]
  File "C:\Users\Faizy\Anaconda3\lib\site-packages\pyglet\canvas\base.py", line 65, in get_screens
    raise NotImplementedError('abstract')    
NotImplementedError: abstract
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x00000175F8F75198>>
Traceback (most recent call last):
  File "c:\users\faizy\downloads\version-control\gym\gym\envs\classic_control\rendering.py", line 143, in __del__
    self.close()
  File "c:\users\faizy\downloads\version-control\gym\gym\envs\classic_control\rendering.py", line 62, in close
    self.window.close()
AttributeError: 'Viewer' object has no attribute 'window'`
