### ISSUE TITLE
Adding LSTM Layer to AC3 Tutorial

### ISSUE THREAD

**Issue by maxss280** [tflearn/tflearn#684]
I'm trying to add a Basic LSTM layer after the conv2d layers on the AC3 demo but I get 

```
[2017-03-27 14:00:40,527] Making new env: MsPacman-v0
Traceback (most recent call last):
  File "A3C.py", line 462, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "A3C.py", line 453, in main
    graph_ops = build_graph(num_actions)
  File "A3C.py", line 310, in build_graph
    action_repeat=action_repeat)
  File "A3C.py", line 102, in build_dqn
    net = tflearn.lstm(net, 64)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/layers/recurrent.py", line 224, in lstm
    scope=scope, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/layers/recurrent.py", line 67, in _rnn_template
    sequence_length=sequence_length)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/layers/recurrent.py", line 520, in __call__
    self.reuse)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/layers/recurrent.py", line 724, in _linear
    "Linear is expecting 2D arguments: %s" % str(shapes))
ValueError: Linear is expecting 2D arguments: [[None, 11, 64], [None, 64]]

```

All I added was the tflearn.lstm(net, 64). So I think I may be missing something on how to properly call the LSTM Layer?

```
def build_dqn(num_actions, action_repeat):
    """
    Building a DQN.
    """
    inputs = tf.placeholder(tf.float32, [None, action_repeat, 84, 84])
    # Inputs shape: [batch, channel, height, width] need to be changed into
    # shape [batch, height, width, channel]
    net = tf.transpose(inputs, [0, 2, 3, 1])
    net = tflearn.conv_2d(net, 32, 8, strides=4, activation='elu')
    net = tflearn.conv_2d(net, 64, 4, strides=2, activation='elu')
    net = tflearn.lstm(net, 64)
    net = tflearn.fully_connected(net, 256, activation='elu')
    q_values = tflearn.fully_connected(net, num_actions)
    return inputs, q_values

```

**Comment by aymericdamien** [comment]
The problem is that convolution layer returns a 4-D tensor [batch, height, width, in_channels], while the LSTM layer expect a 3-D tensor as input [batch, timesteps, features], so depending on what you are trying to achieve, you may need to reshape your tensor accordingly.
