### ISSUE TITLE
ValueError: Shapes X and X' not compatible

### ISSUE THREAD

**Issue by palashd11** [tflearn/tflearn#690]
HI, I'm trying to run this model using tflearn, but it keeps throwing an error. I have shown the error message down below? What is the issue?

The model is upscaling images using conv_2d_transpose multiple times.

- the input is a numpy array of images
- the labels are also numpy arrays of images
- all images are grayscale
- input image size : (46,51)
- label image size is 8 times the above : (368,408)
- the dataset has 73 images
- i have printed all the shapes in the output

Thanks

```python
import numpy as np
import tensorflow as tf
import tflearn

#epoch=10
#batch_size=73

dataset_lr_3D=np.load('dataset_hr_3d.npy')
print 'dataset_hr_3d.npy :', dataset_lr_3D.shape

dataset_hr_3D=np.load('dataset_lr_3d.npy')
print 'dataset_lr_3d.npy:', dataset_hr_3D.shape


input_layer_2=tflearn.layers.core.input_data(shape=[None, 46, 51, 1])
print "input_layer_2 :" , input_layer_2.shape
conv1=tflearn.layers.conv.conv_2d(input_layer_2,64,5,activation='prelu')
print "conv1 :" , conv1.shape
deconv2=tflearn.layers.conv.conv_2d_transpose(conv1,32,5,[92,102],activation='prelu')
print "deconv2 :" , deconv2.shape
deconv3=tflearn.layers.conv.conv_2d_transpose(deconv2,32,5,[184,204],activation='prelu')
print "deconv3 :" , deconv3.shape
deconv4=tflearn.layers.conv.conv_2d_transpose(deconv3,32,5,[368,408],activation='prelu')
print "deconv4 :" , deconv4.shape
conv5=tflearn.layers.conv.conv_2d(deconv4,1,5,activation='prelu')
print "conv5 :" , conv5.shape

network=tflearn.regression(conv5, optimizer='SGD',loss='mean_square')

model=tflearn.DNN(network)

model.fit(dataset_lr_3D,dataset_hr_3D)
model.save("model.tfl")
print("Network trained and saved as model.tfl!")
```
OUTPUT:
```python
dataset_hr_3d.npy : (73, 368, 408)
dataset_lr_3d.npy: (73, 46, 51)
input_layer_2 : (?, 46, 51, 1)
conv1 : (?, 46, 51, 64)
deconv2 : (?, 92, 102, 32)
deconv3 : (?, 184, 204, 32)
deconv4 : (?, 368, 408, 32)
conv5 : (?, 368, 408, 1)
Traceback (most recent call last):

  File "<ipython-input-38-7665cc8991e1>", line 1, in <module>
    runfile('/home/iki/Desktop/code/ms-net.py', wdir='/home/iki/Desktop/code')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/iki/Desktop/code/ms-net.py", line 37, in <module>
    model=tflearn.DNN(network)

  File "/home/iki/.local/lib/python2.7/site-packages/tflearn/models/dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)

  File "/home/iki/.local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 131, in __init__
    clip_gradients)

  File "/home/iki/.local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 655, in initialize_training_ops
    self.grad = tf.gradients(total_loss, self.train_vars)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 500, in gradients
    in_grad.set_shape(t_in.get_shape())

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 425, in set_shape
    self._shape = self._shape.merge_with(shape)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 585, in merge_with
    (self, other))

ValueError: Shapes (?, 368, 408, 32) and (?, 368, 204, 32) are not compatible

```

**Comment by palashd11** [comment]
the problem was solved using 'strides=[1,2,2,1] in the arguments for the conv_2d_transpose layers.
