### ISSUE TITLE
'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by weiryu** [tflearn/tflearn#698]
I am using tensorflo1.0 and today I install tflearn0.3 by pip. 
However when I wanted to use tflearn ,I got  the following error message.Is there anyone can help me to fix this problem?Thank you for your help.
>>> import tflearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tflearn/__init__.py", line 4, in <module>
    from . import config
  File "tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.numpy_io import numpy_input_fn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/numpy_io.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.queues import feeding_functions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.tensorflow_dataframe import TensorFlowDataFrame
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/tensorflow_dataframe.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.transforms import in_memory_source
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/transforms/in_memory_source.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.queues import feeding_functions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/queues/feeding_functions.py", line 38, in <module>
    import pandas as pd
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 44, in <module>
    from pandas.io.api import *
  File "/usr/lib/python2.7/dist-packages/pandas/io/api.py", line 10, in <module>
    from pandas.io.html import read_html
  File "/usr/lib/python2.7/dist-packages/pandas/io/html.py", line 25, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by weiryu** [comment]
I solve this problem by using：
sudo pip install --upgrade beautifulsoup4
sudo pip install --upgrade html5lib
sudo pip install spry

**Comment by shibonskaria** [comment]
@weiryu Thank you very much. This solved my issue.
