### ISSUE TITLE
Loading network trained on distributed cluster error

### ISSUE THREAD

**Issue by Noahyt** [tflearn/tflearn#706]
I am trying to train my network on a distributed cluster (slurm).  I then want to be able to load the trained network on 

I have tried model.save and model.load commands on my local machine and both work without a problem.  

However when I try to load the files saved from the cluster computers, I get the following error

```
2017-04-11 15:36:51.658158: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Conv2D/W/Adam not found in checkpoint
2017-04-11 15:36:51.658157: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Conv2D/W/Adam_1 not found in checkpoint
2017-04-11 15:36:51.659732: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Conv2D/b/Adam_1 not found in checkpoint
2017-04-11 15:36:51.666930: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Conv2D/b/Adam not found in checkpoint
2017-04-11 15:36:51.666954: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected/W/Adam not found in checkpoint
2017-04-11 15:36:51.668078: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected/W/Adam_1 not found in checkpoint
2017-04-11 15:36:51.669157: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected/b/Adam not found in checkpoint
2017-04-11 15:36:51.669297: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected/b/Adam_1 not found in checkpoint
2017-04-11 15:36:51.670707: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected_1/W/Adam not found in checkpoint
2017-04-11 15:36:51.671790: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected_1/W/Adam_1 not found in checkpoint
2017-04-11 15:36:51.673744: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected_1/b/Adam not found in checkpoint
2017-04-11 15:36:51.673948: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key FullyConnected_1/b/Adam_1 not found in checkpoint
2017-04-11 15:36:51.675278: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MeanSquare/Mean/moving_avg not found in checkpoint
Traceback (most recent call last):
  File "NN_TEST.py", line 25, in <module>
    model.load("conv_test_final.tfl")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tflearn/models/dnn.py", line 278, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 449, in restore
    self.restorer.restore(self.session, model_file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Conv2D/W/Adam_1 not found in checkpoint
	 [[Node: save_1/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_5/tensor_names, save_1/RestoreV2_5/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_5', defined at:
  File "NN_TEST.py", line 22, in <module>
    model = tflearn.DNN(network, tensorboard_dir='output_conv/', tensorboard_verbose=3, checkpoint_path='output_conv/conv_test')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tflearn/models/dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 145, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key Conv2D/W/Adam_1 not found in checkpoint
	 [[Node: save_1/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_5/tensor_names, save_1/RestoreV2_5/shape_and_slices)]]


```

I noticed that when I ran model.save on my local machine it was something like:

```
"model_checkpoint_path: "/Users/Noah/ .... /conv_test_final.tfl"
all_model_checkpoint_paths: "/Users/Noah/ ... /conv_test_final.tfl"
```

wheras the checkpoint file from the cluster training is:

```
model_checkpoint_path: "conv_test_final.tfl"
all_model_checkpoint_paths: "conv_test_final.tfl"
```

I tried swapping out the one checkpoint file for the other and the new error looks the same:

`NotFoundError (see above for traceback): Key Conv2D/W/Adam not found in checkpoint
	 [[Node: save_1/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_4/tensor_names, save_1/RestoreV2_4/shape_and_slices)]]
`

**Comment by aymericdamien** [comment]
Seems like it is trying to restore Adam-specific variables. Can you try to load the weights only? `model.load(PATH, weights_only=True)`

**Comment by Noahyt** [comment]
Loading weights only worked for me.  

Although this fixed my problem, I am curious as to why the model.save would not save all relevant parameters to be later loaded.
