### ISSUE TITLE
How to use RNN by gru

### ISSUE THREAD

**Issue by shiratsu** [tflearn/tflearn#719]
Hi.
I try to use RNN by tflearn.

I can use tflearn.ltsm.
However,if i tried to use tflearn.gru,some error would happen.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 589, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("GRU/GRU/GRUCell/Gates/add:0", shape=(?, 12), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gru_tflearn_sample.py", line 62, in <module>
    net = tflearn.gru(net, n_units=6)
  File "/usr/local/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 294, in gru
    scope=scope, name=name)
  File "/usr/local/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 67, in _rnn_template
    sequence_length=sequence_length)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/usr/local/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 601, in __call__
    self.trainable, self.restore, self.reuse))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1216, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3426, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
```

My code is here.
```
# coding: UTF-8

import numpy as np
import pandas as pd
import tflearn
import matplotlib.pyplot as plt
import random
import sys # モジュール属性 argv を取得するため

random.seed(0)
np.random.seed(0)

argvs = sys.argv  # コマンドライン引数を格納したリストの取得

dataframe = pd.read_csv(argvs[1],
        usecols=[1],
        engine='python',
        skipfooter=3)
dataset = dataframe.values
dataset = dataset.astype('float32')

print("正規化前")
print(dataset)

dataset -= np.min(np.abs(dataset))
dataset /= np.max(np.abs(dataset))
print("正規化後")
print(dataset)

def create_dataset(dataset, steps_of_history, steps_in_future):
    X, Y = [], []
    for i in range(0, len(dataset)-steps_of_history, steps_in_future):
        X.append(dataset[i:i+steps_of_history])
        Y.append(dataset[i + steps_of_history])
    X = np.reshape(np.array(X), [-1, steps_of_history, 1])
    Y = np.reshape(np.array(Y), [-1, 1])
    return X, Y

def split_data(x, y, test_size=0.1):
    pos = round(len(x) * (1 - test_size))
    trainX, trainY = x[:pos], y[:pos]
    testX, testY   = x[pos:], y[pos:]
    return trainX, trainY, testX, testY

steps_of_history = 3
steps_in_future = 1

X, Y = create_dataset(dataset, steps_of_history, steps_in_future)

trainX, trainY, testX, testY = split_data(X, Y, 0.4)

# 実際に訓練してみる
net = tflearn.input_data(shape=[None, steps_of_history, 1])
net = tflearn.gru(net, n_units=6)
net = tflearn.fully_connected(net, 1, activation='linear')
net = tflearn.regression(net, optimizer='adam', learning_rate=0.001,
        loss='mean_square')

model = tflearn.DNN(net, tensorboard_verbose=0)
model.fit(trainX, trainY, validation_set=0.1, batch_size=1, n_epoch=150)


# 結果の可視化
train_predict = model.predict(trainX)
test_predict = model.predict(testX)

train_predict_plot = np.empty_like(dataset)
train_predict_plot[:, :] = np.nan
train_predict_plot[steps_of_history:len(train_predict)+steps_of_history, :] = \
        train_predict

test_predict_plot = np.empty_like(dataset)
test_predict_plot[:, :] = np.nan
test_predict_plot[len(train_predict)+steps_of_history:len(dataset), :] = \
        test_predict

plt.figure(figsize=(8, 8))
plt.title('History={} Future={}'.format(steps_of_history, steps_in_future))
plt.plot(dataset)
plt.plot(train_predict_plot)
plt.plot(test_predict_plot)
plt.savefig('test.png')

```

What is this problem?

**Comment by shiratsu** [comment]
I can resolve by myself.

**Comment by CaptainQiu** [comment]
hi , how did you solve this problem

**Comment by CaptainQiu** [comment]
I solved it.
tflearn is using an older version of tensorflow .
the older api 'tf.split(axis, num_or_size_splits, value)'
now is 'tf.split(value, num_or_size_splits, axis)'
so you should go to    '/usr/local/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 601' find the function 'array_ops.split(....)'  and change the location of 'value' and 'axis'
