### ISSUE TITLE
Time distribute layer is broken

### ISSUE THREAD

**Issue by Jimsparkle** [tflearn/tflearn#733]
input data should be (num, timestep, width, height, 1)
output data should be (num, timestep, 4)

and when I run

`    network = input_data([None, timestep, width, height, 1], name='input')

    network = reshape(network, [-1, width, height, 1])

    network = conv_2d(network, 96, 11, strides=4, activation='relu')
    network = max_pool_2d(network, 3, strides=2)
    network = local_response_normalization(network)
    network = conv_2d(network, 256, 5, activation='relu')
    network = max_pool_2d(network, 3, strides=2)
    network = local_response_normalization(network)
    network = conv_2d(network, 384, 3, activation='relu')
    network = conv_2d(network, 384, 3, activation='relu')
    network = conv_2d(network, 256, 3, activation='relu')
    network = max_pool_2d(network, 3, strides=2)
    network = local_response_normalization(network)
    network = flatten(network)
    image_size = int(network.shape[1])
    network = reshape(network, [-1, timestep, image_size])
    network = lstm(network, 128, dropout=0.1, return_seq=True)
    network = lstm(network, 128, dropout=0.1, return_seq=True)
    network = time_distributed(network, fully_connected, [4])
    network = softmax(network)
    network = reshape(network, [-1, timestep, 4])
    network = regression(network, optimizer='momentum',
                         loss='categorical_crossentropy',
                         learning_rate=lr, name='targets')
    model = tflearn.DNN(network, checkpoint_path='model_alexnet',
                        max_checkpoints=1, tensorboard_verbose=2, tensorboard_dir='log')`

The following error shown.

`TypeError: Expected int32, got <map object at 0x000001FE3B460F60> of type 'map' instead.`

**Comment by kristafari** [comment]
I think i also have this issue:
`
import tflearn
from tflearn.layers.core import input_data
from tflearn.layers.conv import conv_2d
net = input_data(shape=[None, 100, 100, 20, 1], name='input')
net = tflearn.time_distributed(net, conv_2d, [4, 1, 1, 'same', 'linear', True, 'Xavier'])
`

Output:
`
  File "test_tflearn.py", line 7, in <module>
    net = tflearn.time_distributed(net, conv_2d, [4, 1, 1, 'same', 'linear', True, 'Xavier'])
  File "python3.5/site-packages/tflearn/layers/core.py", line 647, in time_distributed
    return tf.concat(x, 1)
  File "python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1031, in concat
    return identity(values[0], name=scope)
  File "python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
  File "python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "python3.5/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <map object at 0x7f033963deb8>
`

Any workarounds?

**Comment by aymericdamien** [comment]
Please make sure you are using the latest version of TFLearn: `pip install git+https://github.com/tflearn/tflearn.git`, it should be working.

**Comment by kristafari** [comment]
I tried with a new virtualenv and installed a fresh tensorflow (1.1.0) and the latest tflearn and it still has the same error.


>vf new tf                                             3655ms  Fri 05 May 2017 08:02:02 PM CDT
Using base prefix '/usr'
New python executable in /home/x/.virtualenvs/tf/bin/python3
Also creating executable in /home/x/.virtualenvs/tf/bin/python
Installing setuptools, pip, wheel...done.

>pip install git+https://github.com/tflearn/tflearn.git      
Collecting git+https://github.com/tflearn/tflearn.git
  Cloning https://github.com/tflearn/tflearn.git to /tmp/pip-8jnuw5v0-build
Collecting numpy (from tflearn==0.3)
  Using cached numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: six in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from tflearn==0.3)
Collecting Pillow (from tflearn==0.3)
  Downloading Pillow-4.1.1-cp35-cp35m-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 147kB/s 
Collecting olefile (from Pillow->tflearn==0.3)
Installing collected packages: numpy, olefile, Pillow, tflearn
  Running setup.py install for tflearn ... done
Successfully installed Pillow-4.1.1 numpy-1.12.1 olefile-0.44 tflearn-0.3

>pip install tensorflow                                     
Collecting tensorflow
  Using cached tensorflow-1.1.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.10.0 in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.11.0 in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from tensorflow)
Collecting werkzeug>=0.11.10 (from tensorflow)
  Using cached Werkzeug-0.12.1-py2.py3-none-any.whl
Collecting protobuf>=3.2.0 (from tensorflow)
  Downloading protobuf-3.3.0-cp35-cp35m-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 94kB/s 
Requirement already satisfied: wheel>=0.26 in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from tensorflow)
Requirement already satisfied: setuptools in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from protobuf>=3.2.0->tensorflow)
Requirement already satisfied: packaging>=16.8 in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from setuptools->protobuf>=3.2.0->tensorflow)
Requirement already satisfied: appdirs>=1.4.0 in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from setuptools->protobuf>=3.2.0->tensorflow)
Requirement already satisfied: pyparsing in /home/x/.virtualenvs/tf/lib/python3.5/site-packages (from packaging>=16.8->setuptools->protobuf>=3.2.0->tensorflow)
Installing collected packages: werkzeug, protobuf, tensorflow
Successfully installed protobuf-3.3.0 tensorflow-1.1.0 werkzeug-0.12.1

> python -c 'import tensorflow as tf; print(tf.__version__)'
1.1.0

>python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflearn
hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!
>>> from tflearn.layers.core import input_data
>>> from tflearn.layers.conv import conv_2d
>>> net = input_data(shape=[None, 100, 100, 20, 1], name='input')
>>> net = tflearn.time_distributed(net, conv_2d, [4, 1, 1, 'same', 'linear', True, 'Xavier'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tflearn/layers/core.py", line 647, in time_distributed
    return tf.concat(x, 1)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1031, in concat
    return identity(values[0], name=scope)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 444, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/x/.virtualenvs/tf/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <map object at 0x7f03d71dca90>
>>>

**Comment by Jimsparkle** [comment]
I just make a pull request (#767) to solve this problem. Please review it :)
