### ISSUE TITLE
Curses calls breaks in linux

### ISSUE THREAD

**Issue by Xiaoming94** [tflearn/tflearn#739]
the line `curses.tigetstr('cvvis').decode()` gives the following error message:
```
Traceback (most recent call last):
  File "tflearn_rnn.py", line 347, in <module>
    model = train_model(model, hyp, this_run_id, log_run, perflog)
  File "tflearn_rnn.py", line 220, in train_model
    callbacks=monitorCallback)
  File "/home/xiaoming/.local/lib/python3.6/site-packages/tflearn/models/dnn.py", line 215, in fit
    callbacks=callbacks)
  File "/home/xiaoming/.local/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 349, in fit
    caller.on_train_end(self.training_state)
  File "/home/xiaoming/.local/lib/python3.6/site-packages/tflearn/callbacks.py", line 84, in on_train_end
    callback.on_train_end(training_state)
  File "/home/xiaoming/.local/lib/python3.6/site-packages/tflearn/callbacks.py", line 183, in on_train_end
    sys.stdout.write(curses.tigetstr('cvvis').decode())
AttributeError: 'NoneType' object has no attribute 'decode'
```
I am on Arch linux with python 3.6.1

**Comment by willduan** [comment]
Which file has made the mistake?
