### ISSUE TITLE
Nan in summary histogram?

### ISSUE THREAD

**Issue by Noahyt** [tflearn/tflearn#740]
Trying to train cnn. 

I saw that some others had this issue in TensorFlow and solved it by changing the /epsilon parameter of the Adam trainer, but this did not fix my error. 

```
Caused by op u'Conv2D/W/Gradients', defined at:
  File "./TFLEARN_CONV.py", line 82, in <module>
    model = tflearn.DNN(network, tensorboard_dir='output/', tensorboard_verbose=3, checkpoint_path='output')
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/models/dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 131, in __init__
    clip_gradients)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 671, in initialize_training_ops
    self.create_summaries(tensorboard_verbose)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 865, in create_summaries
    summarize_gradients(self.grad, summ_collection)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/helpers/summarizer.py", line 75, in summarize_gradients
    summaries.add_gradients_summary(grads, "", "", summary_collection)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/summaries.py", line 132, in add_gradients_summary
    collection_key))
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/summaries.py", line 44, in get_summary
    summ = tf.summary.histogram(tag, value)
  File "/share/sw/free/tensorflow.1/1.1.0/lib/python2.7/site-packages/tensorflow/python/summary/summary.py", line 209, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/share/sw/free/tensorflow.1/1.1.0/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "/share/sw/free/tensorflow.1/1.1.0/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/share/sw/free/tensorflow.1/1.1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/share/sw/free/tensorflow.1/1.1.0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: Conv2D/W/Gradients
	 [[Node: Conv2D/W/Gradients = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](Conv2D/W/Gradients/tag, Adam/clip_by_global_norm/Adam/clip_by_global_norm/_0/_105)]]

Exception in thread Thread-22 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/share/sw/free/anaconda/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/share/sw/free/anaconda/anaconda2/lib/python2.7/threading.py", line 754, in run
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/data_flow.py", line 187, in fill_feed_dict_queue
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/data_flow.py", line 222, in retrieve_data
  File "/home/toyonaga/.local/lib/python2.7/site-packages/tflearn/utils.py", line 185, in slice_array
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "/home/toyonaga/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 410, in __getitem__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
srun: error: gpu-17-35: task 0: Exited with exit code 1
```

**Comment by Noahyt** [comment]
Solved my own problem: 
Two problems, actually. 

First, I was working with float16 type data which has been documented to cause problems in tensorflow (can't remember where I found this ...I think some stackoverflow post from 2016)

Second (and probably more importantly) my training data was not properly normalized and included a whole batch worth of images without any data.  If you're getting Nan's this means training has diverged, likely indicating a problem with training data.

So all in all my fault and not a TFlearn bug.

**Comment by supamonkey2000** [comment]
Hey Im having a similar error. What do you mean by 

> my training data was not properly normalized

I am using a csv file if it helps.

**Comment by johnprakashjoseph** [comment]
I face this problem if I open the training CSV file in some editor, modify it and then save it...Else it works perfectly fine...Advise please.

**Comment by Noahyt** [comment]
@johnprakashjoseph what sort of modifications are you doing to the file?

@supamonkey2000 -- I was working with "image"-type data and I discovered that across my training examples, some of the pixel intensities were thousands of times larger than in other images.  By normalizing the maximum intensity of each image I got a more consistent dataset that let the network learn appropriate weights.

**Comment by johnprakashjoseph** [comment]
Actually I was just running the Boston example program - regression using  tf.contrib.learn.DNNRegressor using the boston_train.csv training data. So i initially attempted a change in the label output "Medv" values.  But I noticed the moment I open the csv file with Microsoft excel or Open Office and try to save it after making data value modifications and try to run the training, i get the following error.....(Even if i change value of one label from say.... 23.8 to 23.9......a minor change..

InvalidArgumentError (see above for traceback): Nan in summary histogram for: dnn/dnn/hiddenlayer_0_activation	 [[Node: dnn/dnn/hiddenlayer_0_activation = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](dnn/dnn/hiddenlayer_0_activation/tag, dnn/hiddenlayer_0/hiddenlayer_0/Relu)]]

Obviously some data format change is causing the problem, i suspect with my limited knowledge. Please advise.

**Comment by rohit9650** [comment]
@Noahyt could you please elaborate how you normalized your dataset ,Basically at which step at different layers or just in the beginning .
It would be helpful if you give code-snippet.
My problem raised when i was following https://github.com/SaoYan/bgsCNN/ and i changed image height x width to 161 x 161, it think it has caused the problem and now i'm getting Nan ,but what is the solution ?
