### ISSUE TITLE
How to perform unsupervised pre-training with tflearn

### ISSUE THREAD

**Issue by lihengbit** [tflearn/tflearn#750]
How can I unsupervisedly train a layer of CNN with tflearn to achieve unsupervised pre-training?

**Comment by aymericdamien** [comment]
You can have a check at the auto-encoder examples: https://github.com/tflearn/tflearn/blob/master/examples/images/autoencoder.py, https://github.com/tflearn/tflearn/blob/master/examples/images/variational_autoencoder.py, the unsupervised optimization process is using the same data as input and target.

**Comment by lihengbit** [comment]
Thank you for reply. I tried both code, but same error appears:
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/models/dnn.py", line 183, in fit
    self.targets)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/utils.py", line 289, in feed_dict_builder
    feed_dict[net_inputs[i]] = x
IndexError: list index out of range

is this error of input, or of the code?

**Comment by lihengbit** [comment]
It happens when run the code model.fit(X, X, n_epoch=20, validation_set=(testX, testX),
          run_id="auto_encoder", batch_size=256)
and 
training_model.fit({'input_images': X}, {'target_images': X}, n_epoch=100,
                   validation_set=(testX, testX), batch_size=256, run_id="vae")
