### ISSUE TITLE
vgg16.tflearn loading error in vgg_network_finetuning

### ISSUE THREAD

**Issue by lihengbit** [tflearn/tflearn#755]
In vgg_network_finetuning, when I run:
model_file = os.path.join(model_path, "vgg16.tflearn")
model.load(model_file, weights_only=True)

Error appears:
Traceback (most recent call last):
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "conv2_2/b/Adam_1" not found in checkpoint files /scratch/hli17/Tensorflow/vgg16.tflearn
         [[Node: save_5/RestoreV2_53 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_5/Const_0, save_5/RestoreV2_53/tensor_names, save_5/RestoreV2_53/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/models/dnn.py", line 278, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 449, in restore
    self.restorer.restore(self.session, model_file)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "conv2_2/b/Adam_1" not found in checkpoint files /scratch/hli17/Tensorflow/vgg16.tflearn
         [[Node: save_5/RestoreV2_53 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_5/Const_0, save_5/RestoreV2_53/tensor_names, save_5/RestoreV2_53/shape_and_slices)]]

Caused by op 'save_5/RestoreV2_53', defined at:
  File "<stdin>", line 3, in <module>
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/models/dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 145, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/workspace/hli17/tmp/Anaconda4.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "conv2_2/b/Adam_1" not found in checkpoint files /scratch/hli17/Tensorflow/vgg16.tflearn
         [[Node: save_5/RestoreV2_53 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_5/Const_0, save_5/RestoreV2_53/tensor_names, save_5/RestoreV2_53/shape_and_slices)]]

**Comment by willduan** [comment]
It seems that you model defined is different from your checkpoint's model.

**Comment by lihengbit** [comment]
Thank you for helping.  This problem appear when I run the example code of vgg 16 finetuning. How can I check the defination of model in the checkpoint to address this error ?

**Comment by willduan** [comment]
This code need to have checkpoint files of vgg16 firstly, you should run vgg_network.py to generate checkpoint files. The error seems that you don't have checkpoint files.

**Comment by lihengbit** [comment]
How about the provided pre-trained vgg16.tflearn in examples, where is its checkpoint?

**Comment by CodeBag-Debashish** [comment]
HI, could you provide me some other link to download the "vgg16.tflearn" model file ?? dropbox link is not working

**Comment by yschao** [comment]
Dear:
   The "vgg16.tflearn" model file link can not access, can you share a new link?
