### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'

### ISSUE THREAD

**Issue by sean2gh** [tflearn/tflearn#787]
Using python 3.6 on a fresh install of tensorflow and tflearn

C:\Users\User\Downloads>pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-1.2.0rc2-cp36-cp36m-win_amd64.whl
Requirement already satisfied: six>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: protobuf>=3.2.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: backports.weakref==1.0rc1 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: html5lib==0.9999999 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: markdown==2.2.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: bleach==1.5.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: werkzeug>=0.11.10 in c:\programdata\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg (from protobuf>=3.2.0->tensorflow)
Installing collected packages: tensorflow
Successfully installed tensorflow-1.2.0rc2

C:\Users\User\Downloads>pip install tflearn
Collecting tflearn
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from tflearn)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from tflearn)
Requirement already satisfied: Pillow in c:\programdata\anaconda3\lib\site-packages (from tflearn)
Requirement already satisfied: olefile in c:\programdata\anaconda3\lib\site-packages (from Pillow->tflearn)
Installing collected packages: tflearn
Successfully installed tflearn-0.3.1

C:\Users\User\Downloads>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\__init__.py", line 21, in <module>
    from .layers import normalization
  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\layers\__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\layers\recurrent.py", line 8, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, \
ModuleNotFoundError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'

**Comment by aymericdamiensc** [comment]
Can you update to the latest version of TFLearn? This should be working:
`pip install git+https://github.com/tflearn/tflearn.git`

**Comment by aymericdamien** [comment]
Can you update to the latest version of TFLearn? This should be working:
`pip install git+https://github.com/tflearn/tflearn.git`

**Comment by sean2gh** [comment]
Very weird. The version of tflearn-0.3.1 on pip install tflearn gave me this error, whereas the git install you mentioned is also version 0.3.1 and did not have the same error. It is now working properly so thanks. Maybe something is wrong with the version being installed using pip?

Proceed (y/n)? y
  Successfully uninstalled tflearn-0.3.1

C:\Users\User>pip install git+https://github.com/tflearn/tflearn.git
Collecting git+https://github.com/tflearn/tflearn.git
  Cloning https://github.com/tflearn/tflearn.git to c:\users\user\appdata\local\temp\pip-_4pby_cg-build
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from tflearn==0.3.1)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from tflearn==0.3.1)
Requirement already satisfied: Pillow in c:\programdata\anaconda3\lib\site-packages (from tflearn==0.3.1)
Requirement already satisfied: olefile in c:\programdata\anaconda3\lib\site-packages (from Pillow->tflearn==0.3.1)
Installing collected packages: tflearn
  Running setup.py install for tflearn ... done
Successfully installed tflearn-0.3.1

**Comment by naimavahab** [comment]
I have tensorflow with 1.4 and tflearn with 0.3.2 .. still contrib modules of tflearn are not available

**Comment by bhagyashripachkor** [comment]
I have tensorflow with 1.5 and tflearn with 0.3.2 .. I'm getting error:-ImportError: No module named 'tensorflow.contrib.ios_examples.benchmark.benchmark.xcodeproj'. Can someone please guide me solve this error.

**Comment by hamayounahmad** [comment]
I have tensorflow with 1.4 and tflearn with 0.3.2 .. still contrib modules of tflearn are not available and I am also facing same error.

**Comment by ashifkasala** [comment]
File "/anaconda3/lib/python3.7/site-packages/tflearn/layers/recurrent.py", line 9, in <module>
    from tensorflow.python.ops.rnn import rnn_cell_impl as _rnn_cell, dynamic_rnn as _drnn, static_rnn as _rnn, bidirectional_dynamic_rnn as _brnn
ImportError: cannot import name 'rnn_cell_impl' from 'tensorflow.python.ops.rnn' (/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2.py", line 1, in <module>
    import tflearn
  File "/anaconda3/lib/python3.7/site-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/anaconda3/lib/python3.7/site-packages/tflearn/layers/__init__.py", line 11, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/anaconda3/lib/python3.7/site-packages/tflearn/layers/recurrent.py", line 13, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, static_bidirectional_rnn as _brnn
ModuleNotFoundError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'

**Comment by swimming16** [comment]
I have tensorflow with 1.13.1 and tflearn with 0.3.2，this problem has been sloved.
