### ISSUE TITLE
Cannot feed value of shape (15, 228, 228, 3) for Tensor 'InputData/X:0', which has shape '(?, 128, 128, 3)'

### ISSUE THREAD

**Issue by gukangkang** [tflearn/tflearn#791]
I am following Resnet_cifar10 example and use the code to try to solve my dataset.Now I have a problem that while begining to calculate the val accuracy rateI ,it will have this ValueError:Cannot feed value of shape (15, 228, 228, 3) for Tensor 'InputData/X:0', which has shape '(?, 128, 128, 3)'.

I set the batch size=15 ,

**Comment by gukangkang** [comment]
anyone can help me ?

**Comment by BBarbosa** [comment]
Hi @gukangkang! 
From what it looks, i think it is about your input data shape doesn't match with the network definition. I don't think the batch size would cause this error. Can you add a code snippet?

**Comment by moumine9** [comment]
From what I see here, the shape of your images doesn't match what network input requires. I suggest you to resize your images to 128x128 before feeding the network. Depending on the library you use, it might be `im.resize(128,128)` or something else. Also, one important thing I've noticed, always make sure that your images are in rgb mode (depth = 3). To verify it, randomly run ` print(im.shape) ` where `  im ` is the matrix containing your image. In a terminal you can enter ` file /path/to/your/file ` to determine all the details regarding your image.

**Comment by vaibhav-jain** [comment]
Hey Guys,
I'm trying to solve a simple ML problem with TF learn, But getting an error. Below I have added my code.

```
#!/usr/bin/env python
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tflearn

net = tflearn.input_data(shape=[None, 2]) # No of features is two
net = tflearn.fully_connected(net, 2) # No idea what the value should be
# net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net)

# Define model
model = tflearn.DNN(net)
data = [
    # Apple
    [105, 0],
    [110, 0],
    [100, 0],
    [140, 0],
    [130, 0],
    # Orange
    [150, 1],
    [155, 1],
    [160, 1],
    [170, 1],
    [190, 1],
]
labels = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

# Start training (apply gradient descent algorithm)
model.fit(data, labels, n_epoch=3, batch_size=2, show_metric=True)

pred = model.predict([[180, 0], [100, 0]])
print pred

"""
Getting error


Run id: RAATYL
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 10
Validation samples: 0
--

--
Traceback (most recent call last):
  File "./ml5.py", line 32, in <module>
    model.fit(data, labels, n_epoch=3, batch_size=2, show_metric=True)
  File "/home/prime/.virtualenvs/mllearn/local/lib/python2.7/site-packages/tflearn/models/dnn.py", line 216, in fit
    callbacks=callbacks)
  File "/home/prime/.virtualenvs/mllearn/local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 338, in fit
    show_metric)
  File "/home/prime/.virtualenvs/mllearn/local/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 817, in _train
    feed_batch)
  File "/home/prime/.virtualenvs/mllearn/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/prime/.virtualenvs/mllearn/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2,) for Tensor u'TargetsData/Y:0', which has shape '(?, 2)'
"""
```

**Comment by ksooklall** [comment]
@vaibhav-jain Your getting a shape error because your labels have shape (1, 10), but your final layer is just 2 nodes. A fix would be
```
net = tflearn.input_data(shape=[None, 2]) # No of features is two
net = tflearn.fully_connected(net, 32) # I changed the two here to 32, more nodes will capture for correlations
net = tflearn.fully_connected(net, 10, activation='softmax') # 10 to match the labels, so you can calculate your loss
net = tflearn.regression(net)
```

**Comment by dellianesh1508** [comment]
i have some issue some one help me
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

import tensorflow as tf
tf.reset_default_graph()

convnet = input_data(shape=[IMG_SIZE, IMG_SIZE, 3], name='input')
print(convnet)

convnet = conv_2d(convnet, 32, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)
convnet = conv_2d(convnet, 64, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)

convnet = conv_2d(convnet, 128, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)

convnet = conv_2d(convnet, 256, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)

convnet = conv_2d(convnet, 128, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)

convnet = conv_2d(convnet, 64, 2, activation='relu')
print(convnet)
convnet = max_pool_2d(convnet, 2)
print(convnet)

convnet = fully_connected(convnet, 1024, activation='relu')
print(convnet)
convnet = dropout(convnet, 0.5)
print(convnet)

convnet = fully_connected(convnet, 30, activation='softmax')
print(convnet)
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')
print(convnet)

model = tflearn.DNN(convnet, tensorboard_dir='log3')


Error
C:\Users\Delli\Anaconda3\lib\site-packages\tflearn\models\dnn.py in fit(self, X_inputs, Y_targets, n_epoch, validation_set, show_metric, batch_size, shuffle, snapshot_epoch, snapshot_step, excl_trainops, validation_batch_size, run_id, callbacks)
    214                          excl_trainops=excl_trainops,
    215                          run_id=run_id,
--> 216                          callbacks=callbacks)
    217 
    218     def fit_batch(self, X_inputs, Y_targets):

C:\Users\Delli\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py in fit(self, feed_dicts, n_epoch, val_feed_dicts, show_metric, snapshot_step, snapshot_epoch, shuffle_all, dprep_dict, daug_dict, excl_trainops, run_id, callbacks)
    337                                                        (bool(self.best_checkpoint_path) | snapshot_epoch),
    338                                                        snapshot_step,
--> 339                                                        show_metric)
    340 
    341                             # Update training state

C:\Users\Delli\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py in _train(self, training_step, snapshot_epoch, snapshot_step, show_metric)
    816         tflearn.is_training(True, session=self.session)
    817         _, train_summ_str = self.session.run([self.train, self.summ_op],
--> 818                                              feed_batch)
    819 
    820         # Retrieve loss value from summary string

C:\Users\Delli\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\Delli\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    973                 'Cannot feed value of shape %r for Tensor %r, '
    974                 'which has shape %r'
--> 975                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
    976           if not self.graph.is_feedable(subfeed_t):
    977             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (64, 128, 128, 1) for Tensor 'input/X:0', which has shape '(?, 128, 128, 3)'

**Comment by xDarkLemon** [comment]
@dellianesh1508 Hello, have you solved this problem? I got the same error when using the method "fit".
