### ISSUE TITLE
ImportError: cannot import name 'remove_undocumented'

### ISSUE THREAD

**Issue by litingsjj** [tflearn/tflearn#811]
When I import tflearn, there have problem like that:

import tflearn

Traceback (most recent call last):

  File "<ipython-input-2-1dcc0aeffa10>", line 1, in <module>
    import tflearn

  File "/home/lt/anaconda3/lib/python3.5/site-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization

  File "/home/lt/anaconda3/lib/python3.5/site-packages/tflearn/layers/__init__.py", line 11, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \

  File "/home/lt/anaconda3/lib/python3.5/site-packages/tflearn/layers/recurrent.py", line 13, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, static_bidirectional_rnn as _brnn

  File "/home/lt/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell

  File "/home/lt/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 49, in <module>
    from tensorflow.python.util.all_util import remove_undocumented

ImportError: cannot import name 'remove_undocumented'

**Comment by litingsjj** [comment]
I don't know how to solve it. Someone can help me? thanks!

**Comment by willduan** [comment]
which is your tensorflow version ? 
Please try to install tensorflow version 1.0.0
