### ISSUE TITLE
When are we getting a Imagenet dataset?

### ISSUE THREAD

**Issue by dlmacedo** [tflearn/tflearn#86]
Dear friends,

I do love the tflearn project.

Does anybody know if an ImageNet dataset loader is scheduled to be released?

I am asking this because Imagenet is the de facto standard dataset to image in deep learning research and it would be very nice to have it supported by tflearn.

Thanks,

David

**Comment by aymericdamien** [comment]
Yes, it is planned to add a 'model' section after TFLearn v0.2 release. I think it can benefit many people.

**Comment by dlmacedo** [comment]
I think "models" section should be independent of an another session called "datasets" where we should have the loaders of the main datasets like MNIST, ImageNet, CiFAR-10, etc...

In the *models" session we should have AlexNet, VGG, NIN, Inception, ResNet, etc...

Therefore, we could train and test a model in a new dataset just changing one line of code...

**Comment by dlmacedo** [comment]
In my dream, in the main python file with one line we load the dataset and with another line we load the model, then we 
write the trais and test code...

**Comment by 2PacIsAlive** [comment]
I have found that it is difficult to process imagenet with tflearn, as the dataset is >1TB. In addition, some of the imagenet files are truncated, which causes the PIL image loader used by tflearn to crash. 

Most of the image loading examples I have seen use the `tflearn.data_utils.build_image_dataset_from_dir` function, though perhaps there is a better way of doing this..? 

There seem to be more efficient and fault tolerant ways of loading and processing large image datasets using tensorflow - it would be invaluable to have a built in tflearn utility that took care of the entire imagenet process (untarring the individual synsets, building a wordnet id --> real word mapping, loading potentially damaged images, etc.).

**Comment by aymericdamien** [comment]
Yes, I just release yesterday a new way to build hdf5 datasets, that can handle millions of examples, but it may be very slow to build a hdf5 dataset for the entire imagenet (https://github.com/tflearn/tflearn/blob/master/tflearn/data_utils.py#L278).
Also this is planned to be finished soon:
- Loading images directly from files (or url) through feed_dict, so it should be easy for you to train Imagenet directly loading images from files,
- A pre-trained VGG-16/19 imagenet model weights for finetuning purposes.

**Comment by 2PacIsAlive** [comment]
Fantastic! The new way to build hdf5 datasets worked out for my very large set of images. How do I go about using these files with tflearn?

First I make sure the datasets have been created properly:
```
import h5py
with h5py.File('dataset.h5', 'r') as hf:
     print hf.keys()
```
Outputs: 
```
[u'X', u'Y']
```
So I try
```
with h5py.File('dataset.h5', 'r') as hf:
     X = hf.get('X')  # I also tried u'X' and u'Y'
     Y = hf.get('Y') 
```

However when running model.fit I get this error
```
ValueError: Not a dataset (Not a dataset)
```
I also tried using `hf.get().value` and `numpy.array(hf.get())`, but these methods seem to defeat the purpose of the hdf5 file.. and throw memory errors.

**Comment by aymericdamien** [comment]
HDF5 is pretty easy to use, you can just use it like that:
```
h5f = h5py.File('dataset.h5', 'r')
X = h5f['X']
Y = h5f['Y']

net = ...

model = tflearn.DNN(net)
model.fit(X, Y)

h5f.close()
```

**Comment by aymericdamien** [comment]
You can try this new image_preloader:
https://github.com/tflearn/tflearn/blob/master/tflearn/data_utils.py#L399
```
X, Y = tflearn.data_utils.image_preloader('YOUR_FILE', image_shape=(256, 256))
```

It hasn't been tested yet, but it should works. Note that it only can load images from disk now, but it will handle URLs as well pretty soon, just need few changes.

**Comment by 2PacIsAlive** [comment]
I am having some trouble using the image_preloader. 
My code is set up as follows: 
```
X, Y = tflearn.data_utils.image_preloader(target_path='images/', 
                                          image_shape=(256, 256),
                                          mode='folder',
                                          categorical_labels=True,
                                          normalize=True,
                                          grayscale=False,
                                          files_extension=['.jpg'])
network = ...

model = tflearn.DNN(network, checkpoint_path='preload_test_model',
                    max_checkpoints=1, tensorboard_verbose=3)
model.fit(X, Y, n_epoch=1, validation_set=0.1, shuffle=True,
          show_metric=True, batch_size=32, snapshot_step=None,
          snapshot_epoch=True, run_id='preload_test')
```
The `images/` directory contains 10 sub-directories of images, and each sub-directory is labeled with an integer id.
When I try to run this code, I get the following error:
```
Training samples: 20181
Validation samples: 2243
--
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/tflearn/data_flow.py", line 183, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "build/bdist.linux-x86_64/egg/tflearn/data_flow.py", line 218, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "build/bdist.linux-x86_64/egg/tflearn/utils.py", line 166, in slice_array
    return X[start]
  File "build/bdist.linux-x86_64/egg/tflearn/data_utils.py", line 722, in __getitem__
    return self.function(self.array[id])
TypeError: only integer arrays with one element can be converted to an index
```
Is there something I am doing wrong in setting up the preloader? Thanks so much for your help!

**Comment by aymericdamien** [comment]
Could you try to print your 'X' to see that the data have no issue?
try this for example:
```
print X[0]
```

**Comment by 2PacIsAlive** [comment]
@aymericdamien it appears to be alright, the output of `print(X[0])` is
```
[[[ 0.13725491  0.17647059  0.13333334]
  [ 0.13725491  0.17647059  0.13333334]
  [ 0.13725491  0.17647059  0.13333334]
  ..., 
```
and the output of `print(Y[0])` is 
```
[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
```

**Comment by aymericdamien** [comment]
@2PacIsAlive Hi, that issue has been solved! Please reinstall TFLearn.

**Comment by 2PacIsAlive** [comment]
It works! Thanks! :shipit:

**Comment by EBMSASS** [comment]
@2PacIsAlive , @aymericdamien Hi, I get the same error for the following code (I've just installed the latest version of TFLearn: tflearn-0.2.1/tflearn-0.2.2):

```
model = tflearn.DNN(network, tensorboard_verbose=tensorboard_verbos_level, tensorboard_dir=summaries_dir)
model.fit(trainX, trainY, n_epoch = num_epochs, shuffle=True, validation_set=(testX, testY), show_metric=True, batch_size=batch_size)
```

print(trainX[0]) and print(trainY[0]) are:

```
[1 2 3 ..., 0 0 0]
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
```

The error that I get:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tflearn/data_flow.py", line 186, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "/tflearn/data_flow.py", line 221, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "/tflearn/utils.py", line 187, in slice_array
    return X[start]
TypeError: only integer arrays with one element can be converted to an index

Training samples: 689
Validation samples: 179
```

Any idea of how to resolve this issue is highly appreciated.

Thanks
