### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by abarrington** [tflearn/tflearn#868]
Hi, I have been having issues similar to #360 and #408. I am attempting to classify a single pixel into one of three categories. All solutions provided to #360 and #408 do not solve my problem. I restarted, added the reset_default_graph(), and in the second section of code converted the data a list.

**Original problem:**
>>> net = tflearn.input_data(shape=[None,1, 3])
>>> net = tflearn.lstm(net, 9)
>>> net = tflearn.fully_connected(net, 3, activation='softmax')
>>> net = tflearn.regression(net, optimizer='adam',
... loss='categorical_crossentropy', name="output1")
>>> model = tflearn.DNN(net, tensorboard_verbose=2)
>>> model.fit(data, labels, n_epoch=5, validation_set=0.1, show_metric=True,snapshot_step=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/models/dnn.py", line 183, in fit
    self.targets)
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/utils.py", line 283, in feed_dict_builder
    feed_dict[net_inputs[i]] = x
IndexError: list index out of range

**Attempt after converting to lists:**
>>> model.fit(X, Y, n_epoch=5, validation_set=0.1, show_metric=True,snapshot_step=100)
---------------------------------
Run id: ORFXDS
Log directory: /tmp/tflearn_logs/
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/utils.py", line 187, in slice_array
    return X[start]
IndexError: index 1091614 is out of bounds for axis 0 with size 1536

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/models/dnn.py", line 215, in fit
    callbacks=callbacks)
  File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 281, in fit
    vd = val_feed_dicts[i] if val_feed_dicts else None
IndexError: list index out of range

Is there an easy solution here?
Thank you

**Comment by aymericdamien** [comment]
Can you verify the shape of 'X'? and make sure it is in accordance with your input: [None,1, 3].
Also, can you try to remove the 'validation_set' param, to see if it is working without.

**Comment by abarrington** [comment]
I retried with this code:

```
from __future__ import division, print_function, absolute_import
import numpy as np
import tflearn
import scipy.io as sio
data = sio.loadmat('../tftest.mat')
labels = sio.loadmat('../tftest_labels.mat')
data = data['im']
data = dat.astype('float')
labels = labels['final']
labels = labels.reshape(3145728,1)
net = tflearn.input_data(shape=[None, 3])
net = tflearn.fully_connected(net, 9)
net = tflearn.fully_connected(net, 9)
net = tflearn.fully_connected(net, 3, activation='softmax')
net = tflearn.regression(net)
model = tflearn.DNN(net)
model.fit(data, labels, n_epoch=10, show_metric=True)
```
I verified that data.shape = 3145728,3 and labels.shape = 3145728,1. I also removed the validation set.

**Comment by gouthamand** [comment]
Hello All, 

Has this error been fixed ?. I have used tf.reset_default_graph().

call trace narrows to this code in /utils.py and feed_dict function.
/opt/conda/lib/python3.6/site-packages/tflearn/utils.py in feed_dict_builder(X, Y, net_inputs, net_targets)
    298                 X = [X]
    299             for i, x in enumerate(X):
--> 300                 feed_dict[net_inputs[i]] = x

update on this would be really appreciated.

**Comment by gouthamand** [comment]
One of things I observed is that following code created two separate input tensor
iname = input_data(shape= [None,name.shape[1]], name="iname" )
emb_name = embedding(iname, MAX_TEXT, 60//3) 

[<tf.Tensor 'iname/X:0' shape=(?, 13) dtype=float32>,
  <tf.Tensor 'netname/X:0' shape=(?, 13) dtype=float32>],

is that correct ?. Shouldn't it be create one only one tensor. When you provide one input for model.fit generates above stated error
list index out of range.

How to avoid generating two different input tensor.

Thanks in advance for the help.

**Comment by gouthamand** [comment]
Please kindly ignore the issue. I was embedding incorrectly. 
Thanks for opportunity to raise the issue.
