### ISSUE TITLE
How to obtain the output of a specific (or) intermediate layer in the network after training. 

### ISSUE THREAD

**Issue by konemshad** [tflearn/tflearn#887]
i have trained the following network:
              `
           self.network = input_data(shape=self.shape)

		self.network = conv_2d(self.network, 64, 3, activation='relu', name="conv_1_1")
		self.network = conv_2d(self.network, 64, 3, activation='relu',  name="conv_1_2")
		self.network = max_pool_2d(self.network, 2, strides=2)

		self.network = conv_2d(self.network, 128, 3, activation='relu', name="conv_2_1")
		self.network = conv_2d(self.network, 128, 3, activation='relu', name="conv_2_2")
		self.network = max_pool_2d(self.network, 2, strides=2)

		self.network = conv_2d(self.network, 256, 3, activation='relu', name="conv_3_1")
		self.network = conv_2d(self.network, 256, 3, activation='relu', name="conv_3_2")
		self.network = conv_2d(self.network, 256, 3, activation='relu', name="conv_3_3")
		self.network = max_pool_2d(self.network, 2, strides=2)

		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_4_1")
		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_4_2")
		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_4_3")
		self.network = max_pool_2d(self.network, 2, strides=2)

		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_5_1")
		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_5_2")
		self.network = conv_2d(self.network, 512, 3, activation='relu', name="conv_5_3")
		self.network = max_pool_2d(self.network, 2, strides=2)

	
		self.network = conv_2d(self.network,1024, 3 ,activation="relu", name="conv_6")
		self.network = global_avg_pool(self.network)
		self.network = fully_connected(self.network,4, activation='softmax')
		self.network = regression(self.network, optimizer='RMSProp',loss='categorical_crossentropy',learning_rate=0.0001)`
how do i get the output of the conv_6 layer. The implementation in keras for this is very simple, it is something like this:   `conv6 = model.layers[-4].output`

Is there any way to implement it in TFlearn?

Thanks.

**Comment by rodrigorpereira** [comment]
I had the same problem as I need to extract values after activation on specific layers for feature extraction.
Looking at the code I found a way to deal with it. You'll need to use evaluate function on the model predictor passing the image to it. Using your network as a model it goes like this:

```
data_input = tflearn.input_data(shape=[None, 227, 227, 3], name='input')
...
image_batch = ... # a batch of images
feed_dict = tflearn.utils.feed_dict_builder(image_batch , None, [data_input], None)
features = model.predictor.evaluate(feed_dict=feed_dict, ops=['conv_6/Relu:0'],  batch_size=1)
```
The predictor is an instance from a Evaluator class defined in evaluator.py. Its evaluate() function is defined with these arguments:

>  Arguments:
>             feed_dict: `dict`. The feed dictionary of data.
>             ops: list of `Tensors`. The tensors to evaluate.
>             batch_size: `int`. A batch size.

It' is diferent from DNN.evaluate, which evaluate over the train_ops defined in the model. But clearly it uses the same function to call the evaluation.

```# from DNN.evaluate():

    feed_dict = feed_dict_builder(X, Y, self.inputs, self.targets)
    ops = [o.metric for o in self.train_ops]
    return self.predictor.evaluate(feed_dict, ops, batch_size)
```
So we need just to pass to ops parameter the names  (as a list) of the Tensors we need to extract the values. Note that the function does only return 1 eval per op. If you pass more than one image in the batch it returns the mean evaluation over all the images on batch.

Hope it helps.

**Comment by konemshad** [comment]
Thanks for looking into the issue @rodrigorpereira  
when i run the following code 
` data_input = tflearn.input_data(shape=[None, 227, 227, 3], name='input')
model=p.run(op="LOAD",model_name="4datacm") #loading the model
X=images#array of images
feed_dict=feed_dict_builder(X,None,[data_input],None)
features = model.predictor.evaluate(feed_dict=feed_dict, ops=['conv_6/Relu:0'], batch_size=1) `

gives me this error:
`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tflearn/data_flow.py", line 195, in fill_feed_dict_queue
    data[k] = self.dprep_dict[k].apply(data[k])
KeyError: <tf.Tensor 'Placeholder:0' shape=(?, 224, 224, 3) dtype=float32>`
