### ISSUE TITLE
image_preloader versus build_hdf5_image_dataset

### ISSUE THREAD

**Issue by mbertalan** [tflearn/tflearn#907]
Thanks for creating this amazing API, I think TFlearn is great and make it very easy to use. 

I am trying to replicate the code to train inceptionV3 using my own data. However, I am getting a odd error when I try to run using the hdf5 file. My images are 400 by 300 in gray and png format. 

First I used: (This one works without any error)
dataset_file = '/home/Me/Test/classfile.tab'
X, Y = image_preloader(dataset_file, image_shape=(400, 300), mode='file', categorical_labels=True, normalize=True, files_extension="png", grayscale=True)

network = input_data(shape=[None, 300, 400, 1])
conv1_7_7 = conv_2d(network, 64, 7, strides=2, activation='relu', name='conv1_7_7_s2')

# Than I created the hdf5 file:
dataset_file = '/home/Me/Test/classfile.tab'
from tflearn.data_utils import build_hdf5_image_dataset
build_hdf5_image_dataset(dataset_file, image_shape=(400, 300), mode='file', output_path='test2.h5', categorical_labels=True, normalize=True, grayscale=True, files_extension="png")

# Run using the command:
...
import h5py
h5f = h5py.File('/home/bertalan/Test/hdf5/test2.h5', 'r')
X = h5f['X']
Y = h5f['Y']

network = input_data(shape=[None, 300, 400, 1])
...

I get the error: (ValueError: Cannot feed value of shape (28, 300, 400) for Tensor u'InputData/X:0', which has shape '(?, 300, 400, 1)'). Where 28 is my batch size. Why the value is not a 4D ? Any suggestions ? 

python TrainingUsingTFLearn.py 
2017-09-19 18:21:37.724161: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 18:21:37.724205: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 18:21:37.724219: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
---------------------------------
Run id: test3
Log directory: /home/Me/Test/tflearn/Test/train_logs/
---------------------------------
Training samples: 160
Validation samples: 40
--
--
Traceback (most recent call last):
  File "TrainingUsingTFLearn.py", line 136, in <module>
    snapshot_epoch=True, run_id='test3')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 216, in fit
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 338, in fit
    show_metric)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 817, in _train
    feed_batch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (28, 300, 400) for Tensor u'InputData/X:0', which has shape '(?, 300, 400, 1)'

**Comment by sctb512** [comment]
so, what the answer is ?
