### ISSUE TITLE
Initializing Vocab Processor with vocabulary doesn't work

### ISSUE THREAD

**Issue by zotroneneis** [tflearn/tflearn#919]
I am using the VocabularyProcessor to map documents to integer arrays. However, I don't seem to be able to initialize the VocabProcessor with my own vocabulary. In the docs it says that I can provide a vocabulary when creating the VocabProcessor as in:

    vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length, vocabulary=vocab)

However, when creating the VocabularyProcessor like this I cannot transform my documents properly. Using

    vocab_processor.transform(sentences)))

doesn't transform and/or return the sentences. As a consequence calling 

    transformed_document = np.array(list(vocab_processor.transform(sentences)))

throws an error:

    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

I am providing the vocabulary as a dictionary, using the indices as values as in:

    vocab = {'word1': 1, 'word2': 80, ...}

**Comment by sbmaruf** [comment]
@zotroneneis  

Let's have some experiment to answer your question,
```
vocab={'hello':3, '.':5, 'world':20, '/' : 10}
sentences= ['hello world . / hello', 'hello']

vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length=6, vocabulary=vocab)
list(vocab_processor.transform(sentences)) 
```
The output of the following code segment is,
`[array([ 3, 20,  3,  0,  0,  0]), array([3, 0, 0, 0, 0, 0])]`

Now you may already see that space(' ') and dot('.') both are actually not tokenized. To perform tokenization on them you may write your own tokenized function. A sample code is given below.

```
def my_func(iterator):
  return (x.split(" ") for x in iterator)

vocab={'hello':3, '.':5, 'world':20, '/' : 10}
sentences= ['hello world . / hello', 'hello']

vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length=6, vocabulary=vocab, tokenizer_fn = my_func)

list(vocab_processor.transform(sentences)) 
```

Now the output of the code segment is like
`[array([ 3, 20,  5, 10,  3,  0]), array([3, 0, 0, 0, 0, 0])]`

which is the expected output. hope this makes your confusion clear.

Your next confusion might be what are the values that will be tokenized by default. Let me post here the original [source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/preprocessing/text.py) so that you can never be confused,

```
TOKENIZER_RE = re.compile(r"[A-Z]{2,}(?![a-z])|[A-Z][a-z]+(?=[A-Z])|[\'\w\-]+",
                          re.UNICODE)
def tokenizer(iterator):
  """Tokenizer generator.
  Args:
    iterator: Input iterator with strings.
  Yields:
    array of tokens per each value in the input.
  """
  for value in iterator:
    yield TOKENIZER_RE.findall(value)
```

but my suggestion will be, **"write your own function and be confident"**

**Comment by nidhikamath91** [comment]
I tried the same method.
vocab={'<UNK>': 0, 'hello':3, 'here':5, 'world':20}
sentences= ['hello summer ', 'summer is here']
vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length, vocabulary=vocab)

np.array(list(processor.transform(sentences))) 

I get the below error 

Traceback (most recent call last):
  File "features-predict.py", line 74, in <module>
    x_test = np.array(list(vocab_processor.transform(data_text)))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 188, in transform
    word_ids[idx] = self.vocabulary_.get(token)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Instead shouldnt it be 

[3 0 0]
[0 0 5]
