### ISSUE TITLE
Unable to use tflearn/examples/nlp/bidirectional_lstm.py  ，who  can help me？

### ISSUE THREAD

**Issue by luoyexuge** [tflearn/tflearn#935]

**Comment by luoyexuge** [comment]
Traceback (most recent call last):
  File "/Users/shuubiasahi/Documents/python/tflearnexcise/bidirectional_lstmdemo.py", line 34, in <module>
    net=bidirectional_rnn(net,rnncell_fw,rnncell_bw,dynamic=False)
  File "/anaconda/lib/python3.5/site-packages/tflearn/layers/recurrent.py", line 374, in bidirectional_rnn
    dtype=tf.float32)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 375, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 574, in dynamic_rnn
    dtype=dtype)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 637, in _dynamic_rnn_loop
    for input_ in flat_input)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 637, in <genexpr>
    for input_ in flat_input)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 649, in with_rank_at_least
    raise ValueError("Shape %s must have rank at least %d" % (self, rank))
ValueError: Shape (128, ?) must have rank at least 3

**Comment by jbn** [comment]
See this prior PR: https://github.com/tflearn/tflearn/pull/825
