### ISSUE TITLE
Quickstart does not work, at all

### ISSUE THREAD

**Issue by cmosh** [tflearn/tflearn#947]
Just using the load.csv method returns an error. Why do I need to debug a quickstart?

`import numpy as np
import tflearn

# Download the Titanic dataset
from tflearn.datasets import titanic
titanic.download_dataset('titanic_dataset.csv')

# Load CSV file, indicate that the first column represents labels
from tflearn.data_utils import load_csv
data, labels = load_csv('titanic_dataset.csv', target_column=0,
                        categorical_labels=True, n_classes=2)`

Gives this error. Tensorflow works

`Traceback (most recent call last):
  File "titanic.py", line 10, in <module>
    data, labels = load_csv('./titanic_dataset.csv', target_column=0, categorical_labels=True, n_classes=2)
  File "/home/clive/.envs/tflearn/lib/python3.4/site-packages/tflearn/data_utils.py", line 805, in load_csv
    target = to_categorical(target, n_classes)
  File "/home/clive/.envs/tflearn/lib/python3.4/site-packages/tflearn/data_utils.py", line 46, in to_categorical
    return (y[:, None] == np.unique(y)).astype(np.float32)
TypeError: list indices must be integers, not tuple
`

**Comment by Istoman** [comment]
I've got the same issue, I mean, I tried looking into it with no success, the documentation is clear and the given code should totally work.

Have you found a way around it since then ?

**Comment by cmosh** [comment]
I lost interest the moment the quickstart failed, it's just better to use tensorflow directly
