### ISSUE TITLE
Save model and load it on another model with same structure

### ISSUE THREAD

**Issue by TheRealfanibu** [tflearn/tflearn#951]
I have two DNN-models with the same structure and I want to train them independently, but I want to transfer the weights of the first model to the second model at runtime.
 
```
import tflearn
from tflearn.layers.core import input_data, fully_connected
from tflearn.layers.estimator import regression

def create_model(shape):
    fc = fully_connected(shape, n_units=12, activation="relu")
    fc2 = fully_connected(fc, n_units=2, activation="softmax")
    regressor = regression(fc2)

    return tflearn.DNN(regressor)

shape = input_data([None, 2])

model1 = create_model(shape)  #first model
model2 = create_model(shape)  #second model

"""
...
train model1
...
"""

path = "models/test_model.tfl"
model1.save(path) 
model2.load(path, weights_only=True)  #get the weights of the first model 
```

If I run this I get the following Error:

```
2017-11-05 17:42:47.978858: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key FullyConnected_3/b not found in checkpoint
2017-11-05 17:42:47.981882: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key FullyConnected_3/W not found in checkpoint
2017-11-05 17:42:47.982010: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key FullyConnected_2/b not found in checkpoint
2017-11-05 17:42:47.982181: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Key FullyConnected_2/W not found in checkpoint
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key FullyConnected_3/b not found in checkpoint
	 [[Node: save_6/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_6/Const_0_0, save_6/RestoreV2_7/tensor_names, save_6/RestoreV2_7/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Jonas/PycharmProjects/ReinforcementLearning/TflearnSaveLoadTest.py", line 20, in <module>
    model2.load(path, weights_only=True)
  File "D:\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "D:\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 492, in restore
    self.restorer_trainvars.restore(self.session, model_file)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key FullyConnected_3/b not found in checkpoint
	 [[Node: save_6/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_6/Const_0_0, save_6/RestoreV2_7/tensor_names, save_6/RestoreV2_7/shape_and_slices)]]

Caused by op 'save_6/RestoreV2_7', defined at:
  File "C:/Users/Jonas/PycharmProjects/ReinforcementLearning/TflearnSaveLoadTest.py", line 16, in <module>
    model2 = create_model(shape)
  File "C:/Users/Jonas/PycharmProjects/ReinforcementLearning/TflearnSaveLoadTest.py", line 11, in create_model
    return tflearn.DNN(regressor)
  File "D:\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "D:\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 155, in __init__
    allow_empty=True)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1218, in __init__
    self.build()
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1020, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key FullyConnected_3/b not found in checkpoint
	 [[Node: save_6/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_6/Const_0_0, save_6/RestoreV2_7/tensor_names, save_6/RestoreV2_7/shape_and_slices)]]
```

Any suggestions on how to fix this error?

**Comment by sjeongchoi** [comment]
I solved the similar problem. try reset tensorflow graph. 
(tf.reset_default_graph())
