### ISSUE TITLE
how can i save model as 

### ISSUE THREAD

**Issue by fffupeng** [tflearn/tflearn#964]

**Comment by BBarbosa** [comment]
Hi @fffupeng!
I use an additional script to do that. 

```"""
Tensorflow graph freezer
Converts Tensorflow trained models in .pb

Code adapted from:
https://gist.github.com/morgangiraud/249505f540a5e53a48b0c1a869d370bf#file-medium-tffreeze-1-py
"""

import os, argparse
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow.python.framework import graph_util

def freeze_graph(model_folder,output_graph="frozen_model.pb"):
    # We retrieve our checkpoint fullpath
    try:
        checkpoint = tf.train.get_checkpoint_state(model_folder)
        input_checkpoint = checkpoint.model_checkpoint_path
        print("[INFO] input_checkpoint:", input_checkpoint)
    except:
        input_checkpoint = model_folder
        print("[INFO] Model folder", model_folder)

    # Before exporting our graph, we need to precise what is our output node
    # This is how TF decides what part of the Graph he has to keep and what part it can dump
    output_node_names = "FullyConnected/Softmax" # NOTE: Change here

    # We clear devices to allow TensorFlow to control on which device it will load operations
    clear_devices = True
    
    # We import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)

    # We retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    # We start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)

        # We use a built-in TF helper to export variables to constants
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,                        # The session is used to retrieve the weights
            input_graph_def,             # The graph_def is used to retrieve the nodes 
            output_node_names.split(",") # The output node names are used to select the usefull nodes
        ) 

        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))

        print("[INFO] output_graph:",output_graph)
        print("[INFO] all done")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Tensorflow graph freezer\nConverts trained models to .pb file",
                                     prefix_chars='-')
    parser.add_argument("--mfolder", type=str, help="model folder to export")
    parser.add_argument("--ograph", type=str, help="output graph name", default="frozen_model.pb")
    
    args = parser.parse_args()
    print(args,"\n")

    freeze_graph(args.mfolder,args.ograph)
```

However, before doing model.save(...) on TFLearn i have to do
``` del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:] ```

Then I call this command
``` python tf_freeze.py --mfolder=<path_to_tflearn_model>```

*Note* 
- The <path_to_tflearn_model> must not have the ".data-00000-of-00001".
- The _output_node_names_ variable may change depending on your architecture. The thing is that you must reference the layer that has the softmax activation function.

**Comment by thenathan30** [comment]
Hi,
I get :
> File export/model.tlf.meta does not exist.
I read, that TFlearn use different order on line :
`saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)`

So have you an idea ?

Thanks

**Comment by MidsizeMango** [comment]
What is to be replaced here 
" output_node_names = "FullyConnected/Softmax" "?

**Comment by BBarbosa** [comment]
Hi @thenathan30 !
Can you show me a snapshot of your directory tree where your model is stored?

**Comment by BBarbosa** [comment]
Hi @MidsizeMango!
You should visualize your network on the TensorBoard and check which layer you want to export. In this case (classification problem) i need the output of the softmax function.

**Comment by poojashah89** [comment]
@BBarbosa I am using softmax activation on 2 layer to convert my model using tflearn. I did not get the part where you mentioned about "output_node_names" Where exactly that value I will get from ?

**Comment by BBarbosa** [comment]
Hi @poojashah89!
Take a look on this [https://gist.github.com/morgangiraud/249505f540a5e53a48b0c1a869d370bf#gistcomment-2195007](link)

**Comment by kerolos** [comment]
hello everyone,
Does anyone know how to save the proper metafile or (.pb format) to load from c++? 
furthermore, should I initialize a session and feed it into tflearn.DNN function?
I really appreciate your help.

the code : 
import tensorflow as tf

import tflearn 
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression
from tflearn.layers.normalization import local_response_normalization

TRAIN_DIR = '/home/Desktop/tflearn/model1'
IMG_SIZE = 50
LR = 1e-4

train_data=np.load('train_data.npy')

#MODEL_NAME = 'flowers-{}-{}.model'.format(LR, '2conv-basic')
MODEL_NAME = 'graph.chkp'
convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = local_response_normalization(convnet)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = local_response_normalization(convnet)

convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = conv_2d(convnet, 265, 5, activation='relu')
convnet = conv_2d(convnet,512, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = local_response_normalization(convnet)

convnet = conv_2d(convnet, 265, 5, activation='relu')
convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = local_response_normalization(convnet)

convnet = fully_connected(convnet, 4096, activation='tanh')
convnet = dropout(convnet, 0.5)
convnet = fully_connected(convnet, 1024, activation='tanh')
convnet = dropout(convnet, 0.5)
convnet = fully_connected(convnet, 4, activation='softmax',name="output")
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

config = tf.ConfigProto()
#config.gpu_options.per_process_gpu_memory_fraction = 0.9
#session = tf.Session(config=tf.ConfigProto(log_device_placement=True))
sess = tf.Session(config=config)

model = tflearn.DNN(convnet,tensorboard_dir='log')  #,session=sess

train = train_data[:-94]
test = train_data[-94:]

X = np.array([i[0] for i in train]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
Y = [i[1] for i in train]

test_x = np.array([i[0] for i in test]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
test_y = [i[1] for i in test]

model.fit({'input': X}, {'targets': Y}, n_epoch=10, validation_set=({'input': test_x}, {'targets': test_y}), 
    snapshot_step=500, snapshot_epoch=False, shuffle=True, show_metric=True, batch_size=64, run_id=MODEL_NAME)
model.save(MODEL_NAME)

**Comment by kucinghitam13** [comment]
Hi @BBarbosa,

 I've run your script (including your code before saving the model) and got this error.

```
<ipython-input-33-d25c7e46cc6b> in freeze_graph(model_folder, output_graph)
28     # We start a session and restore the graph weights
     29     with tf.Session() as sess:
---> 30         saver.restore(sess, input_checkpoint)
     31 
     32         # We use a built-in TF helper to export variables to constants

AttributeError: 'NoneType' object has no attribute 'restore'
```

My model variable was dnn object from tflearn and seems like it doesn't have any restore method. Any idea how to get around this?

Thanks

**Comment by kucinghitam13** [comment]
Hi @BBarbosa,

I've run your code to freeze my tflearn model using output node name "FullyConnected_1/Softmax" and got this message.

```
[INFO] Model folder C:\Dika Adhitama\Machine Learning\Leaf Classification\Model\mk1\leafclassifier-CNN-mk1.model.ckpt3
INFO:tensorflow:Restoring parameters from C:\Dika Adhitama\Machine Learning\Leaf Classification\Model\mk1\leafclassifier-CNN-mk1.model.ckpt3
INFO:tensorflow:Froze 13 variables.
Converted 13 variables to const ops.
69 ops in the final graph.
[INFO] output_graph: C:\Dika Adhitama\Machine Learning\Leaf Classification\Model\mk1\leafclassifier-CNN-mk1.model.frozen_graph.pb
[INFO] all done
```

Then on different runtime I tried to load the .pb file using this code after I've defined my model architect.
```
with tf.Session() as sess:
    with gfile.FastGFile(MODEL_NAME + '.frozen_graph.pb','rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')
```

But then when I tried to make a prediction using `model.predict()` , it gave me a wrong prediction and as if my model hasn't even been trained yet. Is there something I miss here?

**Comment by BBarbosa** [comment]
Hi @kucinghitam13!
I'm glad you made it. 
Did you apply any preprocessing methods in your training? If you did, you must replicate them as well.

**Comment by kucinghitam13** [comment]
> Hi @kucinghitam13!
> I'm glad you made it.
> Did you apply any preprocessing methods in your training? If you did, you must replicate them as well.

Thank you for your response. Yes I did in both training and testing. I finally managed to accurately predict my test data but I was using general tensorflow, not tflearn, thus I concluded the graph exportation worked fine.

The problem was on loading the frozen graph and predicting the test data using tflearn. So far I haven't found any other way so that my loaded graph can be used in tflearn using `model.predict()` and seems like tflearn wasn't build to do this yet, at least from my underastanding.

**Comment by BBarbosa** [comment]
As far as I know, TFLearn can't run frozen graphs. 
Currently, I use frozen graphs on: 
- OpenCV DNN Module
- TensorFlow Mobile 
- TensorFlow (general)

Otherwise, I use the specific TFLearn or Keras model loaders.

**Comment by zhenhua10** [comment]
> As far as I know, TFLearn can't run frozen graphs.
> Currently, I use frozen graphs on:
> 
> * OpenCV DNN Module
> * TensorFlow Mobile
> * TensorFlow (general)
> 
> Otherwise, I use the specific TFLearn or Keras model loaders.

I also encountered a similar problem with kucinghitam13, Inaccurate prediction，my prediction code is as follows:

from tensorflow.python.platform import gfile
with tf.Graph().as_default():
   output_graph_def = tf.GraphDef()
   with open("pretrained\model.pb", "rb") as f:
      output_graph_def.ParseFromString(f.read())
      tensors = tf.import_graph_def(output_graph_def, name="")
      print(tensors)
   with tf.Session() as sess:
      init = tf.global_variables_initializer()
      sess.run(init)
      op = sess.graph.get_operations()
     

      op = sess.graph.get_tensor_by_name("FullyConnected_1/Softmax:0")
      input_tensor = sess.graph.get_tensor_by_name('InputData/X:0')
      probs = sess.run(op,feed_dict = {input_tensor:X})


      print(probs)

The four files that are used to export the PB file are：
checkpoint
xor.infer.tflearn.data-00000-of-00001
xor.infer.tflearn.index
xor.infer.tflearn.meta

What is wrong with me? Thank you！

**Comment by fly2015** [comment]
I am facing the same problem. I can not freeze graph the model files which was trained by tflean.
Here is the list of files after I made a training 
- checkpoint
- model.tflearn.index
- model.tflearn.data-00000-of-00001
- model.tflearn.meta
- training_data

My purpose is: I would like to freeze these file to a ".pb" file for using in java program.
Currently, I could not find any solution for resolving this problem. 
I used the lines of code above to try freeze_graph and saw the errors

[INFO] input_checkpoint: D:\chatbot\chatbot-demo\models\model.tflearn
Traceback (most recent call last):
  File "D:\chatbot\chatbot-demo\freeze_graph.py", line 59, in <module>
    freeze_graph(args.mfolder,args.ograph)
  File "D:\chatbot\chatbot-demo\freeze_graph.py", line 24, in freeze_graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1960, in import_meta_graph
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 790, in import_scoped_meta_graph
    ops.prepend_name_scope(value, scope_to_prepend_to_names))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3613, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3673, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'Adam' refers to an Operation not in the graph."

Can TFLearn run frozen graphs?
Or how I can use trained files by java tensorflow lib?

Please help me ! Thanks

**Comment by BBarbosa** [comment]
Hi @fly2015!
As I mentioned on https://github.com/tflearn/tflearn/issues/964#issuecomment-350717215, try to do
`del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]` before saving model.

**Comment by BBarbosa** [comment]
You are welcome @fly2015
From your code I see that you forget to include the word `del`  before `tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]`
Can you try it again please?

**Comment by fly2015** [comment]
@BBarbosa Many thanks.
I can freeze the model to ".pb" file.

I am trying to use java tensorflow lib to read this file and make predictions.

Do you have any suggestion for me? Is it possible?

Best thanks you again.

**Comment by BBarbosa** [comment]
Hi @fly2015!
I'm glad you made it.
At the moment I use frozen models on an Android app. 
However, I never tried it on Java.

Best regards.

**Comment by lakwinc** [comment]
Hi @BBarbosa 

I am new to tflearn and I want to save following model as a .pb file. Can you please explain the steps i should follow?

```
import cv2                
import numpy as np        
import os           
from random import shuffle
from tqdm import tqdm   

TRAIN_DIR = 'D:\\My Projects\\Dataset\\dataset5_for_testing\\train'
TEST_DIR = 'D:\\My Projects\\Dataset\\dataset5_for_testing\\test'
IMG_SIZE = 50
LR = 1e-3

MODEL_NAME = 'snakes-{}-{}.model'.format(LR, '2conv-basic')

def label_img(img):
    print("\nimg inside label_img",img)
    print("\n",img.split('.')[-2])
    temp_name= img.split('.')[-2]
    print("\n",temp_name[:1])
    temp_name=temp_name[:1]
    word_label = temp_name
    

  
    if word_label == 'A': return [0,0,0,0,1]   
    elif word_label == 'B': return [0,0,0,1,0]  
    elif word_label == 'C': return [0,0,1,0,0] 
    elif word_label == 'D': return [0,1,0,0,0] 
    elif word_label == 'E' : return [1,0,0,0,0]

def create_train_data():
    training_data = []
    for img in tqdm(os.listdir(TRAIN_DIR)):
        label = label_img(img)
        path = os.path.join(TRAIN_DIR,img)
        img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        training_data.append([np.array(img),np.array(label)])
    shuffle(training_data)
    np.save('train_data.npy', training_data)
    return training_data


def process_test_data():
    testing_data = []
    for img in tqdm(os.listdir(TEST_DIR)):
        path = os.path.join(TEST_DIR,img)
        img_num = img.split('.')[0]
        img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        testing_data.append([np.array(img), img_num])
    shuffle(testing_data)
    np.save('test_data.npy', testing_data)
    return testing_data

train_data = create_train_data()


import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

import tensorflow as tf
tf.reset_default_graph()

convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 5, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet, tensorboard_dir='log')



if os.path.exists('{}.meta'.format(MODEL_NAME)):
    model.load(MODEL_NAME)
    print('model loaded!')


train = train_data[:-200]
test = train_data[-200:]

X = np.array([i[0] for i in train]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
Y = [i[1] for i in train]

test_x = np.array([i[0] for i in test]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
test_y = [i[1] for i in test]

model.fit({'input': X}, {'targets': Y}, n_epoch=3, validation_set=({'input': test_x}, {'targets': test_y}), 
    snapshot_step=500, show_metric=True, run_id=MODEL_NAME)

del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]

model.save(MODEL_NAME)
print('Done!')


```

**Comment by BBarbosa** [comment]
Hi @lakwinc!
Please try to use the script that is on [here](https://github.com/tflearn/tflearn/issues/964#issuecomment-350717215). 
Once your network architecture has the _Softmax_ activation on the second Fully Connected layer you must adapt the script and re-write this snippet
`output_node_names = "FullyConnected_1/Softmax"`

**Comment by lakwinc** [comment]
Hi @BBarbosa!
I use anaconda environment. So, should I save freeze.py python script in the folder which i saved the model and then run python tf_freeze.py --mfolder=<path_to_tflearn_model> in shell? or?

**Comment by BBarbosa** [comment]
Hi @lakwinc!
If you save the _freeze.py_ in the directory where you saved the model then i think you need to open a commnads line and execute
```python tf_freeze.py --mfolder=.```

**Comment by marination** [comment]
Hi, i am facing the same issue as @fly2015 , i get the error  "The name 'Adam' refers to an Operation not in the graph." I did do the following before saving the model:
`g= tf.Graph()
with g.as_default():
    del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]
# save the model
model.save('signs.tflearn')`
issue originates from this line:
`saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)`
Any help will be appreciated
