### ISSUE TITLE
libale_c.so: mach-o, but built for simulator (not macOS)

### ISSUE THREAD

**Issue by tonychan818** [tflearn/tflearn#975]
Chungs-MacBook-Pro:reinforcement_learning chungchan$ python atari_1step_qlearning.py 
2017-12-11 18:10:37.025935: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "atari_1step_qlearning.py", line 465, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "atari_1step_qlearning.py", line 455, in main
    num_actions = get_num_actions()
  File "atari_1step_qlearning.py", line 373, in get_num_actions
    env = gym.make(game)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 164, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 122, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 88, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/usr/local/lib/python2.7/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/usr/local/lib/python2.7/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/usr/local/lib/python2.7/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so, 6): no suitable image found.  Did find:
	/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)
	/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)

any idea?

**Comment by liuyangvoid** [comment]
do you know how to fix it?
