### ISSUE TITLE
Error Importing tflearn

### ISSUE THREAD

**Issue by AjejeBrazorfEU** [tflearn/tflearn#985]
When trying to import tflearn i get this error:
`Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found(I translated this)`

I've simply installed tflearn with :
`pip install tflearn`

**Comment by AjejeBrazorfEU** [comment]
Solved installing Cuda 8.0 and cuDNN v 6.0
