### ISSUE TITLE
Bidirectional LTSM example throws shape error

### ISSUE THREAD

**Issue by yuzhou164** [tflearn/tflearn#988]
Running the following file throws an error:
https://github.com/tflearn/tflearn/blob/master/examples/nlp/bidirectional_lstm.py

ValueError: Shape (128, ?) must have rank at least 3

Setup:
win7 64
Python 3.5
Tensorflow v1.4.0
```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/machine learning/DL/tflearn/bidirectional_lstm.py", line 26, in <module>
    net = bidirectional_rnn(net, BasicLSTMCell(128), BasicLSTMCell(128))
  File "D:\Anaconda2\envs\py3\lib\site-packages\tflearn\layers\recurrent.py", line 374, in bidirectional_rnn
    dtype=tf.float32)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\ops\rnn.py", line 401, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\ops\rnn.py", line 614, in dynamic_rnn
    dtype=dtype)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\ops\rnn.py", line 677, in _dynamic_rnn_loop
    for input_ in flat_input)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\ops\rnn.py", line 677, in <genexpr>
    for input_ in flat_input)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 670, in with_rank_at_least
    raise ValueError("Shape %s must have rank at least %d" % (self, rank))
ValueError: Shape (128, ?) must have rank at least 3
```

**Comment by hkhatod** [comment]
I am having same problem.
