### ISSUE TITLE
ImportError: cannot import name 'add_arg_scope'

### ISSUE THREAD

**Issue by 1658484908** [tflearn/tflearn#996]
my use tensorflow1.5.0rc in 17flower example
`Traceback (most recent call last):
  File "E:/ml/flower/flower.py", line 1, in <module>
    import tflearn
  File "D:\anconda\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "D:\anconda\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "D:\anconda\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ImportError: cannot import name 'add_arg_scope'`

in tensorflow1.5.0rc contrib-》framework-》python
there isnot  add_arg_scope

**Comment by aymericdamien** [comment]
I tried with TF 1.5.0rc0 and cannot reproduce this error, it is working fine for me. I used this built: ```pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.5.0rc0-py2-none-any.whl```

Also, it seems that `add_arg_scope` is still under 'tensorflow.contrib.framework.python.ops' in both master and v1.5.0 branches. [r1.5 branch](https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/contrib/framework/python/ops/arg_scope.py#L166), [master branch](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/arg_scope.py#L166)

**Comment by 1658484908** [comment]
I uninstall tensorflow and install tensorflow again .I see the add_arg_scope .Maybe I installed incomplete.
