### ISSUE TITLE
AlexNet and Mnist--ValueError: None values not supported

### ISSUE THREAD

**Issue by HI160029** [tflearn/tflearn#999]
I ran an AlexNet code to train the MNIST dataset and get this error. What does it mean? And how to slove it??

Traceback (most recent call last):
  File "alexnet_mnist.py", line 161, in <module>
    pred = alexnet(x, weights,biases,keep_prob) # Feedforward predicted value
  File "alexnet_mnist.py", line 112, in alexnet
    _fc1_drop = tf.nn.dropout(_fc1, _keep_pro) 	# Dropout is applied for the preventtion of overfitting
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1894, in dropout
    x = ops.convert_to_tensor(x, name="x")
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/joshua/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

**Comment by aymericdamien** [comment]
It seems that your variable `_fc1` is `None`, thus it is not working. Can you check that it is actually a Tensor?

**Comment by HI160029** [comment]
I have found the mistake. It was just typo.
